### ISSUE TITLE
win_iis_website "parameters" parameter not idempotent

### ISSUE THREAD

**Issue by bkonicek** [ansible-collections/ansible.windows#114]
##### SUMMARY
The `win_iis_website` module is no longer idempotent when defining 'parameters:` If the property is defined it reports "Changed" on every run. As soon as it is commented out it stops reporting changes in the play.

This is similar to https://github.com/ansible/ansible/issues/34500 but seems to have regressed to any parameters, not just the specific one in the previous issue

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
community.windows.win_iis_website

##### ANSIBLE VERSION

```
ansible 2.10.2
```

##### OS / ENVIRONMENT
Ubuntu 18.04
Remote host - Windows Server 2019

##### STEPS TO REPRODUCE
Create a Windows 2019 server that Ansible can reach. Install IIS and run a playbook to create a win_iis_website

```yaml
- community.windows.win_iis_website:
     name: testsite
     application_pool: DefaultAppPool
     port: 80
     physical_path: C:\inetpub\wwwroot
     state: started
     parameters: logfile.directory:C:\inetpub
```

##### EXPECTED RESULTS
After running the playbook once, subsequent runs should report no changes.

```
HOSTNAME               : ok=1 changed=0
```

##### ACTUAL RESULTS
Every time the above task is run changes are reported.

```
HOSTNAME               : ok=1 changed=1
```
