### ISSUE TITLE
List of paths not supported by win_file 

### ISSUE THREAD

**Issue by Expresso31** [ansible-collections/ansible.windows#121]
ansible.windows.win_file:
        path: 
        - C:\folder
        - C:\folder\subfolder
        - C:\folder
        - C:\folder\subfolder
        state: directory

**Comment by inorangestylee** [comment]
Use it with `loop` https://docs.ansible.com/ansible/latest/user_guide/playbooks_loops.html#iterating-over-a-simple-list
This is what it exists for
```
  - ansible.windows.win_file:
      path: "{{ item }}"
      state: directory
    loop:
      - C:\folder1
      - C:\folder2\subfolder
      - C:\folder3
      - C:\folder4\subfolder
```
