### ISSUE TITLE
win_hostname Reboot

### ISSUE THREAD

**Issue by jimbo8098** [ansible-collections/ansible.windows#126]
##### SUMMARY

Currently, when changing hostname on a Windows server you usually have to reboot leading to two separate tasks, just like in the example documentation:

```
- name: Change the hostname to sample-hostname
  ansible.windows.win_hostname:
    name: sample-hostname
  register: res

- name: Reboot
  ansible.windows.win_reboot:
  when: res.reboot_required
```

Would it be worthwhile to add a `reboot` parameter to this which would simply reboot the machine following it's renaming?

```
- name: Change the hostname to sample-hostname
  ansible.windows.win_hostname:
    name: sample-hostname
    reboot: yes
```
##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

win_hostname
##### ADDITIONAL INFORMATION

```
- name: Change the hostname to sample-hostname
  ansible.windows.win_hostname:
    name: sample-hostname
    reboot: yes
```
