### ISSUE TITLE
win_dsc fails to serialize properties into CimInstance

### ISSUE THREAD

**Issue by jborean93** [ansible-collections/ansible.windows#15]
_From @Rukas on Aug 10, 2018 18:48_

##### SUMMARY

Using win_dsc results in the following error: `Failed to serialize properties into CimInstance.`

The same configuration in pure DSC works without issue:

```
        xIEEsc DisableIEEscAdmin {
            IsEnabled = $false
            UserRole  = "Administrators"   
        }
```

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

- win_dsc
##### ANSIBLE VERSION

```
2.6.2
```

##### CONFIGURATION

```
DEFAULT_FORKS(/opt/devops-ansible/playbooks/test/ansible.cfg) = 40
DEFAULT_HOST_LIST(/opt/devops-ansible/playbooks/test/ansible.cfg) = [u'/opt/devops-ansible/playbooks/test/hosts.yml']
DEFAULT_LOG_PATH(/opt/devops-ansible/playbooks/test/ansible.cfg) = /opt/devops-ansible/playbooks/test/playbook.log
PERSISTENT_CONNECT_TIMEOUT(/opt/devops-ansible/playbooks/test/ansible.cfg) = 30
```
##### OS / ENVIRONMENT

From Ubuntu 16.04.2
Managing Server 2016

##### STEPS TO REPRODUCE

hosts.yml
```yaml
sql:
  hosts:
    10.2.1.6:
      ansible_winrm_server_cert_validation: ignore
      ansible_connection: winrm
      ansible_user: "some user"
      ansible_password: "some vault password"
```
test_playbook.yml
```yaml
---
- hosts: sql
  gather_facts: true
  tasks:
    - name: Install PSDesiredStateConfiguration PowerShell Module
      win_psmodule:
        name: PSDesiredStateConfiguration
        state: present
    - name: Install xSystemSecurity PowerShell Module
      win_psmodule:
        name: xSystemSecurity
        state: present
    - name: Set IE security to disabled for Administrators
      win_dsc:
        resource_name: xIEEsc
        IsEnabled: false
        UserRole: 'Administrators'
        PsDscRunAsCredential_username: '{{ansible_user}}'
        PsDscRunAsCredential_password: '{{ansible_password}}'
```

##### EXPECTED RESULTS

The DSC configuration to be successful

##### ACTUAL RESULTS

```
ansible-playbook test_playbook.yml -i hosts.yml -vv --ask-vault-pass

ansible-playbook 2.6.2
  config file = /opt/devops-ansible/playbooks/test/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
Using /opt/devops-ansible/playbooks/test/ansible.cfg as config file

PLAYBOOK: test_playbook.yml *********************************************************************************************************************************************************
1 plays in test_playbook.yml

PLAY [sql] **************************************************************************************************************************************************************************

TASK [Gathering Facts] **************************************************************************************************************************************************************
task path: /opt/devops-ansible/playbooks/test/test_playbook.yml:2
ok: [10.2.1.6]
META: ran handlers

TASK [Install PSDesiredStateConfiguration PowerShell Module] ************************************************************************************************************************
task path: /opt/devops-ansible/playbooks/test/test_playbook.yml:5
ok: [10.2.1.6] => {"changed": false, "nuget_changed": false, "output": "Module PSDesiredStateConfiguration already present", "repository_changed": false}

TASK [Install xSystemSecurity PowerShell Module] ************************************************************************************************************************************
task path: /opt/devops-ansible/playbooks/test/test_playbook.yml:9
ok: [10.2.1.6] => {"changed": false, "nuget_changed": false, "output": "Module xSystemSecurity already present", "repository_changed": false}

TASK [Set IE security to disabled for Administrators] *******************************************************************************************************************************
task path: /opt/devops-ansible/playbooks/test/test_playbook.yml:13
fatal: [10.2.1.6]: FAILED! => {"changed": false, "module_version": "1.4.0.0", "msg": "Failed to serialize properties into CimInstance.", "reboot_required": false}
        to retry, use: --limit @/opt/devops-ansible/playbooks/test/test_playbook.retry

PLAY RECAP **************************************************************************************************************************************************************************
10.2.1.6                   : ok=3    changed=0    unreachable=0    failed=1
```

```


_Copied from original issue: ansible/ansible#43975_

**Comment by jborean93** [comment]
_From @Rukas on Aug 10, 2018 19:35_

This seems to only happen with that specific DSC module so far.  I'm using a few others without issue such as: 
- StorageDsc
  - OpticalDiskDriveLetter
  - WaitForDisk
  - Disk
- WindowsDefender
  - WindowsDefender

**Comment by jborean93** [comment]
_From @gstorme on Jun 21, 2019 11:58_

I've encountered this error with the Disk resource on a Windows Server 2016, with ansible 2.7.
This resource has worked before though, on other systems.

```yaml
- name: Create partition
  win_dsc:
    resource_name: Disk
    DriveLetter: "{{ drive_letter }}"
    DiskId: "{{ number }}"
    Size:
    FSLabel: "{{ label }}"
    FSFormat: "{{ fs_type }}"
    AllocationUnitSize: "{{ cluster_size }}"
  when: drive_letter != 'C'
```

```
FAILED! => {"changed": false, "module_version": "4.7.0.0", "msg": "Failed to serialize properties into CimInstance.", "reboot_required": false}
```
