### ISSUE TITLE
When connecting via OpenSSH, additions to the PATH are not detected without a reboot

### ISSUE THREAD

**Issue by shadowink** [ansible-collections/ansible.windows#165]
##### SUMMARY
When connecting to a Windows host via OpenSSH, modules change the PATH, but it is not detected. When software is installed, it cannot be run if it is on the new PATH.

Example 1:  When win_chocolatey is run, if chocolatey is not installed on the system, it installs chocolatey.  However, any modules that try to use chocolatey after fails with "Failed to find Chocolatey installation, make sure choco.exe is in the PATH env value"

Example 2:  win_package is used to install Powershell 7.  Immediately after win_shell is used to run pwsh and fails with "The term 'pwsh' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again."

using win_reboot is required to get the new path to be detected.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

win_chocolatey and win_package

##### ANSIBLE VERSION

```
ansible 2.10.1
  config file = /Users/me/repos/playbooks/ansible.cfg
  configured module search path = ['/Users/me/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/ansible
  executable location = /Library/Frameworks/Python.framework/Versions/3.8/bin/ansible
  python version = 3.8.5 (v3.8.5:580fbb018f, Jul 20 2020, 12:11:27) [Clang 6.0 (clang-600.0.57)]


```

##### CONFIGURATION

```

```

##### OS / ENVIRONMENT

Ansible running on Mac 11.0.1 
Controlling Windows 10 1909 machine with OpenSSH v8.1.0.0p1-Beta
ansible_connection set to ssh and ansible_shell_type set to powershell

##### STEPS TO REPRODUCE

```yaml
---
- hosts: all

  tasks:
    - name: display path at first
      win_shell:  Write-Output $env:PATH
      register: path1

    - name: install chocolatey
      win_chocolatey:
        name: chocolatey
        state: present
    # this adds C:\ProgramData\chocolatey\bin to the path, but it is not shown in the output
    
    - name: display path after chocolatey install
      win_shell:  Write-Output $env:PATH
      register: path2

    - name: Download Powershell Installer
      win_get_url:
        url: "https://github.com/PowerShell/PowerShell/releases/download/v7.1.0/PowerShell-7.1.0-win-x64.msi"
        dest: "c:\\Install\\PowerShell-7.1.0-win-x64.msi"

    - name: Install Powershell
      win_package:
        path: "c:\\Install\\PowerShell-7.1.0-win-x64.msi"
    # this adds c:\Program Files\PowerShell\7\ to the path, but it is not shown in the output

    - name: display path after pwsh install
      win_shell:  Write-Output $env:PATH
      register: path3

    # this fails
    - name: Attempt to use chocolatey
      win_chocolatey_source:
        name: chocolatey
        state: absent
      ignore_errors: true

    # this fails
    - name: attempt to use pwsh
      win_shell: pwsh -Command '$host.version'
      ignore_errors: true

    - name: reboot
      win_reboot:

    - name: display path after reboot
      win_shell:  Write-Output $env:PATH
      register: path4

    # PATH now contains C:\ProgramData\chocolatey\bin and c:\Program Files\PowerShell\7\

    - name: Attempt to use chocolatey
      win_chocolatey_source:
        name: chocolatey
        state: absent
      ignore_errors: true

    - name: attempt to use pwsh
      win_shell:  pwsh -Command '$host.version'
      ignore_errors: true

```

##### EXPECTED RESULTS

after win_chocolatey installs chocolatey, chocolatey should work.

after powershell 7 is installed, pwsh commands should run

##### ACTUAL RESULTS

PATH is updated on the system, but not picked up by current powershell process.

```
https://gist.github.com/shadowink/1485b1eb41daca8f0c3a4d334395809a#file-ansible-out

```
