### ISSUE TITLE
win_acl to have /reset capability of icacls

### ISSUE THREAD

**Issue by jborean93** [ansible-collections/ansible.windows#18]
_From @SagarKodam on Oct 05, 2018 13:09_

##### SUMMARY

win_acl can be used to set ACL to files and folders, but cannot be used to reset the permissions.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

win_acl

##### ADDITIONAL INFORMATION

```yaml
- name: Reset current to default permission for temp folder
  win_acl:
    path: C:\temp
    state: reset
```

_Copied from original issue: ansible/ansible#46540_
