### ISSUE TITLE
win_reboot: pending reboot check

### ISSUE THREAD

**Issue by inorangestylee** [ansible-collections/ansible.windows#182]
##### SUMMARY
Hello,
Is it real to remake functionality of `win_reboot` like `PendingReboot` DSC resource works? Reboot only if reboot is pending, and use `force` key to force reboot 

`PendingReboot` checks:
- reboots triggered by the CCM ConfigMgr client
- reboots triggered by Computer renames
- pending file rename reboots
- reboots triggered by Windows Update
- reboots triggered by the Component-Based Servicing component

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
win_reboot

##### ADDITIONAL INFORMATION

https://docs.microsoft.com/en-us/powershell/scripting/dsc/configurations/reboot-a-node?view=powershell-7.1
https://adamtheautomator.com/pending-reboot-registry-windows/

```yaml
- name: Reboot the machine if it expects but skips hosts rename pending reboot check
  ansible.windows.win_reboot:
    post_reboot_delay: 120
    skip_pending_computer_rename: true
```
```yaml
- name: No checks, just reboot
  ansible.windows.win_reboot:
    post_reboot_delay: 120d
    force: true
```

**Comment by mwtrigg** [comment]
As proposed, this would introduce a serious breaking change and (as it's altering the default behavior) would necessarily require a rewrite everywhere it is used.

Could you modify your request in such a way as to not alter the expected result of a playbook already in use?

- 

My personal thought is that when I call win_reboot, I want and expect the target to reboot; I do not want or expect it to perform additional logic tests.

**Comment by inorangestylee** [comment]
Ok, mb it better looks like this:

```
- name: Reboot the machine if it expects but skips hosts rename pending reboot check
  ansible.windows.win_reboot:
    post_reboot_delay: 120
    if_needed: true
    if_needed_skip:
    - pending_computer_rename
```
new bool parameter `if_needed` (default: false) used for intelligent reboot control
new list parameter `if_needed_skip` used for skip pending reboot requirements. 
`if_needed_skip` list parameters:
```
   cmm_client_sdk
   component_based_servicing
   pending_computer_rename
   pending_file_rename
   windows_update
```

with this, you can keep the old `win_reboot` functionality without rewriting everything where it is used and add new "smart" behavior.
