### ISSUE TITLE
win_updates module doesn't install a update program from SCCM

### ISSUE THREAD

**Issue by sky-joker** [ansible-collections/ansible.windows#194]
##### SUMMARY

I'm not sure this a bug, a update program doesn't install from SCCM(System Center Configuration Manager) with win_updates module.  
The update programs have been displaying on software center in a windows client.  

![image](https://user-images.githubusercontent.com/19516126/110802582-a98fba80-82c1-11eb-84aa-96df1be4ad96.png)

But it doesn't install with win_updates module.

According to the module document the following is written like.

```
managed_server Use a managed server catalog. For environments utilizing Windows Server Update Services (WSUS), Systems Center Configuration Manager (SCCM), or similar corporate update servers, this option selects the defined corporate update source.
```

https://docs.ansible.com/ansible/latest/collections/ansible/windows/win_updates_module.html

As I understand, the update programs can be installed from SCCM by set the server_selection to managed_server.

##### ISSUE TYPE

- Bug Report

##### COMPONENT NAME

win_updates

##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.9.17
```

##### CONFIGURATION

```
$ ansible-config dump --only-changed
```

##### OS / ENVIRONMENT

|      Role      |       Version       |
|----------------|---------------------|
| SCCM Server OS | Windows Server 2019 |
| SCCM           | 1902                |
| SCCM Client OS | Windows Server 2019 |
| Control node   | CentOS 7            |
| Python         | 3.6.8               |

##### STEPS TO REPRODUCE

I created the following playbook and execute it.

```yaml
---
- name: Windows Update Playbook
  hosts: all
  gather_facts: false
  tasks:
    - name: Apply update programs
      win_updates:
        category_names:
          - CriticalUpdates
          - SecurityUpdates
          - Updates
        server_selection: managed_server
        state: installed
      register: result

    - debug: var=result
```

##### EXPECTED RESULTS

The update programs are installed that showed on software center.

##### ACTUAL RESULTS

The changed doesn't occur, and not install the update programs.

#### OTHER INFO

I executed the following command via Powershell, but anything update programs don't display.

```
$session = New-Object -ComObject Microsoft.Update.Session
$searcher = $session.CreateUpdateSearcher()
$searcher.serverselection = 1
$searcher.Search("IsAssigned=1").Updates
```

Is this a bug of the module?

**Comment by jborean93** [comment]
The module just calls the same PowerShell script that you ran. The updates found is entirely up to the the Windows Update Agent and what it reports. If it doesn't report an update isn't available then we can't do anything about that. Do you see the updates when you go to update the host manually though the Windows Update UI. If you do then maybe we need some more config settings in the module but if it isn't there then you can't expect this module to work.

**Comment by sky-joker** [comment]
Thank you @jborean93 for the response.

>  Do you see the updates when you go to update the host manually though the Windows Update UI.

Yes.  
I could be confirmed some programs.

```
Start -> Settings -> Windows Update
```

But more program displayed than I approved in SCCM.  
Most likely, the programs are installed via Internet, not SCCM.

I wonder that Microsoft.Update.Session doesn't support a wrap for SCCM and Software Center🤔

**Comment by jborean93** [comment]
Have you tried setting `ServerSelection = 0` to use the default settings and seeing if the COM API returns the updates? Just as an FYI the `win_updates` module uses the search filter `IsInstalled = 0` rather than `IsAssigned = 1`.

**Comment by sky-joker** [comment]
> Have you tried setting ServerSelection = 0 to use the default settings and seeing if the COM API returns the updates?

Thank you for the advice.  
I tried with the following playbook.

```yaml
---
- name: Windows Update Playbook
  hosts: all
  gather_facts: false
  tasks:
    - name: Apply update programs
      win_updates:
        category_names:
          - CriticalUpdates
          - SecurityUpdates
          - Updates
        server_selection: default
        state: installed
      register: result

    - debug: var=result
```

**Result**

```
$ ansible-playbook main.yml -i inventory.yml

PLAY [Windows Update Playbook] **************************************************************************************************************************************************************

TASK [Apply update programs] ****************************************************************************************************************************************************************
ok: [192.168.10.51]

TASK [debug] ********************************************************************************************************************************************************************************
ok: [192.168.10.51] => {
    "result": {
        "changed": false,
        "failed": false,
        "filtered_updates": {},
        "found_update_count": 0,
        "installed_update_count": 0,
        "reboot_required": false,
        "updates": {}
    }
}

PLAY RECAP **********************************************************************************************************************************************************************************
192.168.10.51              : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

Unfortunately, the result was same.
