### ISSUE TITLE
win_dsc cannot run composite resources

### ISSUE THREAD

**Issue by jamski68** [ansible-collections/ansible.windows#227]
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
win_dsc

##### ANSIBLE VERSION

```
ansible [core 2.11.1] 
  config file = /home/user/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/src/venv/lib64/python3.9/site-packages/ansible
  ansible collection location = /home/user/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/user/src/venv/bin/ansible
  python version = 3.9.2 (default, Mar  5 2021, 01:49:45) [GCC 8.4.1 20200928 (Red Hat 8.4.1-1)]
  jinja version = 3.0.1
  libyaml = True

```

##### CONFIGURATION

```

```

##### OS / ENVIRONMENT

Target Windows Server 2016 or 2019

##### STEPS TO REPRODUCE

```
    - name: Install PowerStig Ps module
      win_psmodule:
        name: PowerStig
        state: present
        allow_clobber: true

    - name: Apply STIG 
      community.windows.win_dsc:
        resource_name: WindowsServer
        OsVersion: "2016"
        OsRole: "MS"
        PsDscRunAsCredential_username: "{{ ansible_user | d(omit) }}"
        PsDscRunAsCredential_password: "{{ ansible_password | d(omit) }}"
```

##### EXPECTED RESULTS
win_dsc should run the DSC configuration

##### ACTUAL RESULTS

```
TASK [Apply STIG] ******************************************************************************************************************************************************************************
task path: /home/user/src/prepare.yml:22
Using module file /home/user/.ansible/collections/ansible_collections/ansible/windows/plugins/modules/win_dsc.ps1
Pipelining is enabled.
<db-01> ESTABLISH WINRM CONNECTION FOR USER: INTERNAL\vagrant on PORT 5985 TO db-01
EXEC (via pipeline wrapper)
The full traceback is:
Not found 
At line:50 char:17
+ ... $resource = Get-CimClass -ClassName $ClassName -Namespace root\Micros ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (root\Microsoft\...n:WindowsServer:String) [Get-CimClass], CimException
    + FullyQualifiedErrorId : HRESULT 0x80041002,Microsoft.Management.Infrastructure.CimCmdlets.GetCimClassCommand

ScriptStackTrace:
at Get-DscCimClassProperties, <No file>: line 50
at Get-OptionSpec, <No file>: line 150
at <ScriptBlock>, <No file>: line 424

Microsoft.Management.Infrastructure.CimException: Not found 
   at Microsoft.Management.Infrastructure.Internal.Operations.CimAsyncObserverProxyBase`1.ProcessNativeCallback(OperationCallbackProcessingContext callbackProcessingContext, T currentItem, Boolean moreResults, MiResult operationResult, String errorMessage, InstanceHandle errorDetailsHandle)
fatal: [db-01]: FAILED! => {
    "changed": false,
    "msg": "Unhandled exception while executing module: Not found "
}


```
However if I run `Get-DscResoure -Name WindowServer` I can see that the resource is there

```
PS C:\Users\vagrant.INTERNAL> Get-DscResource -Name WindowsServer

ImplementedAs   Name                      ModuleName                     Version    Properties                                        
-------------   ----                      ----------                     -------    ----------                                        
Composite       WindowsServer             PowerSTIG                      4.8.0      {DependsOn, PsDscRunAsCredential, OsVersion, Os...
```
