### ISSUE TITLE
win_dsc - Selectively disable parsing string with commas into list/array?

### ISSUE THREAD

**Issue by rayterrill** [ansible-collections/ansible.windows#228]
##### SUMMARY
String value with commas appears to be parsed as an array - is there a way to selectively disable this?

##### ISSUE TYPE
- Bug Report/Question

##### COMPONENT NAME
win_dsc

##### ANSIBLE VERSION

```paste below
ansible 2.9.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/popnimda/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.9 (default, Jan 26 2021, 15:33:00) [GCC 8.4.0]
```

##### CONFIGURATION

```paste below
      win_dsc:
        resource_name: DhcpScopeOptionValue
        ScopeId: 10.81.21.1
        OptionId: 242
        Value: "MCIPADD=10.10.10.10,HTTPSRVR=phoneconfig5,MCPORT=1719,L2QSIG=3,L2QAUD=5"
        AddressFamily: "IPv4"
        VendorClass: "" #empty intentionally - required
        UserClass: "" #empty intentionally - required
```

##### STEPS TO REPRODUCE

```yaml

```

##### EXPECTED RESULTS

Some way to disable parsing comma-separated strings into arrays/lists

##### ACTUAL RESULTS

```paste below
Failed to invoke DSC Set method: Parameters for option value to be set for option ID 242 do not match with option definition on DHCP server DHCP1.
```

**Comment by jborean93** [comment]
This only occurs when the DSC definition states the option is an array of values, in this case `Value` in [DhcpScopeOptionValue](https://github.com/dsccommunity/xDhcpServer/blob/master/source/DSCResources/MSFT_DhcpScopeOptionValue/MSFT_DhcpScopeOptionValue.schema.mof#L6) is a `String[]`. The typical behaviour in Ansible for dealing with a list of strings is to use `,` as a delimiter if the module receives just a string. In this case you want to explicitly set the `Value` as a list to avoid the module from splitting it, i.e.

```yaml
      win_dsc:
        resource_name: DhcpScopeOptionValue
        ScopeId: 10.81.21.1
        OptionId: 242
        Value:
        - MCIPADD=10.10.10.10,HTTPSRVR=phoneconfig5,MCPORT=1719,L2QSIG=3,L2QAUD=5
        AddressFamily: "IPv4"
        VendorClass: "" #empty intentionally - required
        UserClass: "" #empty intentionally - required
```

This is the expected behaviour and we cannot change how it works without breaking existing playbooks that rely on it and also make it harder to specify a list of values using the `ansible -a` command line syntax.
