### ISSUE TITLE
Periodically receive "Failed to invoke DSC Test method: Cannot invoke the Invoke-DscResource cmdlet. The Consistency Check or Pull cmdlet is in progress and must return before Invoke-DscResource can be invoked. Use -Force option if that is available to cancel the current operation." when running many dsc tasks in a loop

### ISSUE THREAD

**Issue by rayterrill** [ansible-collections/ansible.windows#233]
##### SUMMARY

We're using win_dsc to apply a large number of DHCP reservations (using xDhcpServerReservation). Periodically we receive the error:
```
Failed to invoke DSC Test method: Cannot invoke the Invoke-DscResource cmdlet. The Consistency Check or Pull cmdlet is in progress and must return before Invoke-DscResource can be invoked. Use -Force option if that is available to cancel the current operation.
```

We're using a loop to generate the win_dsc tasks.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

win_dsc

##### ANSIBLE VERSION

```paste below
ansible 2.9.0
  config file = /home/popnimda/Ansible-WinDHCPReservations/ansible.cfg
  configured module search path = ['/home/popnimda/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.9 (default, Jan 26 2021, 15:33:00) [GCC 8.4.0]
```

##### CONFIGURATION

```paste below
DEFAULT_CALLBACK_WHITELIST(/home/popnimda/Ansible-WinDHCPReservations/ansible.cfg) = ['profile_tasks']
DEFAULT_HOST_LIST(/home/popnimda/Ansible-WinDHCPReservations/ansible.cfg) = ['/home/popnimda/Ansible-WinDHCPReservations/production']
HOST_KEY_CHECKING(/home/popnimda/Ansible-WinDHCPReservations/ansible.cfg) = False
INTERPRETER_PYTHON(/home/popnimda/Ansible-WinDHCPReservations/ansible.cfg) = /usr/bin/python3
RETRY_FILES_ENABLED(/home/popnimda/Ansible-WinDHCPReservations/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Server 2016

##### STEPS TO REPRODUCE

```yaml
---
- name: Populate Reservations Vars
  include_vars:
    name: reservations
    dir: ../reservations/
    files_matching: "{{ file }}"
- name: Reservations
  win_dsc:
    resource_name: xDhcpServerReservation
    ScopeID: "{{ item.0.key }}"
    IPAddress: "{{ item.1.IPAddress }}"
    ClientMACAddress: "{{ item.1.ClientMACAddress }}"
    Name: "{{ item.1.Name }}"
    AddressFamily: IPv4
    Ensure: "{{ item.1.Ensure }}"
  loop: "{{ reservations | dict2items | subelements('value') }}" #convert reservations to list and loop over the value elements
  loop_control:
    label: "{{ item.0.key }} - {{ item.1.IPAddress }}" #override the label/name for the loop
```

##### EXPECTED RESULTS

Should successfully process all results.

##### ACTUAL RESULTS

```paste below
{"ClientMACAddress": "b8a44f083425", "Ensure": "Present", "IPAddress": "10.79.85.27", "Name": "axis-b8a44f083425"}], "module_version": "3.0.0", "msg": "Failed to invoke DSC Test method: Cannot invoke the Invoke-DscResource cmdlet. The Consistency Check or Pull cmdlet is in progress and must return before Invoke-DscResource can be invoked. Use -Force option if that is available to cancel the current operation.", "reboot_required": false}
```
