### ISSUE TITLE
win_user: Add support for check mode

### ISSUE THREAD

**Issue by jborean93** [ansible-collections/ansible.windows#24]
_From @chopraaa on Mar 13, 2019 09:13_

##### SUMMARY
I feel it's important to add support for check mode to `win_user`. In my case, it would make sure the user doesn't exist already with the required groups, or only reset password if it exists and not create a new account and stuff like this.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
win_user

##### ADDITIONAL INFORMATION
```yaml
    - name: "Check if requested user already exists"
      win_user:
        name: "{{ rdp_user }}"
        groups: "{{ rdp_groups }}"
      register: win_user_query_result
      check_mode: True

    - name: "Create a new user called {{ rdp_user }}"
      win_user:
        name: "{{ rdp_user }}"
        password: "{{ rdp_password }}"
        state: present
        groups: "{{ rdp_groups }}"
      when: win_user_query_result is not changed
      register: win_user_result
```

_Copied from original issue: ansible/ansible#53737_
