### ISSUE TITLE
win_powershell: script: filename.ps1

### ISSUE THREAD

**Issue by GP1cdenney** [ansible-collections/ansible.windows#245]
##### SUMMARY

I would like to pass a file on the ansible control node to win_powershell's script: parameter.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

win_powershell

##### ADDITIONAL INFORMATION

With the ansible.builtin.script module, we can provide a script file to execute on a target and specify the executable and additional arguments to use. Making a script Idempotent, and telling Ansible if changes occured or not, can be difficult though.

With ansible.windows.win_powershell, one of the new features you introduced was the $Ansible object that we can set the changed and failed statuses on, however, you cannot pass a file to the script parameter of win_powershell like you can with the builtin script module. I find it very difficult to read powershell in a yaml syntax/highlighted file in vscode, and having to transpose powershell code from a ps1 file into yaml can be very tedious if you need to troubleshoot.

Right now, win_powershell is pretty great for small code executions and easy enough to work with, but it would definitely be much nicer to work with if ps1 files could be passed to the module instead of raw yaml code (this would especially lend itself well to roles and collections)

```yaml
- ansible.windows.win_powershell:
    script: foobar.ps1
    executable: pwsh.exe
    arguments:
    - -ExecutionPolicy
    - ByPass
 
```

**Comment by jborean93** [comment]
This can be done today by using the [file lookup](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/file_lookup.html)

```yaml
- ansible.windows.win_powershell:
    script: '{{ lookup("file", "foobar.ps1") }}'
    executable: pwsh.exe
    arguments:
    - -ExecutionPolicy
    - ByPass
```

Except for `win_powershell` being able to run it in `pwsh.exe` I cannot think of any other scenarios where this might be beneficialcial over using the controller based file as a module. The latter has a few more benefits such as:

* Simpler, no need to mess with runspaces and serializing output
* Access to existing, and custom, module utils that can be shipped with Ansible
* Better documentation standards and tools are available for modules
* Can be callable by name outside the role/collection, `win_powershell` will still need be called with the proper options to replicate the same behaviour
