### ISSUE TITLE
win_file directory creation broken

### ISSUE THREAD

**Issue by agowa338** [ansible-collections/ansible.windows#246]
##### SUMMARY
win_file directory doesn't create a new empty directory.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
win_file

##### ANSIBLE VERSION

```paste below
ansible 2.10.11
  config file = ./ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = ./venv/lib/python3.9/site-packages/ansible
  executable location = ./venv/bin/ansible
  python version = 3.9.6 (default, Jun 30 2021, 10:22:16) [GCC 11.1.0]
```

##### COLLECTION VERSION

```paste below
1.7.0
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

Case 1:
```yaml
- name: Create foo
          ansible.windows.win_file:
            path: "C:\foo"
            state: directory
```

Case 2:
```yaml
- name: Create foo\bar
          ansible.windows.win_file:
            path: "C:\foo\bar"
            state: directory
```

##### EXPECTED RESULTS

Case 1:
Folder foo being created

Case 2:
Folder foo\bar being created

##### ACTUAL RESULTS

Case 1:
Ansible reports `ok` as well as `"changed": false`. But the folder doesn't exist

Case 2:
Ansible fails with this error:
```
fatal: [test]: FAILED! => {"changed": false, "msg": "Get-AnsibleParam: Parameter 'path' has an invalid path 'C:\foo\bar' specified."}
```

**Comment by jborean93** [comment]
This because you have used double quoted with backslashes. This changes the what you would expect the literal value to it's actual value `\f` [form feed](https://theasciicode.com.ar/ascii-control-characters/form-feed-female-symbol-venus-ascii-code-12.html) and `\b` [backspace](https://theasciicode.com.ar/ascii-control-characters/backspace-ascii-code-8.html).

For the first case I'm not 100% sure why Windows didn't fail that the path is invalid but potentially because it's just after the root it's just ignoring the value? The 2nd example is failing as expected because `\b` is also not a valid path character.

You have 3 options to solve this problem:

```yaml
# Don't quote the value at a
path: C:\foo\bar

# Use single quotes
path: 'C:\foo\bar'

# Use double quotes and escape \
path: "C:\\foo\\bar"
```

We do have some docs around this https://docs.ansible.com/ansible/latest/user_guide/windows_usage.html#path-formatting-for-windows for more information.
