### ISSUE TITLE
KB5004244 appears to have broken win_reboot on Server 2019

### ISSUE THREAD

**Issue by dpower1985** [ansible-collections/ansible.windows#249]
##### SUMMARY

I first noticed this issue with the Out of bound patch Microsoft released last week for the Print Nightmare vulnerability, but it also appears to be happening with the update released yesterday for Server 2019 which replaced it, KB5004244. Once this update is installed the win_reboot module will successfully trigger a reboot but then never detect the system has come back up again. I've verified WinRM is running and reachable but Ansible doesn't detect it automatically. 
Oddly enough if I manually reboot the machine a second time then once it comes back up Ansible detects this and reconnects, but the next time the system is rebooted by the win_reboot module it fails to detect the server coming back up. It just waits for my reboot_timeout to expire and then fails the task.

I'm seeing this issue when building new machines and installing Windows Updates. If I explicitly exclude KB5004244 however then everything works fine and every win_reboot call works as expected.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ansible.windows.win_reboot

##### ANSIBLE VERSION

```paste below
ansible [core 2.11.2]
  config file = /build/templates/ansible.cfg
  configured module search path = ['/build/templates/playbooks/modules', '/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.6 (default, Jul  1 2021, 07:39:48) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
  jinja version = 3.0.1
  libyaml = True
```

##### COLLECTION VERSION

```paste below
# /usr/local/lib/python3.9/site-packages/ansible_collections
Collection      Version
--------------- -------
ansible.windows 1.7.0
```

##### CONFIGURATION

```paste below
DEFAULT_CONNECTION_PLUGIN_PATH(/build/templates/ansible.cfg) = ['/build/templates/connection_plugins']
DEFAULT_MODULE_PATH(/build/templates/ansible.cfg) = ['/build/templates/playbooks/modules', '/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
DEFAULT_ROLES_PATH(/build/templates/ansible.cfg) = ['/build/templates/roles']
DEPRECATION_WARNINGS(/build/templates/ansible.cfg) = False
SYSTEM_WARNINGS(/build/templates/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Target OS - Windows Server 2019

##### STEPS TO REPRODUCE

```yaml
- name: Second update run
  ansible.legacy.win_shell: |
    Import-Module C:\PSWindowsUpdate\PSWindowsUpdate.psd1 -Force -ErrorAction Stop
    Get-WUInstall -NotCategory "Drivers" -Install -AcceptAll -IgnoreReboot -Verbose | Select-Object Result, KB, Size, Title | Format-Table -Autosize | Out-File C:\Windows\Temp\UpdateLog2.log
  vars:
    ansible_become: yes
    ansible_become_method: runas
    ansible_become_user: packer
  tags: 
    - windows_all

- name: Second update reboot
  ansible.windows.win_reboot:
    reboot_timeout: 3600
  tags: 
    - windows_all
```

##### EXPECTED RESULTS

TASK [windows_update_powershell : Second update run] ***************************[0m
changed: [default][0m
TASK [windows_update_powershell : Second update reboot] *************************
changed: [default]

##### ACTUAL RESULTS

```paste below
TASK [windows_update_powershell : Second update run] ***************************[0m
changed: [default][0m
TASK [windows_update_powershell : Second update run reboot] ********************[0m
fatal: [default]: FAILED! => {"changed": false, "elapsed": 3612, "msg": "Timed out waiting for last boot time check (timeout=3600)", "rebooted": true}[0m
```
