### ISSUE TITLE
win_group - `description` option causes module failure in check mode when the group doesn't exist yet

### ISSUE THREAD

**Issue by briantist** [ansible-collections/ansible.windows#258]
##### SUMMARY

When running `win_group` in check mode with the `description` option, the module will fail.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

win_group.ps1

##### ANSIBLE VERSION

```paste below
ansible 2.9 with ansible.windows 1.7.0
```

##### COLLECTION VERSION

```paste below
1.7.0
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Windows 2016

##### STEPS TO REPRODUCE

Run in check mode:
```yaml
- name: "Create Local Group"
  ansible.windows.win_group:
    name: test
    description: test
    state: present
```

##### EXPECTED RESULTS

check mode returns proper status

##### ACTUAL RESULTS

```paste below
The property 'description' cannot be found on this object. Verify that the property exists and can be set.
```
