### ISSUE TITLE
win_copy fails with using become to switch to a non-admin user

### ISSUE THREAD

**Issue by lheimbs** [ansible-collections/ansible.windows#271]
##### SUMMARY
While trying to copy a file to a managed node and becoming a lower-priviliged (non-admin) user with `become` win_copy fails to copy the file and displays a _System.UnauthorizedAccessException: Access is denied ---> System.ComponentModel.Win32Exception: Access is denied_ error while copying the file in question into a temp directory of the original Administrator user.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
win_copy

##### ANSIBLE VERSION

```paste below
ansible [core 2.11.4] 
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/lenny/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /home/lenny/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.9.6 (default, Jun 30 2021, 10:22:16) [GCC 11.1.0]
  jinja version = 3.0.1
  libyaml = True
```

##### COLLECTION VERSION

```paste below

```

##### CONFIGURATION

```paste below
<empty>
```

##### OS / ENVIRONMENT

target OS: Windows Server 2019 Desktop

##### STEPS TO REPRODUCE

```yaml
---
- name: Test win_copy as underprivileged user
  hosts: windows
  remote_user: Administrator

  tasks:
    - name: Create a underprivileged user
      win_user:
        name: testuser
        password: testpassword_123
        state: present
    - name: Allow user to login through become
      win_user_right:
        name: SeBatchLogonRight
        users:
        - 'testuser'
        action: add
    - name: Try to copy a file as the new user
      win_copy:
        src: testfile
        dest: C:\Users\Public\testfile
      become: yes
      become_user: testuser
      become_method: runas
```

##### EXPECTED RESULTS

The File is expected to get copied to the target machine

##### ACTUAL RESULTS

The task fails because the new user does not have access rights to the temp folder ansible uses, since the temp folder belongs to the Admin user:
testuser does not have permissions to access `c:\users\administrator\appdata\temp...`

```paste below
redirecting (type: action) ansible.builtin.win_copy to ansible.windows.win_copy
redirecting (type: action) ansible.builtin.win_copy to ansible.windows.win_copy
Using module file /usr/lib/python3.9/site-packages/ansible_collections/ansible/windows/plugins/modules/win_copy.ps1
Pipelining is enabled.
<192.168.1.100> ESTABLISH WINRM CONNECTION FOR USER: Administrator on PORT 5986 TO 192.168.1.100
EXEC (via pipeline wrapper)
EXEC (via pipeline wrapper)
<192.168.1.100> PUT "/home/lheimbs/projects/testfile" TO "C:\Users\Administrator\AppData\Local\Temp\ansible-tmp-1631003932.203487-470989-237865370674475\source"
Using module file /usr/lib/python3.9/site-packages/ansible_collections/ansible/windows/plugins/modules/win_copy.ps1
Pipelining is enabled.
EXEC (via pipeline wrapper)
EXEC (via pipeline wrapper)
The full traceback is:
Access is denied
At line:378 char:15
+     if (-not (Test-Path -LiteralPath $src -PathType Leaf)) {
+               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (C:\Users\Admini...70674475\source:String) [Test-Path], UnauthorizedAccessException
    + FullyQualifiedErrorId : ItemExistsUnauthorizedAccessError,Microsoft.PowerShell.Commands.TestPathCommand

ScriptStackTrace:
at <ScriptBlock>, <No file>: line 378

System.UnauthorizedAccessException: Access is denied ---> System.ComponentModel.Win32Exception: Access is denied
   --- End of inner exception stack trace ---
   at Microsoft.PowerShell.Commands.FileSystemProvider.ItemExists(String path, ErrorRecord& error)
fatal: [192.168.1.100]: FAILED! => {
    "changed": true,
    "checksum": "da39a3ee5e6b4b0d3255bfef95601890afd80709",
    "dest": "C:\\Users\\Public\\testfile",
    "msg": "failed to copy file /home/lheimbs/projects/testfile: Unhandled exception while executing module: Access is denied",
    "operation": "file_copy",
    "original_basename": "testfile",
    "size": 0,
    "src": "testfile"
}
```

A workaround is setting `ansible_remote_tmp` to a directory like all users have access to but this seems more like a hack than desired behavior...
