### ISSUE TITLE
win_feature: Reporting "NoChangeNeeded" and reboot_required: true

### ISSUE THREAD

**Issue by gone-for-coding** [ansible-collections/ansible.windows#287]
##### SUMMARY
win_feature: Reporting "NoChangeNeeded" and reboot_required: true resulting in an unwanted reboot when only checking for reboot_required.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
win_feature

##### ANSIBLE VERSION

```paste below
ansible-playbook [core 2.11.4]
  config file = /code/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.8.12 (default, Sep 28 2021, 19:14:48) [GCC 10.2.1 20210110]
  jinja version = 3.0.1
  libyaml = True
```

##### COLLECTION VERSION

```paste below
ansible.windows "1.7.2"
```

##### CONFIGURATION

```paste below
CALLBACKS_ENABLED(/code/ansible.cfg) = ['ansible.builtin.junit']
DEFAULT_FORKS(/code/ansible.cfg) = 25
DEFAULT_STDOUT_CALLBACK(/code/ansible.cfg) = default
SHOW_CUSTOM_STATS(/code/ansible.cfg) = True
```

##### OS / ENVIRONMENT
Windows Server 2016

##### STEPS TO REPRODUCE

Run playbook with features already installed.
Exact cause it yet unkown but possibly pending reboots after installing windows updates.

```yaml
- name: Install RDS Features
  ansible.windows.win_feature:
    name:
      - Remote-Desktop-Services
      - RDS-RD-Server
      - RSAT-RDS-Tools
      - RSAT-RDS-Licensing-Diagnosis-UI
    state: present
  register: win_result

- name: Reboot if installing RDS features requires it
  ansible.windows.win_reboot:
  when: win_result.reboot_required
```

##### EXPECTED RESULTS

reboot_required should only be true when win_feature actually changes something. Otherwise the reboot might be a result of some other activities on the system.

##### ACTUAL RESULTS

Below output results in an unwanted reboot as a reboot is required but not caused by any changes of win_feature.

```paste below
ok: [hostname] => {"changed": false, "exitcode": "NoChangeNeeded", "feature_result": [], "reboot_required": true, "success": true}
```
