### ISSUE TITLE
setup: Windows gathering facts should honor gather_timeout

### ISSUE THREAD

**Issue by ronansalmon** [ansible-collections/ansible.windows#31]
##### SUMMARY
Windows facts should honor gather_timeout

playbook:
```
- hosts: windows
  gather_facts: false
  roles:
    - gather_fact
```
role: gather_fact
```
- name: Getting hosts infos
  setup:
    gather_timeout: 3
```

gather_timeout is ignored. Setup module never gives up after 3 seconds on windows machines.

##### COMPONENT NAME
setup
