### ISSUE TITLE
`win_find` Takes abnormally long time to complete.

### ISSUE THREAD

**Issue by areed1192** [ansible-collections/ansible.windows#318]
##### SUMMARY

I've noticed with the `win_find` module that it will take an abnormally long time to grab all the files from a directory. I have a folder that only has three files in it, but the module has taken over 15 mins to run and is still not finished. The only thing I'll say is the files are large in nature (over twenty GBs) but there are only three of them and I'm not doing any copy operation just trying to get file information like the path, name, and creation time.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

Module Name: `win_find`

##### ANSIBLE VERSION

```paste below
ansible [core 2.11.4] 
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/Users/""/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/4.5.0/libexec/lib/python3.9/site-packages/ansible
  ansible collection location = /Users/""/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.7 (default, Sep  3 2021, 12:37:55) [Clang 12.0.5 (clang-1205.0.22.9)]
  jinja version = 3.0.1
  libyaml = True
```

##### COLLECTION VERSION

```paste below
# /Users/alexreed/.ansible/collections/ansible_collections
Collection      Version
--------------- -------
ansible.windows 1.8.0  
```

##### OS / ENVIRONMENT

Operating System: MacOS Monterey 12.0.1
Processor: 2.6 GHz 6-Core Intel Core i7
Memory: 16 GB 2667 MHz DDR4

##### STEPS TO REPRODUCE

```yaml
- name: Find files in path
  ansible.windows.win_find:
    paths: D:\shares\GP_BKUPS\MR01
  register: gp_files

- name: Print the found files.
  ansible.builtin.debug:
    msg: "{{ gp_files }}"
```
