### ISSUE TITLE
Ansible win_dsc fails to install SqlServer with SqlServerDsc

### ISSUE THREAD

**Issue by zmaktouf** [ansible-collections/ansible.windows#32]
##### SUMMARY

I am trying to install SQLServer 2019 on Windows Server 2019 using ansible and SqlServerDsc I am getting am error about missing CimClass MSFT_SqlSetup. 

```
The full traceback is:
Not found 
At line:50 char:17
+ ... $resource = Get-CimClass -ClassName $ClassName -Namespace root\Micros ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (root\Microsoft\...n:MSFT_SqlSetup:String) [Get-CimClass], CimException
    + FullyQualifiedErrorId : HRESULT 0x80041002,Microsoft.Management.Infrastructure.CimCmdlets.GetCimClassCommand

ScriptStackTrace:
at Get-DscCimClassProperties, <No file>: line 50
at Get-OptionSpec, <No file>: line 150
at <ScriptBlock>, <No file>: line 376

Microsoft.Management.Infrastructure.CimException: Not found 
   at Microsoft.Management.Infrastructure.Internal.Operations.CimAsyncObserverProxyBase`1.ProcessNativeCallback(OperationCallbackProcessingContext callbackProcessingContext, T currentItem, Boolean moreResults, MiResult operationResult, String errorMessage, InstanceHandle errorDetailsHandle)
fatal: [192.168.56.5]: FAILED! => {
    "changed": false,
    "msg": "Unhandled exception while executing module: Not found "
}
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

win_dsc

##### ANSIBLE VERSION

```paste below
$ ansible --version
ansible 2.9.6
  config file = None
  configured module search path = ['/home/<username>/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/<username>/<myproject>/ve/lib/python3.6/site-packages/ansible
  executable location = /home/<username>/<myproject>/ve/bin/ansible
  python version = 3.6.9 (default, Nov  7 2019, 10:44:02) [GCC 8.3.0]

```

##### CONFIGURATION

```paste below
ansible-config dump --only-changed
=> Empty
```

##### OS / ENVIRONMENT

Ansible control machine: Ubuntu 1804
Target Machine: Windows Server 2019

##### STEPS TO REPRODUCE

```yaml
- name: Windows | Install .NET Framework 4.5 Core
  win_feature:
    name: NET-Framework-45-Core
    state: present
    include_sub_features: True

- name: Windows | Install DSC resource (SqlServerDsc)
  win_psmodule:
    name: SQLServerDsc
    state: present

- name: Windows | Create directory structure
  win_file:
    path: C:\mssql_2019_setup
    state: directory

- name: Windows | Fetch SQL Media Downloader
  win_get_url:
    url: https://download.microsoft.com/download/8/8/8/888b0a29-8ead-4a4c-89c2-34ec753b73e8/SQL2019-SSEI-Eval.exe
    dest: C:\mssql_2019_setup\sql2019-setup.exe
    force: no

- name: Windows | Download install media
  win_command: C:\mssql_2019_setup\sql2019-setup.exe /ENU /Action=Download /HideProgressBar /MediaPath=C:\mssql_2019_setup\media /MediaType=ISO  /Quiet
  args:
    creates: C:\mssql_2019_setup\media

- name: Windows | Find ISO in downloaded media
  win_find:
    paths: C:\mssql_2019_setup\media
    patterns: '*.iso'
    file_type: file
  register: iso_find

- name: Windows | Mount ISO image of SQL Server
  win_disk_image:
    image_path: '{{ iso_find.files[0].path }}'
    state: present
  register: mount_info
  changed_when: false

- name: Windows | Install SQL Server
  win_dsc:
    resource_name: SqlSetup
    Action: Install
    InstanceName: '{{ mssql_instance_name }}'
    SourcePath: '{{ mount_info.mount_paths[0] }}'
    Features: SQLENGINE
    ProductKey: '{{ mssql_pid | d(omit)}}'
    UpdateEnabled: False
    InstallSharedDir: C:\Program Files\Microsoft SQL Server
    InstallSharedwowDir: C:\Program Files (x86)\Microsoft SQL Server
    InstanceDir: C:\Program Files\Microsoft SQL Server
    SQLCollation: French_CI_AS
    SQLSysAdminAccounts: BUILTIN\Administrators
    SecurityMode: SQL
    SAPwd_username: sa
    SAPwd_password: '{{ mssql_sa_password }}'
    SQLUserDBDir: C:\MSSQL\Data
    SQLUserDBLogDir: C:\MSSQL\DataLogs
    SQLTempDBDir: C:\MSSQL\TempDB
    SQLTempDBLogDir: C:\MSSQL\TempDBLogs
    SQLBackupDir: C:\MSSQL\Backup
    SqlSvcStartupType: Automatic
    AgtSvcStartupType: Manual
    AsSvcStartupType: Manual
    BrowserSvcStartupType: Manual
    PsDscRunAsCredential_username: '{{ ansible_user | d(omit) }}'
    PsDscRunAsCredential_password: '{{ ansible_password | d(omit)}}'
```

##### EXPECTED RESULTS

No error

##### ACTUAL RESULTS

```paste below
The full traceback is:
Not found 
At line:50 char:17
+ ... $resource = Get-CimClass -ClassName $ClassName -Namespace root\Micros ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (root\Microsoft\...n:MSFT_SqlSetup:String) [Get-CimClass], CimException
    + FullyQualifiedErrorId : HRESULT 0x80041002,Microsoft.Management.Infrastructure.CimCmdlets.GetCimClassCommand

ScriptStackTrace:
at Get-DscCimClassProperties, <No file>: line 50
at Get-OptionSpec, <No file>: line 150
at <ScriptBlock>, <No file>: line 376

Microsoft.Management.Infrastructure.CimException: Not found 
   at Microsoft.Management.Infrastructure.Internal.Operations.CimAsyncObserverProxyBase`1.ProcessNativeCallback(OperationCallbackProcessingContext callbackProcessingContext, T currentItem, Boolean moreResults, MiResult operationResult, String errorMessage, InstanceHandle errorDetailsHandle)
fatal: [192.168.56.5]: FAILED! => {
    "changed": false,
    "msg": "Unhandled exception while executing module: Not found "
}

```

**Comment by jborean93** [comment]
I'll have to debug this a bit further to try and figure out why this is happening. Has this ever worked for you in the past?

**Comment by zmaktouf** [comment]
I wasn't able to run any DSC, even simple ones

```yaml
- hosts: dbservers
  gather_facts: yes
  tasks:
    - name: create file with some text
      win_dsc:
        resource_name: File
        DestinationPath: C:\temp\file
        Contents: |
            Hello
            World
        Ensure: Present
        Type: File
```

I think I found the issue, I am using HTTPS winrm listener. 
If I switch to HTTP winrm listener, it works.
Is this a known issue?

Thanks
