### ISSUE TITLE
win_service_info filter by username

### ISSUE THREAD

**Issue by lucab85** [ansible-collections/ansible.windows#330]
##### SUMMARY
Add to  `win_service_info` module the filter by username feature

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
ansible.windows.win_service_info

##### ADDITIONAL INFORMATION

The following PowerShell WMI code might be useful to filter by username:
`Get-WmiObject -Class Win32_Service | Where-Object {$_.StartName -eq '{{ username }}'}`

**Comment by Akasurde** [comment]
@lucab85 This can be achieved using `selectattr` - 

```yaml
    - ansible.windows.win_service_info:
      register: r

    - debug:
        msg: "{{ item.display_name }}"
      loop: "{{ r.services | selectattr('username', 'search', 'NetworkService*') | list }}"
      loop_control:
        label: "{{ item.display_name }}"
```

will result in - 

```console
...
ok: [windows_host] => (item=Microsoft Cloud Identity Service) => {
    "msg": "Microsoft Cloud Identity Service"
}
ok: [windows_host] => (item=Cryptographic Services) => {
    "msg": "Cryptographic Services"
}
ok: [windows_host] => (item=DNS Client) => {
    "msg": "DNS Client"
}
...
```
