### ISSUE TITLE
win_service and win_service_info returning different states for a running service (running / started)

### ISSUE THREAD

**Issue by cairo-koch-maximilian** [ansible-collections/ansible.windows#338]
##### SUMMARY
The module win_service returns for the state key of an running windows service running, while win_service_info return started. This is really annoying an makes working with both modules together really difficult (practical just use win_service). This is an unexpected behavior because both modules are form the same collection (ansible.windows)

##### ISSUE TYPE
- Bug Report
- unexpected behavior

##### COMPONENT NAME
win_service
win_service_info

##### ANSIBLE VERSION
```
ansible [core 2.12.2]
  config file = /daten/ansible/ansible.cfg
  configured module search path = ['/home/testuser/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/testuser/.local/lib/python3.9/site-packages/ansible
  ansible collection location = /home/testuser/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/testuser/.local/bin/ansible
  python version = 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110]
  jinja version = 3.0.3
  libyaml = True
```

##### COLLECTION VERSION
```
# /home/testuser/.local/lib/python3.9/site-packages/ansible_collections
Collection      Version
--------------- -------
ansible.windows 1.9.0  

# /usr/local/lib/python3.9/dist-packages/ansible_collections
Collection      Version
--------------- -------
ansible.windows 1.9.0  

# /home/testuser/.ansible/collections/ansible_collections
Collection      Version
--------------- -------
ansible.windows 1.9.0 
```

##### CONFIGURATION
```
CALLBACKS_ENABLED(/daten/ansible/ansible.cfg) = ['ansible.posix.profile_tasks']
DEFAULT_HOST_LIST(/daten/ansible/ansible.cfg) = ['/daten/ansible/inventory.yaml']
```

##### OS / ENVIRONMENT
Ansible controller: Debian 11 VM on VirtualBox or / and VMware ESXi 6.7U3
target: unpatched Windows 2016 VM on VirtualBox and / or VMware ESXi 6.7U3

##### STEPS TO REPRODUCE
```yaml
- name: gather information about service spooler (win_service)
  ansible.windows.win_service:
    name: spooler
  register: service_spooler_1

- name: gather information about service spooler (win_service_info)
  ansible.windows.win_service_info:
    name: spooler
  register: service_spooler_2

- name: print return (win_service)
  debug: 
    msg: "{{ service_spooler_1.state }}"

- name: print return (win_service_info)
  debug: 
    msg: "{{ service_spooler_2.services[0].state  }}"
```

##### EXPECTED RESULTS
both modules should return for the state key the same value: e.g. two times running or two times started, which is more ansible like.

##### ACTUAL RESULTS
```
TASK [gather information about service spooler (win_service)] ***************************************************************************
ok: [ws2016-test05]
Wednesday 16 February 2022  11:09:21 +0100 (0:00:02.520)       0:00:06.638 **** 

TASK [gather information about service spooler (win_service_info)] **********************************************************************
ok: [ws2016-test05]
Wednesday 16 February 2022  11:09:23 +0100 (0:00:02.181)       0:00:08.819 **** 

TASK [print return (win_service)] *******************************************************************************************************
ok: [ws2016-test05] => {
    "msg": "running"
}
Wednesday 16 February 2022  11:09:23 +0100 (0:00:00.027)       0:00:08.847 **** 

TASK [print return (win_service_info)] **************************************************************************************************
ok: [ws2016-test05] => {
    "msg": "started"
}
```
