### ISSUE TITLE
win_update reboot on failure

### ISSUE THREAD

**Issue by forum4cc** [ansible-collections/ansible.windows#343]
##### SUMMARY
Sometimes Windows Updates are failing because of multiple reasons. For example with the error code 0x8024a204. In most of the cases, a reboot helps, sometimes you need to clear the update cache aswell. If you loop over the updates with "until:" you can't catch the error with a reboot, so this must be implemented into win_updates directly.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
win_update

##### ADDITIONAL INFORMATION
Add another option, for example "reboot_on_failure: yes/no". If win_update has a failed_update_count >= 1 and reboot_on_failure is set to true, reboot the machine.

Current state, when an update fails, you are left without updates:
```
---
- name: install windows updates and reboot until there are no more updates left
  ignore_errors: yes
  win_updates:
    category_names: '*'
    reboot: yes
    state: installed
  register: win_updates
  until: win_updates.installed_update_count == 0
```

With the feature request the update fails, it reboots the machine and hopefully installs the update within the next retry.
```
---
- name: install windows updates and reboot until there are no more updates left
  ignore_errors: yes
  win_updates:
    category_names: '*'
    reboot: yes
    state: installed
    reboot_on_failure: yes
  register: win_updates
  until: (win_updates.installed_update_count == 0 ) and (win_updates.failed_update_count == 0)
```
There must be a limit to this aswell to not get stuck in a loop if rebooting doesn't help to solve the problem.

A workaround for this might restart the machine before starting the updates, but somehow Windows sometimes needs a failing installation before rebooting helps.
