### ISSUE TITLE
Add ability to set/unset 'Register addresses in DNS` checkbox.

### ISSUE THREAD

**Issue by salderma** [ansible-collections/ansible.windows#347]
##### SUMMARY
Please add feature to allow boolean (checked/unchecked) for _Register this connection's addresses in DNS_ setting.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
ansible.windows.win_dns_client

##### ADDITIONAL INFORMATION
 This would seem to be appropriate for configuring systems with multiple adapters, and quite specifically for Vagrant boxes (and similar) which have a "management" network interface that's generally irrelevant to the system's functional purpose.  This is especially useful with Active Directory DNS servers that might have multiple network adapters, but some should be excluded from having DNS records for the domain.

@rgl has [powershell code](https://github.com/rgl/windows-domain-controller-vagrant/blob/master/provision/domain-controller-configure.ps1#L18) providing a means to accomplish the task, although it is specifically for a Vagrant box.

```yaml
---
hosts: all
vars:
  dc1: 192.168.1.10
  dc2: 192.168.1.11
tasks:
  - name: Remove 1st Adapter from DNS Registrtion
    ansible.windows.win_dns_client:
      adapter_names: 'Ethernet'
      regsiter_dns: false
  - name: Set DNS Servers
    ansible.windows.win_dns_client:
      adapter_names: Ethernet 2'
      register_dns: true
      dns_servers:
        - "{{ dc1 }}"
        - "{{ dc2 }}"
```
