### ISSUE TITLE
Insane slow on deleting files

### ISSUE THREAD

**Issue by it-pappa** [ansible-collections/ansible.windows#355]
##### SUMMARY

It takes 2-4 second to delete files. I have a playbook to delete DAT files which is around 5kb, and it takes 2-4 second to delete each one of them. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

state: absent

##### ANSIBLE VERSION
2.11

```

##### COLLECTION VERSION
<!--- Paste verbatim output from "ansible-galaxy collection list <namespace>.<collection>"  between the quotes
for example: ansible-galaxy collection list community.general
-->
```paste below
latest
```

##### CONFIGURATION

```paste below
none special
```

##### OS / ENVIRONMENT

ubuntu linux
windows server 2019

##### STEPS TO REPRODUCE

```yaml
- name: Delete files
  ansible.windows.win_file:
    path: "{{ item }}"
    state: absent
  loop: "{{ output.files | json_query('[].path') }}"
```

##### EXPECTED RESULTS

Do the job faster

##### ACTUAL RESULTS

very very slow

```paste below

```
