### ISSUE TITLE
win_reboot: failed to get host boot time info

### ISSUE THREAD

**Issue by Akasurde** [ansible-collections/ansible.windows#36]
_From @MaartenMol on Mar 18, 2020 12:29_

##### SUMMARY

Getting the following error: `win_reboot: failed to get host boot time info, rc: 1, stdout: , stderr:`

While running this play on Windows Server 2019

I have seen other reports from before but those are a long time ago and from very old versions of Ansible.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

win_reboot

##### ANSIBLE VERSION

```paste below
2.9.5
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Running the playbook from Ansible AWX on Docker using the official installation steps. No other weird errors when running Playbooks on Windows.

OS to be configured by playbooks: Windows Server 2019 latest updates

Connection method to hosts: 
```
ansible_connection: vmware_tools
ansible_shell_type: powershell
```

##### STEPS TO REPRODUCE

```
---
- name: Deploy an Active Directory
  hosts: domaincontrollers
  gather_facts: yes
  tasks:
    - name: Create new Windows domain in a new forest
      win_domain:
        dns_domain_name: "{{ organization }}"
        safe_mode_password: P@ssword
      register: domain_install
    - name: Reboot when AD feature requires it
      win_reboot:
      when: domain_install.reboot_required
```

##### EXPECTED RESULTS

Reboots when the active directory module requires it.

##### ACTUAL RESULTS

```
{
    "reboot": false,
    "msg": "win_reboot: failed to get host boot time info, rc: 1, stdout: , stderr: ",
    "_ansible_no_log": false,
    "changed": false
}
```

```paste below

```

_Copied from original issue: ansible/ansible#68307_

**Comment by MaartenMol** [comment]
When running a simple reboot all task with win_reboot, same results: (Also on Windows 10)

Playbook:
```
---
- name: Reboot Windows machines
  hosts: all
  gather_facts: yes
  tasks:
    - name: Reboot the machine with all defaults
      when: ansible_facts['os_family'] == "Windows"
      win_reboot:
```

Result:
```
{
    "reboot": false,
    "msg": "win_reboot: failed to get host boot time info, rc: 1, stdout: , stderr: ",
    "_ansible_no_log": false,
    "changed": false
}
```

Running it on a basic CentOS 8 host with Ansbile V2.9.5:

```
ansible-playbook -i inventory_chocoladebol base_reboot.yml -vvvvv
ansible-playbook 2.9.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 3.6.8 (default, Nov 21 2019, 19:31:34) [GCC 8.3.1 20190507 (Red Hat 8.3.1-4)]
Using /etc/ansible/ansible.cfg as config file
setting up inventory plugins
host_list declined parsing /root/base_vm/inventory_chocoladebol as it did not pass its verify_file() method
script declined parsing /root/base_vm/inventory_chocoladebol as it did not pass its verify_file() method
auto declined parsing /root/base_vm/inventory_chocoladebol as it did not pass its verify_file() method
Parsed /root/base_vm/inventory_chocoladebol inventory source with yaml plugin
Loading callback plugin default of type stdout, v2.0 from /usr/lib/python3.6/site-packages/ansible/plugins/callback/default.py

PLAYBOOK: base_reboot.yml ********************************************************************************************************************************************************************************************************************************************************************
Positional arguments: base_reboot.yml
verbosity: 5
connection: smart
timeout: 10
become_method: sudo
tags: ('all',)
inventory: ('/root/base_vm/inventory_chocoladebol',)
forks: 5
1 plays in base_reboot.yml

PLAY [Reboot Windows machines] ***************************************************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************************************************************************************************************************************************************************************
task path: /root/base_vm/base_reboot.yml:2
Using module file /usr/lib/python3.6/site-packages/ansible/modules/windows/setup.ps1
ok: [dc-01]
META: ran handlers

TASK [Reboot the machine with all defaults] **************************************************************************************************************************************************************************************************************************************************
task path: /root/base_vm/base_reboot.yml:6
fatal: [dc-01]: FAILED! => {
    "changed": false,
    "msg": "win_reboot: failed to get host boot time info, rc: 1, stdout: , stderr: ",
    "reboot": false
}

PLAY RECAP ***********************************************************************************************************************************************************************************************************************************************************************************
dc-01                      : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

```

**Comment by MaartenMol** [comment]
This does not seem to be a module issue but a ansible_connection issue. As I am using the same module win_reboot and win_domain both using WinRM in a new test setup they work without issues. When using ansible_connection: psrp with a socks5h proxy in the middle both modules work without issue.

Is this a bug report for the connection plugin vmware_tools?

**Comment by jborean93** [comment]
It sounds like a problem with vmware_tools and how we send the command to be executed. Does it work on this host just through the he winrm connection plugin.

**Comment by MaartenMol** [comment]
> It sounds like a problem with vmware_tools and how we send the command to be executed. Does it work on this host just through the he winrm connection plugin.

It does, the win_domain module does also have an issue when using the vmware_tools plugin. While with WinRM plugin and PSRP plugin they work without any issue.

**Comment by jborean93** [comment]
Ok, this is going to be hard for me to test as I don't have a VMWare host for me to test against. My guess is that because we are running a direct PowerShell cmd https://github.com/ansible-collections/ansible.windows/blob/master/plugins/action/win_reboot.py#L29 against the host for the reboot check it is failing because the shell on the VMWare tools connection plugin is cmd. It's the same for winrm but the actual connection plugin there encodes the script in a powershell command itself so it's not a problem there.

**Comment by MaartenMol** [comment]
> Ok, this is going to be hard for me to test as I don't have a VMWare host for me to test against. My guess is that because we are running a direct PowerShell cmd https://github.com/ansible-collections/ansible.windows/blob/master/plugins/action/win_reboot.py#L29 against the host for the reboot check it is failing because the shell on the VMWare tools connection plugin is cmd. It's the same for winrm but the actual connection plugin there encodes the script in a powershell command itself so it's not a problem there.

Weird because when using VMware Tools as connection plugin, I also let it know that I use Powershell. Example:

```
fs-01:
      vm_template: Windows2019-Template
      deploy_vsphere_datastore: datastore-01
      guest_custom_ip: 172.27.72.72
      ansible_connection: vmware_tools
      ansible_shell_type: powershell
```
What can we do to fix or troubleshoot this?
