### ISSUE TITLE
Phonenumber with plus sign in not set correctly

### ISSUE THREAD

**Issue by urskog84** [ansible-collections/ansible.windows#378]
##### SUMMARY

      telephoneNumber or mobile. is set but the + sign i removed some how
      ex +46730894473 is set to 46730894473

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
ansible [core 2.12.6]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/pefo/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/pefo/.local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/pefo/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.8.10 (default, Mar 15 2022, 12:22:08) [GCC 9.4.0]
  jinja version = 3.0.3
  libyaml = True
```

##### COLLECTION VERSION

```paste below
Collection        Version
----------------- -------
community.windows 1.10.0
```

##### CONFIGURATION

```paste below
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
```

##### STEPS TO REPRODUCE

```yaml
- name: Create user
  community.windows.win_domain_user:
    name: "pefo9999"
    firstname: "Petter"
    surname: "Fors"
    password: B0bP4ssw0rd
    attributes:
      telephoneNumber: "+46730894473"
      mobile: "+46730894473"
      pager: 2
    state: present
```

##### ACTUAL RESULTS

```paste below
Get-ADUser -Identity pefo9999 -Properties mobile,telephoneNumber


DistinguishedName : CN=pefo9999,OU=User,OU=External,OU=Clients,DC=int,DC=stadium,DC=biz
Enabled           : True
GivenName         : Petter
mobile            : 46730894473
Name              : pefo9999
ObjectClass       : user
ObjectGUID        : 5e02f3c0-dc26-44d0-a9cc-8c4ce91d326c
SamAccountName    : pefo9999
SID               : S-1-5-21-2729011942-1175983630-1496970501-21926
Surname           : Fors
telephoneNumber   : 46730894473
UserPrincipalName :

```
