### ISSUE TITLE
Support get information on one certificate by "issue_by" from a Windows Certificate Store

### ISSUE THREAD

**Issue by patsevanton** [ansible-collections/ansible.windows#382]
##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
community.windows.win_certificate_info

```yaml
    - name: Obtain information about all certificates in the root store
      community.windows.win_certificate_info:
        store_name: Root
        issued_by: "RootCA"
      register: rootca
```
