### ISSUE TITLE
UNC Path command is not recognised, despite the command being valid

### ISSUE THREAD

**Issue by Fvnnionz** [ansible-collections/ansible.windows#390]
##### SUMMARY
When I try and run a PS script from a UNC path with 'win_shell' on a target host I receive an error stating the command "is not recognized as the name of a cmdlet, function...". This is for the functionality of running a script from a remote location (server).

I created a simple Powershell script file to test this. When the exact same command  `. \\HOST2\c$\temp\updates\CDiskFacts.ps1` is run on the target host it works fine.

I have tried multiple variations: `. \\HOST2\c$\temp\updates\CDiskFacts.ps1` and `\\HOST2\c$\temp\updates\CDiskFacts.ps1` and they both result in the same error. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
win_shell

##### ANSIBLE VERSION

```
ansible 2.9.27
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/ssm-user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug 13 2020, 02:51:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### COLLECTION VERSION

```

```

##### CONFIGURATION

```
N/A
```

##### OS / ENVIRONMENT
Windows Server 2016/2019

##### STEPS TO REPRODUCE

```
tasks:
  - name: 'Run test CDiskFacts script from HOST2'
    win_shell: \\HOST2\c$\temp\updates\CDiskFacts.ps1
    become: yes
    become_method: runas
    become_flags: logon_type=new_credentials logon_flags=netcredentials_only
    vars:
      ansible_become_user: '{{ USER }}'
      ansible_become_pass: '{{ PASS }}'
    register: diskfacts
```

##### EXPECTED RESULTS
The standard results from 'Get-PSDrive C'

##### ACTUAL RESULTS

```
"stderr_lines": [
    ". : The term '\\\\HOST2\\c$\\temp\\updates\\CDiskFacts.ps1' is not recognized as the name of a ",
    "cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path ",
    "was included, verify that the path is correct and try again."
```

**Comment by jborean93** [comment]
I would do a `win_shell: Test-Path '\\HOST2\c$\temp\updates\CDiskFacts.ps1'` task with all your other options to see if the process can actually see the script at the UNC path. The fact that pwsh is unable to recognize it as a valid command would indicate it is still having permissions problems trying to access it.

If that's the case I would remove the templating `ansible_become_user` and `ansible_become_pass` values and hard code in a credential just to verify it's setting the right one. You could also try and set `ansible_become: yes` as a var rather than `become: yes` because the former takes precedence over the latter.

**Comment by Fvnnionz** [comment]
@jborean93  I managed to avoid adding the account creds directly into the playbook by adding them as a Custom Credential and then calling them in the playbook.

'Test-Path' came back 'false' from the Ansible playbook but true when running it directly on the same target host. The actual script itself continued to fail, which is expected if the Test-Path is failing.

Shown below is the code I used:

  ```
tasks:
    - name: Test file path
      win_shell: Test-Path '\\HOST2\c$\temp\updates\CDiskFacts.ps1'
      vars:
        ansible_become: yes
        ansible_become_method: runas
        ansible_become_flags: logon_type=new_credentials logon_flags=netcredentials_only
        ansible_become_user: '{{ WindowsAdmin_username }}'
        ansible_become_pass: '{{ WindowsAdmin_password }}'
      register: FilePath

    - name: 'Run test CDiskFacts script from Perems110'
      win_shell: \\HOST2\c$\temp\updates\CDiskFacts.ps1
      vars:
        ansible_become: yes
        ansible_become_method: runas
        ansible_become_flags: logon_type=new_credentials logon_flags=netcredentials_only
        ansible_become_user: '{{ WindowsAdmin_username }}'
        ansible_become_pass: '{{ WindowsAdmin_password }}'
      register: diskfacts
```
