### ISSUE TITLE
win_shell output encoding error

### ISSUE THREAD

**Issue by Po-temkin** [ansible-collections/ansible.windows#399]
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
win_shell

##### ANSIBLE VERSION

```
2.9.6

```

##### COLLECTION VERSION

```paste below

```

##### CONFIGURATION
```
```

##### OS / ENVIRONMENT
Windows Server 2019 Standart
Horizon Connection Server 8 2

##### STEPS TO REPRODUCE
For reproduce the problem you must have an installation of Horizon Connection Server. I try it on version 2208.
Output encoding error appear when trying to use 'vdmadmin.exe' with arguments from task 'Set the search exclusons'.
Output from task 'List the search exclusion' looks as i expect.

```yaml
- name: Determine hrzcs search exclusion
  hosts: all
  tasks: 

  - name: Set variables
    set_fact:
      win_shell_command_path: 'C:\Program Files\VMware\VMware View\Server\tools\bin\'
      win_shell_arg1: '-N -domains -search -domain'
      win_shell_arg2: '-add'
      win_shell_arg3: '-N -domains -search -list'

  - name: Set the search exclusion
    win_shell: 
      'vdmadmin.exe {{ win_shell_arg1 }} {{ item }} {{ win_shell_arg2 }}'
    args:
      chdir: '{{ win_shell_command_path }}'
      output_encoding_override: 'utf-8'

    with_items:
      - 'DOMAIN1'
      - 'DOMNAI2'
    
  - name: List the search exclusion
    win_shell: 
      'vdmadmin.exe {{ win_shell_arg3 }}'
    args:
      chdir: '{{ win_shell_command_path }}'
```

##### EXPECTED RESULTS
This message i can see if run command on host using PowerShell or CMD >
```
PS C:\Program Files\VMware\VMware View\Server\tools\bin> vdmadmin.exe -N -domains -search -domain DOMAIN1 -add
Error: Failed to configure domain configuration (The domain DOMAIN1 is already present in this list and cannot be added again)
```

##### ACTUAL RESULTS
Set the search exclusion
```
changed: [hostname.host.etc] => (item=DOMAIN1) => {
    "ansible_loop_var": "item",
    "changed": true,
    "cmd": "vdmadmin.exe -N -domains -search -domain DOMAIN1 -add",
    "delta": "0:00:00.571986",
    "end": "2022-08-09 07:37:19.984329",
    "item": "DOMAIN1",
    "rc": 0,
    "start": "2022-08-09 07:37:19.412343",
    "stderr": "T\u0000h\u0000e\u0000 \u0000d\u0000o\u0000m\u0000a\u0000i\u0000n\u0000 \u0000D\u0000O\u0000M\u0000A\u0000I\u0000N\u00001\u0000 \u0000h\u0000a\u0000s\u0000 \u0000b\u0000e\u0000e\u0000n\u0000 \u0000a\u0000d\u0000d\u0000e\u0000d\u0000 \u0000t\u0000o\u0000 \u0000t\u0000h\u0000e\u0000 \u0000s\u0000e\u0000a\u0000r\u0000c\u0000h\u0000 \u0000l\u0000i\u0000s\u0000t\u0000 \u0000f\u0000o\u0000r\u0000 \u0000t\u0000h\u0000e\u0000 \u0000c\u0000l\u0000u\u0000s\u0000t\u0000e\u0000r\u0000.\u0000\r\u0000\n\u0000",
    "stderr_lines": [
        "T\u0000h\u0000e\u0000 \u0000d\u0000o\u0000m\u0000a\u0000i\u0000n\u0000 \u0000D\u0000O\u0000M\u0000A\u0000I\u0000N\u00001\u0000 \u0000h\u0000a\u0000s\u0000 \u0000b\u0000e\u0000e\u0000n\u0000 \u0000a\u0000d\u0000d\u0000e\u0000d\u0000 \u0000t\u0000o\u0000 \u0000t\u0000h\u0000e\u0000 \u0000s\u0000e\u0000a\u0000r\u0000c\u0000h\u0000 \u0000l\u0000i\u0000s\u0000t\u0000 \u0000f\u0000o\u0000r\u0000 \u0000t\u0000h\u0000e\u0000 \u0000c\u0000l\u0000u\u0000s\u0000t\u0000e\u0000r\u0000.\u0000",
        "\u0000",
        "\u0000"
    ],
    "stdout": "",
    "stdout_lines": []
```
List the search exclusion
```

changed: [hostname.host.etc] => {
    "changed": true,
    "cmd": "vdmadmin.exe -N -domains -search -list",
    "delta": "0:00:00.511007",
    "end": "2022-08-09 08:19:18.924149",
    "rc": 0,
    "start": "2022-08-09 08:19:18.413141",
    "stderr": "",
    "stderr_lines": [],
    "stdout": "Domain Configuration (HOSTNAME)\r\r\n===================================\r\r\nCluster Settings\r\r\n   Include:\r\r\n   Exclude:\r\r\n   Search :\r\r\n     DOMNAI2\r\r\n     DOMAIN1\r\r\n\r\r\nBroker Settings: HOSTNAME \r\r\n   Include:\r\r\n   Exclude:\r\r\n   Search :\r\r\n",
    "stdout_lines": [
        "Domain Configuration (HOSTNAME)",
        "",
        "===================================",
        "",
        "Cluster Settings",
        "",
        "   Include:",
        "",
        "   Exclude:",
        "",
        "   Search :",
        "",
        "     DOMNAI2",
        "",
        "     DOMAIN1",
        "",
        "",
        "",
        "Broker Settings: HOSTNAME ",
        "",
        "   Include:",
        "",
        "   Exclude:",
        "",
        "   Search :",
        ""
    ]
}
```

**Comment by jborean93** [comment]
In this case you should be using `win_command` to execute your executable. The problem here is that `output_encoding_override` is to read the output from the shell executable that is run, which in this case is `powershell.exe`. This shell then runs your `vdmadmin.exe` executable but that's subject to the shell rules for running executables which for PowerShell will use the value of `[Console]::OutputEncoding` to read the raw value. The other problem is the output you are getting is actually UTF-16-LE (Unicode). You can tell as every 2nd char is essentially `\u0000`.

When you use `win_command` it is invoking your executable directly and the value of `output_encoding_override` is used to read the raw output and encode it to a string. In this case you want.

```yaml
- win_command: vdmadmin.exe -N -domains -search -domain DOMAIN1 -add
  args:
    output_encoding_override: utf-16
```

**Comment by Po-temkin** [comment]
Thank you for very fast answer
But win_command showing the same result

```
  - name: Set the search exclusion win_command
    win_command: vdmadmin.exe -N -domains -search -domain DOMAIN1 -add
    args:
      output_encoding_override: utf-16
```

Output

```
TASK [Set the search exclusion win_command] ***********************************************************************************************************************************************************************
task path: /path
Using module file /usr/lib/python2.7/site-packages/ansible/modules/windows/win_command.ps1
Pipelining is enabled.
<hostname> ESTABLISH WINRM CONNECTION FOR USER: user on PORT 5986 TO hostname
EXEC (via pipeline wrapper)
changed: [hostname] => {
    "changed": true,
    "cmd": "vdmadmin.exe -N -domains -search -domain DOMAIN1 -add",
    "delta": "0:00:00.166007",
    "end": "2022-08-09 11:22:17.946171",
    "rc": 0,
    "start": "2022-08-09 11:22:17.780163",
    "stderr": "E\u0000r\u0000r\u0000o\u0000r\u0000:\u0000 \u0000F\u0000a\u0000i\u0000l\u0000e\u0000d\u0000 \u0000t\u0000o\u0000 \u0000c\u0000o\u0000n\u0000f\u0000i\u0000g\u0000u\u0000r\u0000e\u0000 \u0000d\u0000o\u0000m\u0000a\u0000i\u0000n\u0000 \u0000c\u0000o\u0000n\u0000f\u0000i\u0000g\u0000u\u0000r\u0000a\u0000t\u0000i\u0000o\u0000n\u0000 \u0000(\u0000T\u0000h\u0000e\u0000 \u0000d\u0000o\u0000m\u0000a\u0000i\u0000n\u0000 \u0000D\u0000O\u0000M\u0000A\u0000I\u0000N\u00001\u0000 \u0000i\u0000s\u0000 \u0000a\u0000l\u0000r\u0000e\u0000a\u0000d\u0000y\u0000 \u0000p\u0000r\u0000e\u0000s\u0000e\u0000n\u0000t\u0000 \u0000i\u0000n\u0000 \u0000t\u0000h\u0000i\u0000s\u0000 \u0000l\u0000i\u0000s\u0000t\u0000 \u0000a\u0000n\u0000d\u0000 \u0000c\u0000a\u0000n\u0000n\u0000o\u0000t\u0000 \u0000b\u0000e\u0000 \u0000a\u0000d\u0000d\u0000e\u0000d\u0000 \u0000a\u0000g\u0000a\u0000i\u0000n\u0000)\u0000\r\u0000\n\u0000",
    "stderr_lines": [
        "E\u0000r\u0000r\u0000o\u0000r\u0000:\u0000 \u0000F\u0000a\u0000i\u0000l\u0000e\u0000d\u0000 \u0000t\u0000o\u0000 \u0000c\u0000o\u0000n\u0000f\u0000i\u0000g\u0000u\u0000r\u0000e\u0000 \u0000d\u0000o\u0000m\u0000a\u0000i\u0000n\u0000 \u0000c\u0000o\u0000n\u0000f\u0000i\u0000g\u0000u\u0000r\u0000a\u0000t\u0000i\u0000o\u0000n\u0000 \u0000(\u0000T\u0000h\u0000e\u0000 \u0000d\u0000o\u0000m\u0000a\u0000i\u0000n\u0000 \u0000D\u0000O\u0000M\u0000A\u0000I\u0000N\u00001\u0000 \u0000i\u0000s\u0000 \u0000a\u0000l\u0000r\u0000e\u0000a\u0000d\u0000y\u0000 \u0000p\u0000r\u0000e\u0000s\u0000e\u0000n\u0000t\u0000 \u0000i\u0000n\u0000 \u0000t\u0000h\u0000i\u0000s\u0000 \u0000l\u0000i\u0000s\u0000t\u0000 \u0000a\u0000n\u0000d\u0000 \u0000c\u0000a\u0000n\u0000n\u0000o\u0000t\u0000 \u0000b\u0000e\u0000 \u0000a\u0000d\u0000d\u0000e\u0000d\u0000 \u0000a\u0000g\u0000a\u0000i\u0000n\u0000)\u0000",
        "\u0000",
        "\u0000"
    ],
    "stdout": "",
    "stdout_lines": []
}
META: ran handlers
META: ran handlers
```
