### ISSUE TITLE
`win_acl` and `win_acl_inheritance` both fail when using become=yes on Windows.

### ISSUE THREAD

**Issue by kiwimato** [ansible-collections/ansible.windows#428]
##### SUMMARY
`win_acl` and `win_acl_inheritance` both fail successfully when using become=yes on Windows, so the task is executed successfully, but Ansible says it failed.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

win_acl, win_acl_inheritance

##### ANSIBLE VERSION

```
# I'm using Ansible Tower, and not sure I have access to view the version, or I don't know where to find it easily. However I do see these in the logs:

  ansible-playbook [core 2.12.5.post0]
  python version = 3.8.13 (default, Jun 24 2022, 15:27:57) [GCC 8.5.0 20210514 (Red Hat 8.5.0-13)]
  jinja version = 2.11.3
```

##### COLLECTION VERSION

```paste below

```

##### OS / ENVIRONMENT

I assume Ansible tower runs on RHEL, and the target system is Windows 2019 Datacenter

##### STEPS TO REPRODUCE

~It seems that win_acl only truly fails if I try to remove default permissions, as in when I check the actual Windows machine the permissions are still there.~

This code below seems to fail successfully, meaning it does disable the inheritance and add the necessary users, but Ansible says it failed with the error in "Actual Result":
```yaml
- name: Disable inherited ACE's for "{{ fsx_share }}"
  win_acl_inheritance:
    path: "{{ fsx_share }}"
    state: absent
    reorganize: yes
  run_once: true
  ignore_errors: yes  # task fails successfully with: "Preparing modules for first use", even though the permissions are set correctly
  vars:
    ansible_become: yes
    ansible_become_method: runas
    ansible_become_user: "{{ fsx_shareadmin_username }}"
    ansible_become_password: "{{ fsx_shareadmin_password }}"
- name: Add "{{ fsx_rw_group }}" group to read write
  ansible.windows.win_acl:
    path: "{{ fsx_share }}"
    user: "{{ fsx_rw_group }}"
    rights: Read,ReadAndExecute,Write,Modify,Delete
    type: allow
    state: present
    propagation: InheritOnly
  run_once: true
  ignore_errors: yes   # task fails successfully with: "Preparing modules for first use", even though the permissions are set correctly
  vars:
    ansible_become: yes
    ansible_become_method: runas
    ansible_become_user: "{{ fsx_shareadmin_username }}"
    ansible_become_password: "{{ fsx_shareadmin_password }}"
```

##### EXPECTED RESULTS

I'd expect the permissions to be set or removed exactly how it's supposed to work without ansible reporting a failure.

##### ACTUAL RESULTS

```

{
  "module_stdout": "{\"changed\":false}#< CLIXML<Objs Version=\"1.1.0.1\" xmlns=\"http://schemas.microsoft.com/powershell/2004/04\"><Obj S=\"progress\" RefId=\"0\"><TN RefId=\"0\"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N=\"SourceId\">1</I64><PR N=\"Record\"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj><Obj S=\"progress\" RefId=\"1\"><TNRef RefId=\"0\" /><MS><I64 N=\"SourceId\">2</I64><PR N=\"Record\"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>",
  "module_stderr": "",
  "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
  "rc": 1,
  "_ansible_no_log": false,
  "changed": false,
  "item": "ReadAndExecute",
  "ansible_loop_var": "item",
  "_ansible_item_label": "ReadAndExecute"
}
```

**Comment by kiwimato** [comment]
I just realized that rights removal failed due to "Synchronize" not being in the list I want to remove. 
Setting `rights: Modify, Synchronize` to win_acl will make it work, even though Ansible still says it failed.

**Comment by jborean93** [comment]
I can definitely see the `module_stdout` contains the proper module return json but it also includes some CLIXML from the become PowerShell process. Typically this only appears in the stderr so seeing it in the stdout is weird. I'll have to try and replicate it myself to figure out what might be going wrong here.

**Comment by jborean93** [comment]
I cannot seem to replicate this. I am using this as a test playbook

```yaml
- hosts: '2022'
  gather_facts: false
  tasks:
  - win_file:
      path: C:\temp\acl
      state: directory

  - block:
    - win_acl_inheritance:
        path: C:\temp\acl
        state: absent
        reorganize: true
      become: yes
      become_method: runas
      vars:
        ansible_become_user: vagrant
        ansible_become_pass: vagrant

    always:
    - win_file:
        path: C:\temp\acl
        state: absent
```

I've tried both the `winrm` and `psrp` connection plugin but both seem to work just fine. What is interesting is that the `rc` reported by become is also set to `1` causing Ansible to think there is a failure. The become method is simply doing `powershell.exe {module payload}` as another user and while the output contains the module output something is causing PowerShell to return an rc of 1.

Can you share with me:

* Your connection plugin that you are using
* Whether any other module fails with become, i.e. `win_ping`, `win_whoami`, anything really

It would also be great if you could set the environment variable `ANSIBLE_EXEC_DEBUG` to `C:\Windows\TEMP\ansible.log` (or any other path) on the Windows host in question and try to run only the `win_acl` or `win_acl_inheritance` command itself. This environment variable must be set on the Windows host itself and not through Ansible. It will create the log at the path specified with information about our bootstrap wrapper for further debugging.
