### ISSUE TITLE
`win_powershell` to check for module state being present

### ISSUE THREAD

**Issue by ncook-hxgn** [ansible-collections/ansible.windows#431]
##### SUMMARY

`win_powershell` to be able to manage powershell modules and powershell packaage providers.

##### COMPONENT NAME
community.win_powershell

##### ADDITIONAL INFORMATION

```yaml

- name: Install NuGet Package Provider
  ansible.windows.win_powershell:
    provider: NuGet
    state: present

- name: Install Az PowerShell Module
  ansible.windows.win_powershell:
    module: Az
    state: present
    scope: AllUsers # default CurrentUser

- name: Uninstall Az PowerShell Module
  ansible.windows.win_powershell:
    module: Az
    state: absent
    scope: AllUsers # default CurrentUser
        
```
