### ISSUE TITLE
win_certificate_store: Adding PFX certs to service account results in private key not visible

### ISSUE THREAD

**Issue by james-masson** [ansible-collections/ansible.windows#443]
##### SUMMARY

When importing a PFX including CA, signing certs, private key into a service account's "My" cert store, private key dissapears.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
win_certificate_store

##### ANSIBLE VERSION

```paste below
ansible 2.10.17
```

##### COLLECTION VERSION
```paste below
  - name: community.windows
    version: 1.11.0
```

##### CONFIGURATION

```paste below
(ansible) ansible-config dump --only-changed
ANSIBLE_PIPELINING(/ansible/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/ansible/ansible.cfg) = -o ControlMaster=auto -o ControlPersist=120s -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
DEFAULT_FILTER_PLUGIN_PATH(/ansible/ansible.cfg) = ['/ansible/plugins/filter-plugins']
DEFAULT_FORKS(/ansible/ansible.cfg) = 25
DEFAULT_HOST_LIST(/ansible/ansible.cfg) = ['/ansible/inventories/netbox']
DEFAULT_INVENTORY_PLUGIN_PATH(/ansible/ansible.cfg) = ['/ansible/plugins/inventory-plugins']
DEFAULT_LOOKUP_PLUGIN_PATH(/ansible/ansible.cfg) = ['/ansible/plugins/lookup-plugins']
DEFAULT_ROLES_PATH(/ansible/ansible.cfg) = ['/ansible/roles', '/ansible/roles/linux', '/ansible/roles/windows', '/ansible/roles/bootstrap', '/ansible/roles/misc']
DEFAULT_TIMEOUT(/ansible/ansible.cfg) = 30
DEFAULT_VAULT_PASSWORD_FILE(env: ANSIBLE_VAULT_PASSWORD_FILE) = /dev/shm/.ansible_vault
DEPRECATION_WARNINGS(/ansible/ansible.cfg) = False
HOST_KEY_CHECKING(env: ANSIBLE_HOST_KEY_CHECKING) = False
```

##### OS / ENVIRONMENT
Windows Server 2019

##### STEPS TO REPRODUCE
When importing a PFX including CA, signing certs, private key into a service account's "My" cert store, private key dissapears.

```
- name: Import code signing certificate to personal store of user
  ansible.windows.win_certificate_store:
    path: '{{ my_path }}'
    file_type: pkcs12
    password: "{{ my_password }}"
    store_location: CurrentUser
    store_name: My
    key_storage: user
    key_exportable: yes
  become: yes
  become_method: runas
  become_user: "{{ my_user }}"
  register: _install_cert
  when: not ansible_check_mode

```

as signtool sees it...
```
The following certificates were considered:
<redacted>
After EKU filter, 3 certs were left.
After expiry filter, 3 certs were left.
After Private Key filter, 0 certs were left.
```

And attempting a manual export of the cert results in the "export private key" checkbox greyed out

When I...
1. Bring up a powershell console using the service account
2. Close the console
3. Delete certs via ansible
4. Add certs via ansible

Now signtool can see the private key

```
The following certificates were considered:
<redacted>
After EKU filter, 3 certs were left.
After expiry filter, 3 certs were left.
After Private Key filter, 1 certs were left.
The following certificate was selected:
<redacted>
Done Adding Additional Store
Successfully signed: <redacted>
```

And attempting a manual export of the cert results in the "export private key" working fine.

##### EXPECTED RESULTS

Private key is visible

##### ACTUAL RESULTS

Missing private key

**Comment by jborean93** [comment]
Not sure if it's just your example but you've use become without a password set for `my_user`. There are two ways Ansible will attempt to use become when no password is set:

+ If there is no active interactive logon for that account it uses a Batch logon
+ If there is an active interactive logon for that account it uses that logon token

In the first example it is a Batch logon with no password set so it cannot unlock the DPAPI store to store the private key. In the second example it uses an Interactive logon which for interactive logons has the DPAPI store unlocked so it can add entries into it. This examples why when you ae logged on as that user then run Ansible the private key exists.

To ensure that this always works you should specify the become password on the task and not rely on no password become process which could result in a batch logon.

```yaml
- name: Import code signing certificate to personal store of user
  ansible.windows.win_certificate_store:
    path: '{{ my_path }}'
    file_type: pkcs12
    password: "{{ my_password }}"
    store_location: CurrentUser
    store_name: My
    key_storage: user
    key_exportable: yes
  become: yes
  become_method: runas
  vars:
    ansible_become_user: "{{ my_user }}"
    ansible_become_pass: "{{ my_password }}"
  register: _install_cert
  when: not ansible_check_mode
```

I am curious as to why it didn't fail though. Will have to look further into it to see if there's a way to validate it or maybe just display a warning saying there was a key in the pfx but it failed to import it or something.
