### ISSUE TITLE
Small error in the docs for ansible.windows.win_updates

### ISSUE THREAD

**Issue by silhouette** [ansible-collections/ansible.windows#468]
There seems to be a small error in the documentation. Here it says "category_name" instead of "category_names":

```yaml
- name: Install only particular updates based on the KB numbers
  ansible.windows.win_updates:
    category_name:
    - SecurityUpdates
    accept_list:
    - KB4056892
    - KB4073117
```
