### ISSUE TITLE
win_package module not working anymore and retuns Access is denied, Win32ErrorCode 5 - 0x00000005

### ISSUE THREAD

**Issue by mihai-satmarean** [ansible-collections/ansible.windows#476]
##### SUMMARY

win_package not working anymore and returns:
```json
{
  "exception": "Exception calling \"CreateProcess\" with \"7\" argument(s): \"CreateProcessW() failed (Access is denied, Win32ErrorCode 5 - 0x00000005)\"\nAt line:678 char:15\r\n+     $result = Start-AnsibleWindowsProcess @commandArgs\r\n+               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n    + CategoryInfo          : NotSpecified: (:) [Start-AnsibleWindowsProcess], MethodInvocationException\n    + FullyQualifiedErrorId : Win32Exception,Start-AnsibleWindowsProcess\r\n\r\nScriptStackTrace:\r\nat Start-AnsibleWindowsProcess, <No file>: line 230\r\nat Invoke-Executable, <No file>: line 678\r\nat <ScriptBlock>, <No file>: line 1327\r\nat <ScriptBlock>, <No file>: line 1479\r\n\r\nSystem.Management.Automation.MethodInvocationException: Exception calling \"CreateProcess\" with \"7\" argument(s): \"CreateProcessW() failed (Access is denied, Win32ErrorCode 5 - 0x00000005)\" ---> ansible_collections.ansible.windows.plugins.module_utils.Process.Win32Exception: CreateProcessW() failed (Access is denied, Win32ErrorCode 5 - 0x00000005)\r\n   at ansible_collections.ansible.windows.plugins.module_utils.Process.ProcessUtil.NativeCreateProcess(String applicationName, String commandLine, SecurityAttributes processAttributes, SecurityAttributes threadAttributes, Boolean inheritHandles, ProcessCreationFlags creationFlags, IDictionary environment, String currentDirectory, StartupInfo startupInfo) in c:\\Users\\Administrator\\AppData\\Local\\Temp\\glfkpdaz.0.cs:line 440\r\n   at ansible_collections.ansible.windows.plugins.module_utils.Process.ProcessUtil.CreateProcess(String lpApplicationName, String lpCommandLine, String lpCurrentDirectory, IDictionary environment, Byte[] stdin, String outputEncoding, Boolean waitChildren) in c:\\Users\\Administrator\\AppData\\Local\\Temp\\glfkpdaz.0.cs:line 404\r\n   at CallSite.Target(Closure , CallSite , Type , Object , String , String , Object , Object , String , SwitchParameter )\r\n   --- End of inner exception stack trace ---\r\n   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)\r\n   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)\r\n   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)\r\n   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)\r\n   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)\r\n   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)\r\n   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)\r\n   at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()\r\n   at System.Management.Automation.CommandProcessorBase.Complete()",
  "msg": "Unhandled exception while executing module: Exception calling \"CreateProcess\" with \"7\" argument(s): \"CreateProcessW() failed (Access is denied, Win32ErrorCode 5 - 0x00000005)\"",
  "_ansible_no_log": null,
  "changed": false
}
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

win_package
##### ANSIBLE VERSION

```paste below
ansible-playbook [core 2.14.3]
  config file = /runner/project/ansible.cfg
  configured module search path = ['/home/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/site-packages/ansible
  ansible collection location = /runner/requirements_collections:/home/runner/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.9.16 (main, Dec  8 2022, 00:00:00) [GCC 11.3.1 20221121 (Red Hat 11.3.1-4)] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
Using /runner/project/ansible.cfg as config file
setting up inventory plugins
host_list declined parsing /runner/inventory/hosts as it did not pass its verify_file() method
Parsed /runner/inventory/hosts inventory source with script plugin
Loading callback plugin default of type stdout, v2.0 from /usr/local/lib/python3.9/site-packages/ansible/plugins/callback/default.py
Loading callback plugin awx_display of type stdout, v2.0 from /usr/local/lib/python3.9/site-packages/ansible_runner/display_callback/callback/awx_display.py
```

##### COLLECTION VERSION

```paste below
    "Starting collection install process",
    "Downloading https://galaxy.ansible.com/download/ansible-posix-1.5.1.tar.gz to /var/lib/awx/projects/.__awx_cache/_8__nexodus_virtual_studio_01/stage/tmp/ansible-local-350088a_rvha7d/tmpisd6whki/ansible-posix-1.5.1-585z87so",
    "Installing 'ansible.posix:1.5.1' to '/var/lib/awx/projects/.__awx_cache/_8__nexodus_virtual_studio_01/stage/requirements_collections/ansible_collections/ansible/posix'",
    "ansible.posix:1.5.1 was installed successfully",
    "Downloading https://galaxy.ansible.com/download/community-windows-1.12.0.tar.gz to /var/lib/awx/projects/.__awx_cache/_8__nexodus_virtual_studio_01/stage/tmp/ansible-local-350088a_rvha7d/tmpisd6whki/community-windows-1.12.0-wz7qiyqw",
    "Installing 'community.windows:1.12.0' to '/var/lib/awx/projects/.__awx_cache/_8__nexodus_virtual_studio_01/stage/requirements_collections/ansible_collections/community/windows'",
    "community.windows:1.12.0 was installed successfully",
    "Downloading https://galaxy.ansible.com/download/ansible-windows-1.13.0.tar.gz to /var/lib/awx/projects/.__awx_cache/_8__nexodus_virtual_studio_01/stage/tmp/ansible-local-350088a_rvha7d/tmpisd6whki/ansible-windows-1.13.0-nvfju0f8",
    "Installing 'ansible.windows:1.13.0' to '/var/lib/awx/projects/.__awx_cache/_8__nexodus_virtual_studio_01/stage/requirements_collections/ansible_collections/ansible/windows'",
    "ansible.windows:1.13.0 was installed successfully",
    "Downloading https://galaxy.ansible.com/download/community-aws-5.2.0.tar.gz to /var/lib/awx/projects/.__awx_cache/_8__nexodus_virtual_studio_01/stage/tmp/ansible-local-350088a_rvha7d/tmpisd6whki/community-aws-5.2.0-22jzwjbl",
    "Installing 'community.aws:5.2.0' to '/var/lib/awx/projects/.__awx_cache/_8__nexodus_virtual_studio_01/stage/requirements_collections/ansible_collections/community/aws'",
    "community.aws:5.2.0 was installed successfully",
    "Downloading https://galaxy.ansible.com/download/amazon-aws-5.3.0.tar.gz to /var/lib/awx/projects/.__awx_cache/_8__nexodus_virtual_studio_01/stage/tmp/ansible-local-350088a_rvha7d/tmpisd6whki/amazon-aws-5.3.0-hcc8guqk",
    "Installing 'amazon.aws:5.3.0' to '/var/lib/awx/projects/.__awx_cache/_8__nexodus_virtual_studio_01/stage/requirements_collections/ansible_collections/amazon/aws'",
    "amazon.aws:5.3.0 was installed successfully",
    "Downloading https://galaxy.ansible.com/download/community-general-6.4.0.tar.gz to /var/lib/awx/projects/.__awx_cache/_8__nexodus_virtual_studio_01/stage/tmp/ansible-local-350088a_rvha7d/tmpisd6whki/community-general-6.4.0-3cpsuw6u",
    "Installing 'community.general:6.4.0' to '/var/lib/awx/projects/.__awx_cache/_8__nexodus_virtual_studio_01/stage/requirements_collections/ansible_collections/community/general'",
    "community.general:6.4.0 was installed successfully"
```

##### CONFIGURATION

```paste below
"is AWX"
```

##### OS / ENVIRONMENT

 "______________ 
<  AWX 21.0.0  >
 -------------- 
          \
          \   ^__^
              (oo)\_______
              (__)      A )\
                  ||----w |
                  ||     ||
"
##### STEPS TO REPRODUCE

using AWX

```yaml
- name: Install the grafana agent
  ansible.windows.win_package:
    path: C:\Temp\grafana-agent-installer.exe
    wait_for_children: yes
    arguments:
      - /S
      - /EnableExporter true
      - /Username "{{ grafana_cloud_loki_user }}"
      - /Password "{{ grafana_cloud_api_key }}"
      - /Url "{{ grafana_cloud_loki_url }}"
```

##### EXPECTED RESULTS

before this week it was installing

##### ACTUAL RESULTS

we got an error

```paste below
is the playbook
```

**Comment by jborean93** [comment]
Can you explain what may have changed between when it was working and when it was not? Did you upgrade Ansible, the `ansible.windows` collection, something about the server?

**Comment by hiyokotaisa** [comment]
@mihai-satmarean @jborean93 I can replicate the issue on the latest version of grafana-agent(v0.32.1) with latest ansible.windows collection. Howerver, this error does not appear when installing old version of grafana-agent(v0.31.0) with same environment.

So basically this issue is coming from latest garafana-agent, not win_package module.

**Comment by jborean93** [comment]
Thanks for sharing, is this exe something I can download myself to try and replicate?

**Comment by hiyokotaisa** [comment]
@jborean93 you can grab grafana-agent from here:
https://github.com/grafana/agent/releases

I tested v.0.32.1(problematic) and v0.31.0 (no issue) on Windows Server 2022.

https://github.com/grafana/agent/releases/download/v0.32.1/grafana-agent-installer.exe.zip
https://github.com/grafana/agent/releases/download/v0.31.0/grafana-agent-installer.exe

Here is the replicator playbook to install and uninstall the grafana agent
```
---
- hosts: all
  gather_facts: no
  tasks:
    - name: Install the grafana agent
      ansible.windows.win_package:
        path: C:\Users\Administrator\Downloads\grafana-agent-installer.exe
        wait_for_children: yes
        arguments:
          - /S
          - /EnableExporter true
          - /Username "hiyoko"
          - /Password "piyopiyo"
          - /Url "http://example.com"

    - name: Uninstall the grafana agent
      ansible.windows.win_package:
        path: C:\Program Files\Grafana Agent\uninstall.exe
        arguments:
          - /S
```

Oddly I can install latest version of grafana-agent without any error after I installed old version of grafana-agent. I cannot replicate it anymore even if I uninstall the old version of grafana-agent but not sure why.

**Comment by jborean93** [comment]
No worries, it's definitely good info for me to have and I'll try and replicate it next week. Just an FYI when using a list of arguments the argument and their value should typically be a separate list entry like:


```yaml
arguments:
- /S
- /EnableExporter
- true
- /Username
- hiyoko
- /Password
- test
- /Url
- http://example.com
```

**Comment by hiyokotaisa** [comment]
Thanks! FYI, here is the full traceback of the issue that I can replicated:
```
The full traceback is:
Exception calling "CreateProcess" with "7" argument(s): "CreateProcessW() failed (Access is denied, Win32ErrorCode 5 - 0x00000005)"
At line:667 char:15
+     $result = Start-AnsibleWindowsProcess @commandArgs
+               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Start-AnsibleWindowsProcess], MethodInvocationException
    + FullyQualifiedErrorId : Win32Exception,Start-AnsibleWindowsProcess

ScriptStackTrace:
at Start-AnsibleWindowsProcess, <No file>: line 230
at Invoke-Executable, <No file>: line 667
at <ScriptBlock>, <No file>: line 1289
at <ScriptBlock>, <No file>: line 1439

System.Management.Automation.MethodInvocationException: Exception calling "CreateProcess" with "7" argument(s): "CreateProcessW() failed (Access is denied, Win32ErrorCode 5 - 0x00000005)" ---> ansible_collections.ansible.windows.plugins.module_utils.Process.Win32Exception: CreateProcessW() failed (Access is denied, Win32ErrorCode 5 - 0x00000005)
   at ansible_collections.ansible.windows.plugins.module_utils.Process.ProcessUtil.NativeCreateProcess(String applicationName, String commandLine, SecurityAttributes processAttributes, SecurityAttributes threadAttributes, Boolean inheritHandles, ProcessCreationFlags creationFlags, IDictionary environment, String currentDirectory, StartupInfo startupInfo) in c:\Users\Administrator\AppData\Local\Temp\fc4hl3t3.2.cs:line 440
   at ansible_collections.ansible.windows.plugins.module_utils.Process.ProcessUtil.CreateProcess(String lpApplicationName, String lpCommandLine, String lpCurrentDirectory, IDictionary environment, Byte[] stdin, String outputEncoding, Boolean waitChildren) in c:\Users\Administrator\AppData\Local\Temp\fc4hl3t3.2.cs:line 404
   at CallSite.Target(Closure , CallSite , Type , Object , String , String , Object , Object , String , SwitchParameter )
   --- End of inner exception stack trace ---
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
   at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess)
   at System.Management.Automation.PSScriptCmdlet.DoEndProcessing()
   at System.Management.Automation.CommandProcessorBase.Complete()
fatal: [test-win]: FAILED! => {
    "changed": false,
    "msg": "Unhandled exception while executing module: Exception calling \"CreateProcess\" with \"7\" argument(s): \"CreateProcessW() failed (Access is denied, Win32ErrorCode 5 - 0x00000005)\""
}

PLAY RECAP *************************************************************************************************************
test-win                   : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
```

**Comment by jborean93** [comment]
@hiyokotaisa I retrieved the latest installer from the link you've supplied and cannot replicate this problem, this was without even installing the older version. I also noticed the link for the `0.32.1` version is for a zip file not an actual exe. I did extract it manually but just wanted to point it out.

How did you get these exe's onto the target host before you installed it with `win_package`? Maybe that process is setting up the files in a way in which they can't be invoked.

**Comment by hiyokotaisa** [comment]
@jborean93 I downloaded `0.32.1` version from Egde browser that is built-in the Windows Server 2022 and extract it from Explorer in GUI. Then I run the playbook that I shared and saw the same issue. I used `Administrator` account to download  and using same user for `ansible_user`.

**Comment by jborean93** [comment]
Thanks for confirming, I did exactly that and it was still able to run, even using the arguments you've specified and it was fine


```yaml
changed: [adhoc] => changed=true
  invocation:
    module_args:
      arguments:
      - /S
      - /EnableExporter true
      - /Username "user"
      - /Password "pass"
      - /Url "http://example.com"
      chdir: null
      client_cert: null
      client_cert_password: null
      creates_path: null
      creates_service: null
      creates_version: null
      expected_return_code:
      - 0
      - 3010
      follow_redirects: safe
      force_basic_auth: false
      headers: null
      http_agent: ansible-httpget
      log_path: null
      maximum_redirection: 50
      password: null
      path: C:\Users\vagrant\Downloads\grafana-agent-installer.exe\grafana-agent-installer.exe
      product_id: null
      provider: auto
      proxy_password: null
      proxy_url: null
      proxy_use_default_credential: false
      proxy_username: null
      state: present
      url_method: null
      url_password: null
      url_timeout: 30
      url_username: null
      use_default_credential: false
      use_proxy: true
      username: null
      validate_certs: true
      wait_for_children: true
  rc: 0
  reboot_required: false
```

The only way I can replicate this is if the downloaded file does not have the `Execute` rights for the current user but that would require either an explicit Deny rule or essentially for inheritance to be disabled. Even so in that particular scenario the error is expected because the user does not have Read/Execute rights on the exe to run it.
