### ISSUE TITLE
win_domain_membership failing with "Value was either too large or too small for an Int32."

### ISSUE THREAD

**Issue by shadowink** [ansible-collections/ansible.windows#484]
##### SUMMARY
win_domain_membership is failing to join a domain with the error 'failed to join domain: Value was either too large or too small for an Int32.'

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ansible.windows.win_domain_membership

##### ANSIBLE VERSION

```
ansible-playbook [core 2.12.7]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/opt/morpheus/.local/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /var/opt/morpheus/morpheus-local/workspace/ansible-int-19/collections-85148aad-9cb7-470b-b4f9-996ee2beccd9:/opt/morpheus/.local/.ansible/collections
  executable location = /usr/bin/ansible-playbook
  python version = 3.8.10 (default, Mar 13 2023, 10:26:41) [GCC 9.4.0]
  jinja version = 2.10.1
  libyaml = True

also failed on 

ansible [core 2.14.1]
  config file = None
  configured module search path = ['/Users/alberghi/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ansible
  ansible collection location = /Users/alberghi/.ansible/collections:/usr/share/ansible/collections
  executable location = /Library/Frameworks/Python.framework/Versions/3.9/bin/ansible
  python version = 3.9.6 (v3.9.6:db3ff76da1, Jun 28 2021, 11:49:53) [Clang 6.0 (clang-600.0.57)] (/Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9)
  jinja version = 3.0.1
  libyaml = True
```

##### COLLECTION VERSION

```

# /opt/morpheus/.local/.ansible/collections/ansible_collections
Collection        Version
----------------- -------
community.windows 1.12.0

# /usr/lib/python3/dist-packages/ansible_collections
Collection        Version
----------------- -------
community.windows 1.10.0

and 

# /Users/alberghi/.ansible/collections/ansible_collections
Collection        Version
----------------- -------
community.windows 1.11.0

# /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ansible_collections
Collection        Version
----------------- -------
community.windows 1.11.1

```

##### CONFIGURATION

```

```

##### OS / ENVIRONMENT

Ubuntu 20 and macOS 13.3

##### STEPS TO REPRODUCE

```
- ansible.windows.win_domain_membership:
    dns_domain_name: ad.keysight.com
    hostname: "{{vmname | truncate(15, true, '', 0 ) }}"
    domain_admin_user: "MYDOMAIN\\{{domainjoin_user}}"
    domain_admin_password: "{{domainjoin_pass}}"
    domain_ou_path: "OU=KPC-EPH,OU=PROJ,OU=ResourceOU,DC=AD,DC=MYDOMAIN,DC=COM"
    state: domain
  register: domain_state

```

##### EXPECTED RESULTS

Domain joined
##### ACTUAL RESULTS

```
fatal: [10.17.22.29]: FAILED! => {
    "changed": true,
    "msg": "failed to join domain: Value was either too large or too small for an Int32.",
    "reboot_required": false
}

```

I had our AD team look in the logs and there were no failed authentications or denied joins from the account we use for domain joining during the window we tested.
