### ISSUE TITLE
win_updates reboot:True - host is not rebooted, module returns error

### ISSUE THREAD

**Issue by DouglasHeriot** [ansible-collections/ansible.windows#49]
##### SUMMARY

I've set `win_updates` `reboot: True` so that the hosts will be rebooted if necessary. However I've had one host fail with error message `A reboot is required before more updates can be installed`.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

win_updates

##### ANSIBLE VERSION

```paste below
ansible 2.9.7
  config file = /home/douglas/Code/infra-as-code/ansible.cfg
  configured module search path = ['/home/douglas/Code/infra-as-code/lib/ansible/modules']
  ansible python module location = /home/douglas/Code/infra-as-code/venv/lib/python3.6/site-packages/ansible
  executable location = /home/douglas/Code/infra-as-code/venv/bin/ansible
  python version = 3.6.9 (default, Apr 18 2020, 01:56:04) [GCC 8.4.0]
```

##### CONFIGURATION

```paste below
ANSIBLE_PIPELINING(/home/douglas/Code/infra-as-code/ansible.cfg) = True
COLLECTIONS_PATHS(/home/douglas/Code/infra-as-code/ansible.cfg) = ['/home/douglas/Code/infra-as-code/vendor']
DEFAULT_CLICONF_PLUGIN_PATH(/home/douglas/Code/infra-as-code/ansible.cfg) = ['/home/douglas/Code/infra-as-code/lib/ansible/plugins/cliconf
DEFAULT_FORKS(/home/douglas/Code/infra-as-code/ansible.cfg) = 30
DEFAULT_HOST_LIST(/home/douglas/Code/infra-as-code/ansible.cfg) = ['/home/douglas/Code/infra-as-code/inventory/staging.yml']
DEFAULT_INVENTORY_PLUGIN_PATH(/home/douglas/Code/infra-as-code/ansible.cfg) = ['/home/douglas/Code/infra-as-code/lib/ansible/plugins/inven
DEFAULT_LOOKUP_PLUGIN_PATH(/home/douglas/Code/infra-as-code/ansible.cfg) = ['/home/douglas/Code/infra-as-code/lib/ansible/plugins/lookup']
DEFAULT_MODULE_PATH(/home/douglas/Code/infra-as-code/ansible.cfg) = ['/home/douglas/Code/infra-as-code/lib/ansible/modules']
DEFAULT_MODULE_UTILS_PATH(/home/douglas/Code/infra-as-code/ansible.cfg) = ['/home/douglas/Code/infra-as-code/lib/ansible/module_utils']
DEFAULT_PRIVATE_KEY_FILE(/home/douglas/Code/infra-as-code/ansible.cfg) = /home/douglas/.ssh/ctadmin_rsa
DEFAULT_ROLES_PATH(/home/douglas/Code/infra-as-code/ansible.cfg) = ['/home/douglas/Code/infra-as-code/vendor/roles', '/home/douglas/Code/i
DEFAULT_STDOUT_CALLBACK(/home/douglas/Code/infra-as-code/ansible.cfg) = debug
DEFAULT_TERMINAL_PLUGIN_PATH(/home/douglas/Code/infra-as-code/ansible.cfg) = ['/home/douglas/Code/infra-as-code/lib/ansible/plugins/termin
HOST_KEY_CHECKING(/home/douglas/Code/infra-as-code/ansible.cfg) = False
INTERPRETER_PYTHON(/home/douglas/Code/infra-as-code/ansible.cfg) = auto_silent
TRANSFORM_INVALID_GROUP_CHARS(/home/douglas/Code/infra-as-code/ansible.cfg) = ignore
```

##### OS / ENVIRONMENT

Ansible host: Ubuntu 18.04 LTS
Target host: Windows  10 1903

##### STEPS TO REPRODUCE

```yaml
      - name: Update Windows Hosts
        win_updates:
          state: installed
          reboot: True
          category_names:
            - "Application"
            - "Connectors"
            - "Critical Updates"
            - "Definition Updates"
            - "Developer Kits"
            - "Feature Packs"
            - "Guidance"
            - "Security Updates"
            - "Service Packs"
            - "Tools"
            - "Update Rollups"
            - "Updates"
            - "Windows Defender"
```

##### EXPECTED RESULTS

All updates should be installed, host rebooted as many times as necessary.

##### ACTUAL RESULTS

```paste below
fatal: [WINDOWS-HOST]: FAILED! => {
    "changed": false,
    "filtered_updates": {},
    "found_update_count": 1,
    "installed_update_count": 0,
    "reboot_required": true,
    "updates": {
        "a5becc0d-4344-493b-96f6-4945bbeae18b": {
            "categories": [
                "Updates",
                "Windows 10, version 1903 and later"
            ],
            "id": "a5becc0d-4344-493b-96f6-4945bbeae18b",
            "installed": false,
            "kb": [
                "4497165"
            ],
            "title": "2020-01 Update for Windows 10 Version 1903 for x64-based Systems (KB4497165)"
        }
    }
}

MSG:

A reboot is required before more updates can be installed
```
