### ISSUE TITLE
win_powershell using parameters dict when calling script

### ISSUE THREAD

**Issue by peterfranks** [ansible-collections/ansible.windows#497]
I am trying to use win_powershell for my Ansible playbooks, and I am admittedly new to this. However, I have gotten something to work using the more rudimentary ansible.windows.win_shell. I wanted to try moving to ansible.windows.win_powershell as this seems a bit cleaner.

However, when I try to pass parameters using the "parameters" dict argument to the win_powershell target, it seems to basically not work at all. Is this expected currently? I don't see any unit tests on this, and internet searching (even on this board) shows me no one else having this issue. Looking at the source code, it appears that this should work, but maybe there is a bug where nothing gets passed.

Example playbook:
```
---
# tasks file for install
  - name: Copy Install PS1 Script To Host
    copy:
      src: install.ps1
      dest: C:\ansible\
      
  - name: Execute Install Script
    ansible.windows.win_powershell:
      script: C:\ansible\install.ps1
      error_action: stop
      parameters:
        verstring: any_value_here
```

When I look to my log file on the endpoint, the install.ps1 script is run, but the variable of verstring is blank.

Has anyone else seen this?

**Comment by jborean93** [comment]
The `script` here is actual PowerShell code that is being run not the path to a script to run so in this case the command that is being run on the top level is:

```powershell
param ($verstring)

C:\ansible\install.ps1
```

You would have to do something like this to also apply that parameter to running your script

```yaml
- name: Execute Install Script
  ansible.windows.win_powershell:
    script: |
      param($verstring)

      C:\ansible\install.ps1 -verstring $verstring
    error_action: stop
    parameters:
      verstring: any_value_here
```

You could also do any of the following

```yaml
- name: Execute Install Script
  ansible.windows.win_powershell:
    script: C:\ansible\install.ps1 -verstring $args[0]
    error_action: stop
    parameters:
      verstring: any_value_here


# This avoids copying the script in a second task
- name: Execute Install Script
  ansible.windows.win_powershell:
    script: '{{ lookup('file", "install.ps1") }}'
    error_action: stop
    parameters:
      verstring: any_value_here
```

Hopefully this helps.
