### ISSUE TITLE
Add 'validate' to win_template

### ISSUE THREAD

**Issue by rwaweber** [ansible-collections/ansible.windows#50]
Copied from https://github.com/ansible/ansible/issues/35661

##### SUMMARY
Add validate parameter to win_template module with the same behavior as the [template](https://docs.ansible.com/ansible/latest/modules/template_module.html#parameter-validate) module.

##### ISSUE TYPE
- Feature Request

##### COMPONENT NAME
win_template module

##### ADDITIONAL INFORMATION
Mostly copying from the old ansible repo: Copied from https://github.com/ansible/ansible/issues/35661

```yaml
- name: Create a Unix-style file from a Jinja2 template
  win_template:
    src: unix/config.conf.j2
    dest: C:\share\unix\config.conf
    newline_sequence: '\n'
    backup: yes
    validate: 'C:\Program Files\customtool\bin\run.exe test -c %s'
```
