### ISSUE TITLE
win_uri module: The request was aborted: Could not create SSL/TLS secure channel.

### ISSUE THREAD

**Issue by westy1221** [ansible-collections/ansible.windows#501]
##### SUMMARY

This looks to be related to a previously closed issue:
https://github.com/ansible/ansible/issues/35413

Receiving the error "The request was aborted: Could not create SSL/TLS secure channel" when requesting the file from:
https://software.ans.uk/pub/installer_vista_win7_win8-64-3.8.0.722.msi

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

win_uri

##### ANSIBLE VERSION

```paste below
ansible [core 2.11.12] 
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/<redacted>/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/<redacted>/work/python_ven/py38-ansible6/lib/python3.8/site-packages/ansible
  ansible collection location = /home/<redacted>/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/<redacted>/work/python_ven/py38-ansible6/bin/ansible
  python version = 3.8.10 (default, Mar 13 2023, 10:26:41) [GCC 9.4.0]
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```paste below
# /home/<redacted>/work/python_ven/py38-ansible6/lib/python3.8/site-packages/ansible_collections
Collection        Version
----------------- -------
community.general 3.8.3  

# /home/<redacted>/.ansible/collections/ansible_collections
Collection        Version
----------------- -------
community.general 6.4.0  
```

##### CONFIGURATION

```paste below
n/a
```

##### OS / ENVIRONMENT

Ubuntu 20.04.6 LTS; Microsoft Windows Server 2012 R2 Standard; "ansible_powershell_version": 4

##### STEPS TO REPRODUCE

```yaml
- name: Download Carbon Black installer
  ansible.windows.win_get_url:
    validate_certs: no
    url: https://software.ans.uk/pub/installer_vista_win7_win8-64-3.8.0.722.msi
    dest: C:\Users\<user>\Downloads
```

##### ACTUAL RESULTS

```paste below
The full traceback is:
The request was aborted: Could not create SSL/TLS secure channel.
At line:429 char:13
+             $web_response = $Request.GetResponse()
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], WebException
    + FullyQualifiedErrorId : WebException

 

ScriptStackTrace:
at Invoke-AnsibleWindowsWebRequest, <No file>: line 429
at Invoke-DownloadFile, <No file>: line 216
at <ScriptBlock>, <No file>: line 265
fatal: [<host>]: FAILED! => {
    "changed": false,
    "dest": "C:\\Users\\<user>\\Downloads\\installer_vista_win7_win8-64-3.8.0.722.msi",
    "elapsed": 0.42190649999999996,
    "invocation": {
        "module_args": {
            "checksum": null,
            "checksum_algorithm": "sha1",
            "checksum_url": null,
            "client_cert": null,
            "client_cert_password": null,
            "dest": "C:\\Users\\<user>\\Downloads",
            "follow_redirects": "safe",
            "force": true,
            "force_basic_auth": false,
            "headers": null,
            "http_agent": "ansible-httpget",
            "maximum_redirection": 50,
            "proxy_password": null,
            "proxy_url": null,
            "proxy_use_default_credential": false,
            "proxy_username": null,
            "url": "[https://software.ans.uk/pub/installer_vista_win7_win8-64-3.8.0.722.msi"](https://software.ans.uk/pub/installer_vista_win7_win8-64-3.8.0.722.msi%22),
            "url_method": null,
            "url_password": null,
            "url_timeout": 30,
            "url_username": null,
            "use_default_credential": false,
            "use_proxy": true,
            "validate_certs": false
        }
    },
    "msg": "Error downloading '[https://software.ans.uk/pub/installer_vista_win7_win8-64-3.8.0.722.msi'](https://software.ans.uk/pub/installer_vista_win7_win8-64-3.8.0.722.msi%27) to 'C:\\Users\\<user>\\Downloads\\installer_vista_win7_win8-64-3.8.0.722.msi': The request was aborted: Could not create SSL/TLS secure channel.",
    "status_code": null,
    "url": "[https://software.ans.uk/pub/installer_vista_win7_win8-64-3.8.0.722.msi"](https://software.ans.uk/pub/installer_vista_win7_win8-64-3.8.0.722.msi%22)
```

**Comment by jborean93** [comment]
This error occurs when the client is unable to perform the TLS handshake, this can be done to a few things like:

* The certificate is signed by a CA that is untrusted or is self signed
* The certificate subject or SAN does not match the hostname you've given it
* The server does not support the TLS protocols the client is offering
* The server does not support the TLS cipher suites the client is offering
* The server does not support the signature algorithms the client is offering

Unfortunately the error surfaced by dotnet and Windows isn't helpful at all in trying to fix this but there is not much else we can do about it.

This particular error is most likely due to the server not supporting any of the cipher suites offered by the client. The [SSLLabs results](https://www.ssllabs.com/ssltest/analyze.html?d=software.ans.uk) indicate only these ciphers are supported by the server

* TLS_AES_128_GCM_SHA256
* TLS_AES_256_GCM_SHA384
* TLS_CHACHA20_POLY1305_SHA256
* TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 (ECDH curve secp256r1)
* TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 (ECDH curve secp256r1)
* TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256

You can view the list of supported cipher suites for Server 2012 R2 at  https://learn.microsoft.com/en-us/windows/win32/secauthn/tls-cipher-suites-in-windows-8-1. The only match here in that list is `TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256_P256` (curve secp256r1) so theoretically it should be possible for you to negotiate the cipher suites. When looking at the TLS exchange from a test Server 2012 R2 host I see the following in the client hello and server hello response:

```yaml
# Client Hello
- ContentType: handshake (22)
  ProtocolVersion: TLS 1.2 (0x0303) (771)
  Data:
  - HandshakeType: client_hello (1)
    Data:
      ProtocolVersion: TLS 1.2 (0x0303) (771)
      Random: 6452B1A621BB8459589533D674C63F394E5A3AAF68A61939765CC94DA8618822
      SessionID: ''
      CipherSuites:
      - TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 - 0xC028
      - TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 - 0xC027
      - TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA - 0xC014
      - TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA - 0xC013
      - TLS_DHE_RSA_WITH_AES_256_GCM_SHA384 - 0x009F
      - TLS_DHE_RSA_WITH_AES_128_GCM_SHA256 - 0x009E
      - TLS_DHE_RSA_WITH_AES_256_CBC_SHA - 0x0039
      - TLS_DHE_RSA_WITH_AES_128_CBC_SHA - 0x0033
      - TLS_RSA_WITH_AES_256_GCM_SHA384 - 0x009D
      - TLS_RSA_WITH_AES_128_GCM_SHA256 - 0x009C
      - TLS_RSA_WITH_AES_256_CBC_SHA256 - 0x003D
      - TLS_RSA_WITH_AES_128_CBC_SHA256 - 0x003C
      - TLS_RSA_WITH_AES_256_CBC_SHA - 0x0035
      - TLS_RSA_WITH_AES_128_CBC_SHA - 0x002F
      - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 - 0xC02C
      - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 - 0xC02B
      - TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384 - 0xC024
      - TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256 - 0xC023
      - TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA - 0xC00A
      - TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA - 0xC009
      - TLS_DHE_DSS_WITH_AES_256_CBC_SHA256 - 0x006A
      - TLS_DHE_DSS_WITH_AES_128_CBC_SHA256 - 0x0040
      - TLS_DHE_DSS_WITH_AES_256_CBC_SHA - 0x0038
      - TLS_DHE_DSS_WITH_AES_128_CBC_SHA - 0x0032
      - TLS_RSA_WITH_3DES_EDE_CBC_SHA - 0x000A
      - TLS_DHE_DSS_WITH_3DES_EDE_CBC_SHA - 0x0013
      - TLS_RSA_WITH_RC4_128_SHA - 0x0005
      - TLS_RSA_WITH_RC4_128_MD5 - 0x0004
      CompressionMethods:
      - none (0)
      Extensions:
      - ExtensionType: server_name (0)
        Data:
        - Type: server_name (0)
          Name: software.ans.uk
        RawData: 001200000F736F6674776172652E616E732E756B
      - ExtensionType: supported_groups (10)
        Data:
        - secp256r1 (23)
        - secp384r1 (24)
        RawData: '000400170018'
      - ExtensionType: ec_point_formats (11)
        Data:
        - uncompressed (0)
        RawData: '0100'
      - ExtensionType: signature_algorithms (13)
        Data:
        - rsa_pkcs1_sha512 (1537)
        - ecdsa_secp521r1_sha512 (1539)
        - rsa_pkcs1_sha256 (1025)
        - rsa_pkcs1_sha384 (1281)
        - rsa_pkcs1_sha1 (513)
        - ecdsa_secp256r1_sha256 (1027)
        - ecdsa_secp384r1_sha384 (1283)
        - ecdsa_sha1 (515)
        - dsa_sha1 (514)
        RawData: '0012060106030401050102010403050302030202'
      - ExtensionType: session_ticket (35)
      - ExtensionType: extended_master_secret (23)
      - ExtensionType: renegotiation_info (65281)
        RawData: '00'

# Server Hello + KEK
- ContentType: handshake (22)
  ProtocolVersion: TLS 1.2 (0x0303) (771)
  Data:
  - HandshakeType: server_hello (2)
    Data:
      ProtocolVersion: TLS 1.2 (0x0303) (771)
      Random: 6313E165484AA517E86DAE154D6C15152FD8F7828092A6E0444F574E47524401
      SessionID: ''
      CipherSuite: TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 - 0xC02B
      CompressionMethod: none (0)
      Extensions:
      - ExtensionType: session_ticket (35)
      - ExtensionType: renegotiation_info (65281)
        RawData: '00'
      - ExtensionType: ec_point_formats (11)
        Data:
        - uncompressed (0)
        RawData: '0100'
- ContentType: handshake (22)
  ProtocolVersion: TLS 1.2 (0x0303) (771)
  Data:
  - HandshakeType: certificate (11)
    Data:
      Certificate: ...
- ContentType: handshake (22)
  ProtocolVersion: TLS 1.2 (0x0303) (771)
  Data:
  - HandshakeType: server_key_exchange (12)
    Data:
      CurveType: named_curve (3)
      Curve: secp256r1 (23)
      PublicKey:
        046AE972CBA69794381B32E07C9EE5A18213322FF9DC42CBA322B9EAF41CAA7641092F9F40590F051621AEF76A35339BAEE6A05705576800F2314A854085E3C869
      SignatureAlgorithm: ecdsa_secp521r1_sha512 (1539)
      Signature:
        3045022018882E0877C6C49F7AAF82028143EAC08E6642A3E58911F6E5AC373017BF35B9022100E3B700E33C36E4C5877463190A59BFB8CA72DC8648E290022AF6EF1080F3EB91
- ContentType: handshake (22)
  ProtocolVersion: TLS 1.2 (0x0303) (771)
  Data:
  - HandshakeType: server_hello_done (14)
```

We can see that the client offered the cipher suite `TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256` and the ECDH curve `secp256r1` which the server then chose in its response.

At a guess as to what's happening on your host is that either those ciphers have been explicitly disabled or they require an update from Microsoft to be installed before they can be used. Unfortunately there's not much else I can do to help you here. The error you are getting is the expected one if the TLS handshake fails and it's highly dependent on your client and the server being able to negotiate a common set of protocols and cipher suites.
