### ISSUE TITLE
win_group_membership "Some or all identity references could not be translated."

### ISSUE THREAD

**Issue by alphaxr6** [ansible-collections/ansible.windows#502]
##### SUMMARY
Error "Some or all identity references could not be translated." when trying to add domain user to local group on windows server

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
win_group_membership

##### ANSIBLE VERSION

```
ansible 2.9.27
```

##### COLLECTION VERSION
```
community.windows:1.13.0
```

##### CONFIGURATION
```
ALLOW_WORLD_READABLE_TMPFILES(/etc/ansible/ansible.cfg) = True
DEFAULT_CALLBACK_WHITELIST(/etc/ansible/ansible.cfg) = ['profile_tasks']
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT
```
3.15.7
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.15.7
PRETTY_NAME="Alpine Linux v3.15"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"
```

##### STEPS TO REPRODUCE

```
     - name: Add domain user to a local group
       ansible.windows.win_group_membership:
         name: Administrators
         members:
           - user1@domain
           - user2@domain
           - user3@domain
         state: present
```

##### EXPECTED RESULTS

Add the domain user account into the local group Administrators of a windows server

##### ACTUAL RESULTS

```
fatal: [hostname]: FAILED! => {"changed": false, "msg": "account_name user1@domain is not a valid account, cannot get SID: Exception calling \"Translate\" with \"1\" argument(s): \"Some or all identity references could not be translated.\""}
```
