### ISSUE TITLE
win_updates always fails with WinRMOperationTimeoutError on starting Round 2 after reboot

### ISSUE THREAD

**Issue by jdptechnc** [ansible-collections/ansible.windows#511]
##### SUMMARY

Using the win_updates module against clean installed Windows 2016 and Windows 2019 VMs.  I allow the win_updates module to reboot hosts when required.  On "Round 2", immediately after the first reboot, a WinRMOperationTimeoutError is encountered, and the task stalls until the task timeout is exceeded.  When timeout is exceeded, a Kerberos error is returned.

I already have a rescue block in place to handle general failures, which runs win_updates again, and this is my current workaround for the issue.  However, to allow for long-running updates and/or long reboots, my task has the reboot_timeout option set for the module, and a timeout defined at the task level.  I have to wait for both timeouts to be exceeded, which lengthens the duration of the update installation.

I encountered this issue with ansible.windows collection 1.13. I tried the latest version (1.14) and had the same issue.

Hosts are using winrm plugin.  I have tried increasing the ansible_winrm_operation_timeout_sec  and ansible_winrm_read_timeout_sec values, but it does not seem to make a difference (the WinRMOperationTimeoutError happens fairly quickly).

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

win_updates

##### ANSIBLE VERSION

```paste below
ansible [core 2.14.6]
  config file = /home/jdptechnc/ansible/ansible.cfg
  configured module search path = ['/home/jdptechnc/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/jdptechnc/ansible/venvs/windows-project/lib64/python3.9/site-packages/ansible
  ansible collection location = /home/jdptechnc/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/jdptechnc/ansible/venvs/windows-project/bin/ansible
  python version = 3.9.14 (main, Jan  9 2023, 00:00:00) [GCC 11.3.1 20220421 (Red Hat 11.3.1-2)] (/home/jdptechnc/ansible/venvs/windows-project/bin/python)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```paste below

# /home/jdptechnc/.ansible/collections/ansible_collections
Collection      Version
--------------- -------
ansible.windows 1.13.0 
```

##### CONFIGURATION

```paste below
CONFIG_FILE() = /home/jdptechnc/ansible/ansible.cfg
DEFAULT_FORKS(/home/jdptechnc/ansible/ansible.cfg) = 100
```

##### OS / ENVIRONMENT

Ansible control machine: RHEL 9.1
Target hosts: Windows Server 2016 and Windows Server 2019
Hypervisor: VMware vSphere 7.0 Update 3.  All VMs have updated VMware tools and using VMXNET3 adapter.

##### STEPS TO REPRODUCE

```yaml
- name: Install Security Updates - Install all pending Windows security updates
  ansible.windows.win_updates:
      reboot_timeout: 1800 
      category_names: 
        - SecurityUpdates 
        - Updates
      reboot: "{{ win_update_reboot_allowed }}"       
      state: installed 
      log_path: "{{ windows_update_ansible_log_path | default(omit) }}"
  throttle: "{{ windows_update_throttle }}"
  timeout: 3600
  register: update_results
```

##### Connection settings from inventory file

```yaml
# WINRM connection settings
ansible_connection: winrm
ansible_winrm_transport: kerberos
ansible_winrm_scheme: http
ansible_winrm_server_cert_validation: ignore
ansible_port: 5985
ansible_winrm_operation_timeout_sec: 300   
ansible_winrm_read_timeout_sec: 360
```

##### EXPECTED RESULTS

Windows Updates installed, reboot if required, and continue checking/installing for updates until all in-scope updates are completed.

##### ACTUAL RESULTS

WinRM error immediatly following the first reboot.  Kerberos exception is display after the task times out.

```paste below
TASK [jdptechnc.windows.updates_install : Install Security Updates - Install all pending Windows security updates] ***********************************************************************************************************************************************************
<test11.mydomain.com> Running win_updates - round 1
<test11.mydomain.com> Rebooting host after installing updates
<test11.mydomain.com> Running win_updates - round 2
[WARNING]: ERROR DURING WINRM SEND INPUT - attempting to recover: WinRMOperationTimeoutError
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: kerberos.GSSError: (('No context has been established', 524288), ('Attempt to use incomplete security context', 39756039))
fatal: [test11.mydomain.com]: FAILED! => {"msg": "Unexpected failure during module execution: (('No context has been established', 524288), ('Attempt to use incomplete security context', 39756039))", "stdout": ""}
```
