### ISSUE TITLE
win_update: powershell process hangs, prevents further updates from running

### ISSUE THREAD

**Issue by rendername** [ansible-collections/ansible.windows#524]
##### SUMMARY
When running updates on multiple servers, we see a couple of servers that never finish updating. These block other servers from starting their updates as well. When investigating the issue we find a powershell process started by ansible that is still running. If we manually kill the powershell process the whole systems gets unstuck and ansible correctly moves on to the other servers. This issue happens intermittently and not always on the same servers.

On the server UI we notice the upgrades are still displaying but the logs show the install has completed. Once we click on "install now" the upgrades disappear from the UI immediately.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
- win_update

##### ANSIBLE VERSION

```
ansible [core 2.11.6]
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  ansible collection location = /home/user/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 2.7.18 (default, Feb 28 2023, 02:51:06) [GCC 7.3.1 20180712 (Red Hat 7.3.1-15)]
  jinja version = 2.7.2
  libyaml = True
```

##### COLLECTION VERSION

```
Collection      Version
--------------- -------
ansible.windows 1.7.3
```

##### CONFIGURATION

```
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = [u'/root/path/to/hosts']
```

##### OS / ENVIRONMENT

- Windows Server 2019

##### STEPS TO REPRODUCE

```yaml
  - name: MAINTENANCE | WINDOWS UPDATES | INSTALL
    win_updates:
      category_names:
        - SecurityUpdates
        - CriticalUpdates
        - UpdateRollups
        - DefinitionUpdates
        - Updates
      log_path: C:\ansible\logs\winupdate-{{ ansible_date_time.iso8601 | replace(':','') }}.log
      reboot_timeout: 1200
      reboot: true
    register: update_results
    ignore_errors: true
```

##### EXPECTED RESULTS

Ansbile would finish up the powershell script running and continue with other server updates.

##### ACTUAL RESULTS

Ansible triggers powershell on the remote host and it hangs until the powershell process is killed manually. This blocks all other server updates from happening. Once killed updates resume as expected.

```paste below
2023-05-27 09:49:40Z Install failed to invoke powershell script: Exception calling "WriteProgress" with "2" argument(s): "Could not find a part of the path 'C:\Users\myuser\AppData\Local\Temp\ansible-tmp-1685174538.3835797-20734-125913791846751\output.txt'."
2023-05-27 09:49:40Z Install result for df6327d2-bd7f-4a7a-8775-61ac20592e4a - ResultCode: Succeeded, HResult: 0, RebootRequired: True
```
[winupdate-2023-05-27T080159Z.log](https://github.com/ansible-collections/ansible.windows/files/11907041/winupdate-2023-05-27T080159Z.log)
