### ISSUE TITLE
win_update fails

### ISSUE THREAD

**Issue by alphaxr6** [ansible-collections/ansible.windows#528]
##### SUMMARY

```ansible.windows.win_update``` module keeps on failing 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

```ansible.windows.win_updates```

##### ANSIBLE VERSION

```
ansible 2.9.27
```

##### COLLECTION VERSION

```
latest
```

##### CONFIGURATION

```
ansible-config dump --only-changed
ALLOW_WORLD_READABLE_TMPFILES(/etc/ansible/ansible.cfg) = True
DEFAULT_CALLBACK_WHITELIST(/etc/ansible/ansible.cfg) = ['profile_tasks']
DEFAULT_STDOUT_CALLBACK(env: ANSIBLE_STDOUT_CALLBACK) = default
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Runner: [Alpine Linux](alpine:3.15)
Dest. Host: Windows Server 2022

##### STEPS TO REPRODUCE

```
 - name: Install all security updates with automatic reboots
   ansible.windows.win_updates:
     category_names:
     - SecurityUpdates
     - CriticalUpdates
     reboot: yes


 - name: Ensure we wait long enough for the updates to be applied during reboot
   ansible.windows.win_updates:
     reboot: yes
     reboot_timeout: 3600
```

##### EXPECTED RESULTS

Running Windows update to install the last update deployed by Microsoft.

##### ACTUAL RESULTS

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ansible_collections.ansible.windows.plugins.action.win_updates._ReturnResultException: Failed to invoke batch job: Unable to find type [Ansible.Windows.Process.StartupInfo].
fatal: [XXXX]: FAILED! => {"changed": false, "failed_update_count": 0, "filtered_updates": {}, "found_update_count": 0, "installed_update_count": 0, "msg": "Failed to invoke batch job: Unable to find type [Ansible.Windows.Process.StartupInfo].", "updates": {}}

```
