### ISSUE TITLE
win_environment doesnt resolve %var%

### ISSUE THREAD

**Issue by markatdxb** [ansible-collections/ansible.windows#535]
##### SUMMARY

im trying to set 2 env vars when the second one should resolve the first one 
when using SETX command this works fine but using module the resolv doesnt work

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

win_environment 
##### ANSIBLE VERSION

```paste below
8.1.0
2.15.1
```

##### COLLECTION VERSION

```paste below

```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

```yaml
- name: Update Env vars
      ansible.windows.win_environment:
        state: present
        name: "{{ item.var_name }}"
        value: "{{ item.var_value }}"
        level: machine
      loop:
        - var_name: VAR_A
          var_value: VALUE_A
        - var_name: VAR_B
          var_value: '%VAR_A%-VALUE_B'
```

##### EXPECTED RESULTS

```
set
VAR_A=VALUE_A
VAR_B=VALUE_A-VALUE_B
```

##### ACTUAL RESULTS

```paste below
set
VAR_A=VALUE_A
VAR_B=%VAR_A%-VALUE_B
```
