### ISSUE TITLE
Issue on running ansible.windows.win_updates module

### ISSUE THREAD

**Issue by HaomouJi** [ansible-collections/ansible.windows#540]
##### SUMMARY
Received error message while using ansible.windows.win_updates.   Ansible 1.13.0.

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```Paste below
 Ansible 2.15.0
```

##### COLLECTION VERSION

```paste below
Ansible.windows 1.14.0
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

windows 2012-2019

##### STEPS TO REPRODUCE

```yaml
- name: WIN PATCHING - PRE-INSTALL - Search for and Download Updates
      ansible.windows.win_updates:
        category_names: '*'
        state: downloaded
      register: winpatch_download_status
```

##### EXPECTED RESULTS

list available KBs

##### ACTUAL RESULTS

```paste below
TASK [win_patching : WIN PATCHING - PRE-INSTALL - Search for and Download Updates] ***
task path: /runner/requirements_roles/win_patching/tasks/main.yml:20
The full traceback is:
Exception calling "NativeCreateProcess" with "9" argument(s): "CreateProcessW() failed (Access is denied, Win32ErrorCode 5 - 0x00000005)"
At line:388 char:9
+         $pi = [Ansible.Windows.Process.ProcessUtil]::NativeCreateProc ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : Win32Exception

ScriptStackTrace:
at Invoke-AsBatchLogon, <No file>: line 388
at <ScriptBlock>, <No file>: line 1534
fatal: [dwa620802135802.btfin-dev.com]: FAILED! => {
    "changed": false,
    "failed_update_count": 0,
    "filte…
```
