### ISSUE TITLE
RFE: win_dns_client should support diff and return what changes where made

### ISSUE THREAD

**Issue by opoplawski** [ansible-collections/ansible.windows#561]
##### SUMMARY
win_dns_client does not give any information about what was changed.  It should support diff mode and return variables indicating the adapters changed.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
win_dns_client

##### ADDITIONAL INFORMATION

```yaml
    -  ansible.windows.win_dns_client:
        adapter_names: '*'
        dns_servers:
          - 10.0.0.1
          - 10.0.0.2
```
```
result: {
  "changed": true,
  "modified": ["Ethernet Connection 1"], 
  "diff": {
    "before": { [ "name": "Ethernet Connection 1", "dns_servers": ["192.168.1.1"] },
    "after": { [  "name": "Ethernet Connection 1", "dns_servers": ["10.0.0.1", "10.0.0.2"] }
  }
}
<!--- HINT: You can also paste gist.github.com links for larger files -->
