### ISSUE TITLE
win_update: Add the ability to exclude certain category_names

### ISSUE THREAD

**Issue by foss4ever** [ansible-collections/ansible.windows#570]
##### SUMMARY
win_update - add the option to explicitly exclude certain category_names, while including all other categories.  

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
ansible.windows.win_updates

##### ADDITIONAL INFORMATION
It would allow me to ignore Windows Defender definition updates when scanning for updates to install.

```
---
- hosts: "{{ var_hosts }}"
  tasks:
    - name: Search available updates
      ansible.windows.win_updates:
        state: searched
        skip_optional: true
        # example option for excluding certain update categories:
        exclude_categories: DefinitionUpdates
      register: result

    - name: Output search result
      ansible.builtin.debug:
        var: result
```
