### ISSUE TITLE
Determining the root cause of the extra params warning in ansible.windows

### ISSUE THREAD

**Issue by JerrickTram** [ansible-collections/ansible.windows#580]
I'm attempting to replicate the warning: `this task 'ansible.windows.win_command' has extra params, which is only allowed in the following modules: ...` as it showed up in our output of a job template in AWX. It uses Ansible version 2.10.17 and its being ran against windows hosts. 

```
---
- hosts: localhost
  tasks: 
     - name: Reproduce extra param warning/error with win_command
       win_command: whoami.exe /all
       args:
          stdin: systeminfo
       register: whoami

     - name: Return Ansible version
       ansible.builtin.debug:
          msg: "Ansible version is {{ ansible_version.full }}."

     - name: Check if warning exists
       ansible.builtin.debug:
          msg: "{{ whoami.stdout }}"
```

What I was expecting with this sample playbook is to return that warning due to the extra parameter with the `stdin` definition. Using the free-form version of `win_command` instead of the FQCN version for testing sakes. But, the playbook ended up executing fine without any issue in AWX. Previous versions of Ansible mentioned parsing and syntax errors triggering the warning. However, that was for versions prior to 2.10. I've also gotten feedback that it could potentially be using a different collection version of `ansible.windows`. But I'm not too sure (let alone if there is a way to get the current version of this collection). Any tips in the right direction are appreciated.
