### ISSUE TITLE
win_find cant find mapped drive nor networkshare

### ISSUE THREAD

**Issue by KrzesloSzatan** [ansible-collections/ansible.windows#584]
##### SUMMARY
Module can't find files when paths pointed to a mapped drive or a network share.

Task looks like this:

```
- name: Find file with highest version
      ansible.windows.win_find:
        paths: "M:\\aaa\\bbb\\xxx"
        patterns: "zzz-*.exe"
        file_type: file
      register: file_result
```

Error i get:

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: at <ScriptBlock>, <No file>: line 437
fatal: [host]: FAILED! => {"changed": false, "msg": "Unhandled exception while executing module: Exception calling \"GetUnresolvedProviderPathFromPSPath\" with \"1\" argument(s): \"Cannot find drive. A drive with the name 'M' does not exist.\""}

```
And when i try to point to a network path like \\sss\\aaa\\bbb\\xxx it tries to search in **C:**\\sss\\aaa\\bbb\\xxx
```

[WARNING]: Argument path '**C:**\\sss\\aaa\\bbb\\xxx' does not exist or is not accessible, skipping
```

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ansible.windows.win_find

##### ANSIBLE VERSION

```
ansible [core 2.13.13]
  python version = 3.8.10 (default, Jun 22 2022, 20:18:18) [GCC 9.4.0]
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```
Collection      Version
--------------- -------
ansible.windows 1.12.0
```

##### OS / ENVIRONMENT

Target OS: Windows 11
Ansible Host: WSL Ubuntu

##### EXPECTED RESULTS
Find file in provided path

##### ACTUAL RESULTS
Cant find mapped drive or network share location

**Comment by jborean93** [comment]
This is as expected, mapped drives do not work in a network logon/non-interactive context. You have to use the UNC path and even then you also need to contend with the double hop/credential delegation problem. To overcome this you can use CredSSP auth or Kerberos with delegation enabled. You can also use become on the task to explicitly provide credentials for the double hop context. See https://docs.ansible.com/ansible/latest/os_guide/windows_winrm.html#winrm-limitations for more details.

**Comment by KrzesloSzatan** [comment]
> This is as expected, mapped drives do not work in a network logon/non-interactive context. You have to use the UNC path and even then you also need to contend with the double hop/credential delegation problem. To overcome this you can use CredSSP auth or Kerberos with delegation enabled. You can also use become on the task to explicitly provide credentials for the double hop context. See https://docs.ansible.com/ansible/latest/os_guide/windows_winrm.html#winrm-limitations for more details.

Im provisioning Windows with SSH, not winrm - does it change anything ?

**Comment by jborean93** [comment]
Yes it means you either have to use password auth, kerberos with delegation, or become.

**Comment by KrzesloSzatan** [comment]
> Yes it means you either have to use password auth, kerberos with delegation, or become.

Well, i am actually using that. Either in mapping drives and/or win_find module. 

The actual code looks like this 

```
- name: Save the network credentials required for the mapped drive
    community.windows.win_credential:
      name: fileshare
      type: domain_password
      username: '{{ ansible_ssh_user }}'
      secret: '{{ ansible_ssh_password }}'
      state: present

  - name: Create a mapped drive that requires authentication
    community.windows.win_mapped_drive:
      letter: "{{ item.letter }}"
      path: "{{ item.path }}"
      state: present
    with_items:
      - { path: "\\\\sss\\aaa\\bbb\\xxx", letter: "M" }
      - { path: "\\\\sss\\aaa\\bbb\\www$", letter: "L" }
	vars:
	# become is required to save and retrieve the credentials in the tasks
	ansible_become: yes
	ansible_become_method: runas
	ansible_become_user: '{{ ansible_ssh_user }}'
	ansible_become_pass: '{{ ansible_ssh_password }}'

    - name: Find file with highest version
      ansible.windows.win_find:
        paths: "M:\\aaa\\bbb\\xxx"
        patterns: "zzz-*.exe"
        file_type: file
      register: file_result
      vars:
        ansible_become: yes
        ansible_become_method: runas
        ansible_become_user: '{{ ansible_ssh_user }}'
        ansible_become_pass: '{{ ansible_ssh_password }}'
```

What is wrong with it ?

**Comment by jborean93** [comment]
As I said you cannot use mapped drives in a network logon context. As the notes for [win_mapped_drive says](https://docs.ansible.com/ansible/latest/collections/community/windows/win_mapped_drive_module.html#notes)

> You cannot use this module to access a mapped drive in another Ansible task, drives mapped with this module are only accessible when logging in interactively with the user through the console or RDP.

The simplest choice for you is to use a UNC path with become to specify the credentials as per the [become docs](https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_privilege_escalation.html#become-and-windows). For example:

```yaml
- name: use become credential for outbound network logon
  ansible.windows.win_find:
    paths: \\server\share\folder
  vars:
    ansible_become: true
    ansible_become_method: runas
    ansible_become_user: DOMAIN\user
    ansible_become_password: Password01
    ansible_become_flags: logon_type=new_credentials logon_flags=netcredentials_only
```

**Comment by KrzesloSzatan** [comment]
> As I said you cannot use mapped drives in a network logon context. As the notes for [win_mapped_drive says](https://docs.ansible.com/ansible/latest/collections/community/windows/win_mapped_drive_module.html#notes)
> 
> > You cannot use this module to access a mapped drive in another Ansible task, drives mapped with this module are only accessible when logging in interactively with the user through the console or RDP.
> 
> The simplest choice for you is to use a UNC path with become to specify the credentials as per the [become docs](https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_privilege_escalation.html#become-and-windows). For example:
> 
> ```yaml
> - name: use become credential for outbound network logon
>   ansible.windows.win_find:
>     paths: \\server\share\folder
>   vars:
>     ansible_become: true
>     ansible_become_method: runas
>     ansible_become_user: DOMAIN\user
>     ansible_become_password: Password01
>     ansible_become_flags: logon_type=new_credentials logon_flags=netcredentials_only
> ```

Ive tried that but as ive stated before it forcefully tries to find this UNC path in C:

> And when i try to point to a network path like \\sss\aaa\bbb\xxx it tries to search in C:\sss\aaa\bbb\xxx
> 
> ```[WARNING]: Argument path 'C:\\sss\\aaa\\bbb\\xxx' does not exist or is not accessible, skipping```

**Comment by KrzesloSzatan** [comment]
> > As I said you cannot use mapped drives in a network logon context. As the notes for [win_mapped_drive says](https://docs.ansible.com/ansible/latest/collections/community/windows/win_mapped_drive_module.html#notes)
> > > You cannot use this module to access a mapped drive in another Ansible task, drives mapped with this module are only accessible when logging in interactively with the user through the console or RDP.
> > 
> > 
> > The simplest choice for you is to use a UNC path with become to specify the credentials as per the [become docs](https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_privilege_escalation.html#become-and-windows). For example:
> > ```yaml
> > - name: use become credential for outbound network logon
> >   ansible.windows.win_find:
> >     paths: \\server\share\folder
> >   vars:
> >     ansible_become: true
> >     ansible_become_method: runas
> >     ansible_become_user: DOMAIN\user
> >     ansible_become_password: Password01
> >     ansible_become_flags: logon_type=new_credentials logon_flags=netcredentials_only
> > ```
> 
> Ive tried that but as ive stated before it forcefully tries to find this UNC path in C:
> 
> > And when i try to point to a network path like \sss\aaa\bbb\xxx it tries to search in C:\sss\aaa\bbb\xxx
> > `[WARNING]: Argument path 'C:\\sss\\aaa\\bbb\\xxx' does not exist or is not accessible, skipping`

Ok, my bad. Ive noticed that i have put path in double quotes and forgot to add a second pair of \\ at the beginnig and thats why it didnt search precisely in network share. Thx for help.

**Comment by jborean93** [comment]
Thanks for confirming, just an FYI this only happens when you use double quotes as backslashes need to be escape with another backslash. For example this all results in the same value being parsed by YAML

```yaml
paths: \\server\share\folder
paths: '\\server\share\folder'
paths: "\\\\server\\share\\folder"
```

See https://docs.ansible.com/ansible/latest/os_guide/windows_usage.html#path-formatting-for-windows for more details.

I believe this answers your original question so I'm going to close this issue.
