### ISSUE TITLE
win_package: support checksum verification

### ISSUE THREAD

**Issue by mathstuf** [ansible-collections/ansible.windows#596]
##### SUMMARY
`win_package` should support checksum verification of network downloads

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
`ansible.windows.win_package`

##### ADDITIONAL INFORMATION
Verify that the downloaded file is the one expected before execution.

```yaml
- name: Install foobar
  ansible.windows.win_package:
    path: '{{ some_network_url }}'
    checksum: 'sha256sum:deadbeef…'
```
