### ISSUE TITLE
Windows Update Module not installing any updates

### ISSUE THREAD

**Issue by felixtech-msp** [ansible-collections/ansible.windows#603]
##### SUMMARY
The Windows Update module doesn't actually install any updates. It searches them and lists them.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ansible.windows.win_updates

##### ANSIBLE VERSION
```
ansible 2.10.8
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
```

##### COLLECTION VERSION

```paste below
[WARNING]: - unable to find windows.win_updates in collection paths

ERROR! Invalid collection name 'ansible.windows.win_updates', name must be in the format <namespace>.<collection>.
Please make sure namespace and collection name contains characters from [a-zA-Z0-9_] only.
```

This seems to be bugged. The version is whatever came with Ansible on 12 April 2024.

##### CONFIGURATION

```paste below
[this has no output]
```

##### OS / ENVIRONMENT

Target OS: Windows Server 2022

##### STEPS TO REPRODUCE

Playbook:
```yaml
---
- name: Windows Update
  hosts: all
  gather_facts: no
  tasks:
    - name: install all updates
      ansible.windows.win_updates:
        category_names: '*'
        state: installed
        reboot: false
      vars:
        ansible_become: yes
        ansible_become_method: runas
        ansible_become_user: SYSTEM
```

Variables:
```yaml
ansible_connection: winrm
ansible_winrm_transport: ntlm
ansible_winrm_server_cert_validation: ignore
ansible_user: DOMAIN\Administrator
ansible_password: "secretpassword"
```

##### EXPECTED RESULTS

Windows Updates should be searched and installed.

##### ACTUAL RESULTS

The available updates are listed but not installed.

If I manually install updates via the settings panel, those updates are found and installed.

```paste below
ok: [SV004] => {
    "changed": false,
    "filtered_updates": {
        "a8a2d6e3-c6dc-4eb8-bcfb-8c8c7d947899": {
            "categories": [
                "Microsoft Server operating system-21H2",
                "Security Updates"
            ],
            "filtered_reason": "category_names",
            "id": "a8a2d6e3-c6dc-4eb8-bcfb-8c8c7d947899",
            "installed": false,
            "kb": [
                "5034439"
            ],
            "title": "2024-01 Sicherheitsupdate für Microsoft server operating system version 21H2 für x64-basierte Systeme (KB5034439)"
        },
        "bb4336f5-ba8e-4a23-9f8d-040053fe425d": {
            "categories": [
                "Microsoft SQL Server 2019",
                "Updates"
            ],
            "filtered_reason": "category_names",
            "id": "bb4336f5-ba8e-4a23-9f8d-040053fe425d",
            "installed": false,
            "kb": [
                "5035123"
            ],
            "title": "SQL Server 2019 RTM Kumulatives Update (Cumulative Update, CU) 26 KB5035123"
        },
        "f95c6731-bb70-4c21-a8be-b7076bbf04e2": {
            "categories": [
                "Definition Updates",
                "Microsoft Defender Antivirus"
            ],
            "filtered_reason": "category_names",
            "id": "f95c6731-bb70-4c21-a8be-b7076bbf04e2",
            "installed": false,
            "kb": [
                "2267602"
            ],
            "title": "Security Intelligence-Update für Microsoft Defender Antivirus – KB2267602 (Version 1.409.237.0) – Aktueller Kanal (Allgemein)"
        }
    },
    "found_update_count": 0,
    "installed_update_count": 0,
    "reboot_required": false,
    "updates": {}
}
```
