### ISSUE TITLE
Error in Windows Update: Unhandled exception while executing module: Cannot process request because the process (PID) has exited

### ISSUE THREAD

**Issue by pts-aut** [ansible-collections/ansible.windows#623]
##### SUMMARY
We have created a playbook to check for windows updates, list them and install them with reboots.

On Windows Server 2019 Test-Systems it works without any issue - in another infrastructure (also on Windows Server 2019) the process is failing with:

_Unhandled exception while executing module: Cannot process request because the process (PID) has exited._

This Occurs in the win_updates module

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
Module: win_updates

##### ANSIBLE VERSION
ansible [core 2.16.8]
  python version = 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] (/usr/bin/python3)
  jinja version = 3.0.3

##### COLLECTION VERSION
```
Collection      Version
--------------- -------
ansible.windows 2.4.0
```

##### PLAYBOOK

```yaml
- name: Check for new updates
  win_updates:
    category_names: '*'
    state: searched
  register: update_result

- name: Updates available
  debug:
    msg: '{{ update_result.found_update_count }} Updates available.'

- name: Prepare list of updates
  set_fact:
    update_list: |
      {% for item in update_result.updates | dict2items %}
      {{ item.value.kb | join(', ') }} - {{ item.value.title }} ({{ item.value.categories | join(', ')  }})
      {% endfor %}

- name: Print available updates
  debug:
    msg: '{{ update_list.split(''\n'') }}'

- name: Install available updates and reboot if necessary during execution
  win_updates:
    category_names: '*'
    reboot: true
  register: update_result

- name: Updates installed
  debug:
    msg: '{{ update_result.installed_update_count }} Updates installed.'

- name: Prepare list of updates
  set_fact:
    update_list: |
      {% for item in update_result.updates | dict2items %}
      {{ item.value.kb | join(', ') }} - {{ item.value.title }} ({{ item.value.categories | join(', ')  }})
      {% endfor %}

- name: Print updates
  debug:
    msg: '{{ update_list.split(''\n'') }}'

- name: Reboot the server if required
  win_reboot:
    timeout: 600
  when: update_result.reboot_required

- name: Refresh Windows Update List
  ansible.windows.win_powershell:
    script: usoclient StartInteractiveScan
```

##### EXPECTED RESULTS
```
PLAY [Running on nodes using WinRM (WINDOWS)] **********************************

TASK [Check for new updates] ***************************************************
ok: [xxxxx@default]

TASK [Updates available] *******************************************************
ok: [xxxxx@default] => {
    "msg": "4 Updates available."
}

TASK [Prepare list of updates] *************************************************
ok: [xxxxx@default]

TASK [Print available updates] *************************************************
ok: [xxxxx@default] => {
    "msg": [
        "5039217 - 2024-06 Cumulative Update for Windows Server 2019 (1809) for x64-based Systems (KB5039217) (Security Updates)\n2267602 - Security Intelligence Update for Microsoft Defender Antivirus - KB2267602 (Version 1.413.630.0) - Current Channel (Broad) (Definition Updates, Microsoft Defender Antivirus)\n890830 - Windows Malicious Software Removal Tool x64 - v5.125 (KB890830) (Update Rollups, Windows Server 2016, Windows Server 2019)\n5038283 - 2024-05 Cumulative Update for .NET Framework 3.5, 4.7.2 and 4.8 for Windows Server 2019 for x64 (KB5038283) (Updates, Windows Server 2019)\n"
    ]
}

TASK [Install available updates and reboot if necessary during execution] ******
changed: [xxxxx@default]

TASK [Updates installed] *******************************************************
ok: [xxxxx@default] => {
    "msg": "4 Updates installed."
}

TASK [Prepare list of updates] *************************************************
ok: [xxxxx@default]

TASK [Print updates] ***********************************************************
ok: [xxxxx@default] => {
    "msg": [
        "5039217 - 2024-06 Cumulative Update for Windows Server 2019 (1809) for x64-based Systems (KB5039217) (Security Updates)\n2267602 - Security Intelligence Update for Microsoft Defender Antivirus - KB2267602 (Version 1.413.630.0) - Current Channel (Broad) (Definition Updates, Microsoft Defender Antivirus)\n890830 - Windows Malicious Software Removal Tool x64 - v5.125 (KB890830) (Update Rollups, Windows Server 2016, Windows Server 2019)\n5038283 - 2024-05 Cumulative Update for .NET Framework 3.5, 4.7.2 and 4.8 for Windows Server 2019 for x64 (KB5038283) (Updates, Windows Server 2019)\n"
    ]
}

TASK [Reboot the server if required] *******************************************
skipping: [xxxxx@default]

TASK [Refresh Windows Update List] *********************************************
changed: [xxxxx@default]

PLAY RECAP *********************************************************************
xxxxx@default    : ok=9    changed=2    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0   
```

##### ACTUAL RESULTS
```
...
TASK [Install available updates and reboot if necessary during execution] ******
An exception occurred during task execution. To see the full traceback, use -vvv. The error was:    at System.Management.Automation.CommandProcessorBase.Complete()
fatal: [xxxxx@default]: FAILED! => {"changed": false, "failed_update_count": 0, "filtered_updates": {}, "found_update_count": 0, "installed_update_count": 0, "msg": "Unhandled exception while executing module: Cannot process request because the process (10044) has exited.", "updates": {}}

PLAY RECAP *********************************************************************
xxxxx@default        : ok=5    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
```
