### ISSUE TITLE
Not able to run the win_update task on Windows server when Trellix Threat prevention enabled with Ansible version 2.16.6

### ISSUE THREAD

**Issue by rajmartha26** [ansible-collections/ansible.windows#635]
##### SUMMARY
We are experiencing an issue where the win_update task fails to run on Windows servers when Trellix Threat Prevention is enabled. This issue started occurring after upgrading to Ansible version 2.16.6. The same playbook was working fine with Ansible version 2.9.7.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
win_updates

##### ANSIBLE VERSION
Works with below Ansible version
```
ansible 2.9.27
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.18 (default, Dec 18 2023, 22:08:43) [GCC 7.3.1 20180712 (Red Hat 7.3.1-17)]
```

Does not work with below Ansible version
```
ansible [core 2.16.2]
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /root/.local/lib/python3.11/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /root/.local/bin/ansible
  python version = 3.11.7 (main, Jan 26 2024, 15:26:41) [GCC 8.5.0 20210514 (Red Hat 8.5.0-21)] (/usr/bin/python)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION
```
Collection      Version
--------------- -------
ansible.windows 2.2.0
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
Windows server OS: Windows 2022
Trellix agent and threat prevtion installed: Yes

##### STEPS TO REPRODUCE
```yaml
---
- hosts: all, localhost
  gather_facts: yes
  vars:
    http_port: 80
    https_port: 443
    max_clients: 200
    ansible_python_interpreter: auto_silent
  tasks:    
    - name: Print Info
      debug:
        msg:
          - "The operating system family is {{ ansible_os_family }}"
          - "The operating system is {{ ansible_distribution }}"
          - "The operating system major version is {{ ansible_distribution_major_version }}"
    - name: Install all security, critical, and rollup updates without a scheduled task
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
          - UpdateRollups
```

RUn the above playbook from Ansible version 2.16.2 on Windows 2022 server when Trellix agent installed and threat prrevetion enabled and playbook is faild with below error

```
PLAY RECAP *********************************************************************
windows 2022 server : ok=2 changed=0 unreachable=0 failed=1 skipped=0 rescued=0 ignored=0
```

I added below code as per Ansible Documentation, but still getting the same error
```yaml
become: true
become_method: runas
become_user: SYSTEM
```

##### EXPECTED RESULTS
playbook should be successful

##### ACTUAL RESULTS
```
The full traceback is:
Traceback (most recent call last):
  File "/somefolder/.local/.local/lib/python3.11/site-packages/ansible_collections/ansible/windows/plugins/action/win_updates.py", line 679, in run
    result = self._run_sync(task_vars, module_options, reboot, reboot_timeout)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/somefolder/.local/.local/lib/python3.11/site-packages/ansible_collections/ansible/windows/plugins/action/win_updates.py", line 752, in _run_sync
    update_result = self._run_updates(task_vars, module_options)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/somefolder/.local/.local/lib/python3.11/site-packages/ansible_collections/ansible/windows/plugins/action/win_updates.py", line 848, in _run_updates
    start_result = self._execute_win_updates(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/somefolder/.local/.local/lib/python3.11/site-packages/ansible_collections/ansible/windows/plugins/action/win_updates.py", line 946, in _execute_win_updates
    raise _ReturnResultException(msg, exception=result.get('exception', None), **extra_result)
ansible_collections.ansible.windows.plugins.action.win_updates._ReturnResultException: MODULE FAILURE
See stdout/stderr for the exact error
fatal: [windows 2022 server]: FAILED! => {
    "changed": false,
    "failed_update_count": 0,
    "filtered_updates": {},
    "found_update_count": 0,
    "installed_update_count": 0,
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 0,
    "updates": {}
}
            
PLAY RECAP *********************************************************************
windows 2022 server : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
```
