### ISSUE TITLE
Error in win_stat when fetching a file with brackets [] in the name

### ISSUE THREAD

**Issue by cruscio** [ansible-collections/ansible.windows#640]
##### SUMMARY
When fetching (`ansible.builtin.fetch`) a file from Windows, `ansible.windows.win_stat` throws an error and fails if the filename has brackets `[]` in it (and presumably other special characters that affect PowerShell parsing but are valid characters for the filesystem).

I'm trying to fetch the logs from an installer that runs scripts into a SQL Server. The installer creates a log file for each table it imports into, and the file names have brackets around the SQL object names that are part of the filename. For example: `import_[databasename].[schema].[table]_SQLCMD.log`

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ansible.builtin.fetch
ansible.windows.win_stat

##### ANSIBLE VERSION

```paste below
ansible [core 2.17.2]
  config file = /home/cruscio/code/myproject/ansible/ansible.cfg
  configured module search path = ['/home/cruscio/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/cruscio/.local/pipx/venvs/ansible/lib/python3.11/site-packages/ansible
  ansible collection location = /home/cruscio/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/cruscio/.local/bin/ansible
  python version = 3.11.2 (main, May  2 2024, 11:59:08) [GCC 12.2.0] (/home/cruscio/.local/pipx/venvs/ansible/bin/python)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```paste below
# /home/cruscio/.local/pipx/venvs/ansible/lib/python3.11/site-packages/ansible_collections
Collection      Version
--------------- -------
ansible.windows 2.4.0  
```

##### CONFIGURATION

```paste below
CALLBACKS_ENABLED(/home/cruscio/code/myproject/ansible/ansible.cfg) = ['unixy']
CONFIG_FILE() = /home/cruscio/code/myproject/ansible/ansible.cfg
DEFAULT_BECOME_METHOD(/home/cruscio/code/myproject/ansible/ansible.cfg) = runas
DEFAULT_HOST_LIST(/home/cruscio/code/myproject/ansible/ansible.cfg) = ['/home/cruscio/code/myproject/ansible/inventory']
DEFAULT_LOG_PATH(/home/cruscio/code/myproject/ansible/ansible.cfg) = /home/cruscio/code/myproject/ansible/log
DEFAULT_LOOKUP_PLUGIN_PATH(/home/cruscio/code/myproject/ansible/ansible.cfg) = ['/usr/share/ansible/plugins/lookup']
DEFAULT_STDOUT_CALLBACK(/home/cruscio/code/myproject/ansible/ansible.cfg) = yaml
EDITOR(env: EDITOR) = nano
PAGER(env: PAGER) = less
```

##### OS / ENVIRONMENT

Windows Server 2019 and 2022 (presumably any Windows version)

##### STEPS TO REPRODUCE

Run the playbook targeting a Windows node

```yaml
- name: Fail to fetch files from Windows server
  hosts: all
  gather_facts: false
  tasks:

    - name: Powershell - create a directory and a file with brackets in the name
      ansible.windows.win_file:
        path: '{{ item.name }}'
        state: '{{ item.type }}'
      loop:
        - name: C:\ansible_fetch
          type: directory
        - name: C:\ansible_fetch\import_databasename.schema.table_SQLCMD.log
          type: touch
        - name: C:\ansible_fetch\import_[databasename].[schema].[table]_SQLCMD.log
          type: touch

    - name: Find all files
      ansible.windows.win_find:
        paths: 'C:\ansible_fetch'
      register: found_files

    - name: Debug - list found files
      ansible.builtin.debug:
        var: found_files

    - name: Fetch found files (causes an error)
      ansible.builtin.fetch:
        src: '{{ item.path }}'
        dest: '/tmp/ansible_fetch'
        flat: false
      loop: '{{ found_files.files | reverse }}'
      # Reveresed to show the file without brackets is getting fetched as expected

    - name: Cleanup temporary files
      ansible.windows.win_shell: Remove-Item -Path 'C:\ansible_fetch' -Recurse -Force

```

##### EXPECTED RESULTS

There should be two files fetched into `/tmp/ansible_fetch` on the controller

##### ACTUAL RESULTS

One file is fetched, the other causes an error

```paste below
PLAY [Fetch files recursively from Windows server] ***************************

TASK [Powershell - create a directory and a file with brackets in the name] **
ok: [machinenamehere] => (item={'name': 'C:\\ansible_fetch', 'type': 'directory'})
changed: [machinenamehere] => (item={'name': 'C:\\ansible_fetch\\import_databasename.schema.table_SQLCMD.log', 'type': 'touch'})
changed: [machinenamehere] => (item={'name': 'C:\\ansible_fetch\\import_[databasename].[schema].[table]_SQLCMD.log', 'type': 'touch'})

TASK [Find all files and directories recursively] ****************************
ok: [machinenamehere]

TASK [Debug - list found files] **********************************************
ok: [machinenamehere] =>
  found_files:
    changed: false
    examined: 2
    failed: false
    files:
    - attributes: Archive
      checksum: da39a3ee5e6b4b0d3255bfef95601890afd80709
      creationtime: 1723111691.2282472
      exists: true
      extension: .log
      filename: import_[databasename].[schema].[table]_SQLCMD.log
      hlnk_targets: []
      isarchive: true
      isdir: false
      ishidden: false
      isjunction: false
      islnk: false
      isreadonly: false
      isreg: true
      isshared: false
      lastaccesstime: 1723111691.2282472
      lastwritetime: 1723112105.3833928
      lnk_source: null
      lnk_target: null
      nlink: 1
      owner: BUILTIN\Administrators
      path: C:\ansible_fetch\import_[databasename].[schema].[table]_SQLCMD.log
      sharename: null
      size: 0
    - attributes: Archive
      checksum: da39a3ee5e6b4b0d3255bfef95601890afd80709
      creationtime: 1723111691.0563717
      exists: true
      extension: .log
      filename: import_databasename.schema.table_SQLCMD.log
      hlnk_targets: []
      isarchive: true
      isdir: false
      ishidden: false
      isjunction: false
      islnk: false
      isreadonly: false
      isreg: true
      isshared: false
      lastaccesstime: 1723111691.0563717
      lastwritetime: 1723112105.149017
      lnk_source: null
      lnk_target: null
      nlink: 1
      owner: BUILTIN\Administrators
      path: C:\ansible_fetch\import_databasename.schema.table_SQLCMD.log
      sharename: null
      size: 0
    matched: 2

TASK [Fetch found files (causes an error)] ***********************************
changed: [machinenamehere] => (item={'path': 'C:\\ansible_fetch\\import_databasename.schema.table_SQLCMD.log', 'extension': '.log', 'filename': 'import_databasename.schema.table_SQLCMD.log', 'creationtime': 1723111691.0563717, 'checksum': 'da39a3ee5e6b4b0d3255bfef95601890afd80709', 'size': 0, 'isreadonly': False, 'attributes': 'Archive', 'lastaccesstime': 1723111691.0563717, 'isreg': True, 'isjunction': False, 'islnk': False, 'isarchive': True, 'lastwritetime': 1723112105.149017, 'nlink': 1, 'isshared': False, 'ishidden': False, 'exists': True, 'isdir': False, 'lnk_target': None, 'sharename': None, 'hlnk_targets': [], 'lnk_source': None, 'owner': 'BUILTIN\\Administrators'})
fatal: [machinenamehere]: FAILED! =>
  msg: |-
    failed to setup file stream for fetch '/tmp/ansible_fetch/machinenamehere/C:/ansible_fetch/import_[databasename].[schema].[table]_SQLCMD.log': C:\ansible_fetch\import_[databasename].[schema].[table]_SQLCMD.log does not exist
        + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
        + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException
```

With debugging on
```
TASK [Fetch found files (causes an error)] *************************************
task path: /home/cruscio/code/myproject/ansible/debug.yml:27
Using module file /home/cruscio/.local/pipx/venvs/ansible/lib/python3.11/site-packages/ansible_collections/ansible/windows/plugins/modules/win_stat.ps1
Pipelining is enabled.
<machinenamehere> ESTABLISH PSRP CONNECTION FOR USER: ***** ON PORT 5986 TO machinenamehere
PSRP: EXEC (via pipeline wrapper)
ok: [machinenamehere] => (item={'path': 'C:\\ansible_fetch\\import_databasename.schema.table_SQLCMD.log', 'extension': '.log', 'filename': 'import_databasename.schema.table_SQLCMD.log', 'creationtime': 1723111691.0563717, 'checksum': 'da39a3ee5e6b4b0d3255bfef95601890afd80709', 'size': 0, 'isreadonly': False, 'attributes': 'Archive', 'lastaccesstime': 1723111691.0563717, 'isreg': True, 'isjunction': False, 'islnk': False, 'isarchive': True, 'lastwritetime': 1723112423.3720267, 'nlink': 1, 'isshared': False, 'ishidden': False, 'exists': True, 'isdir': False, 'lnk_target': None, 'sharename': None, 'hlnk_targets': [], 'lnk_source': None, 'owner': 'BUILTIN\\Administrators'}) => changed=false 
  ansible_loop_var: item
  checksum: da39a3ee5e6b4b0d3255bfef95601890afd80709
  dest: /tmp/ansible_fetch/machinenamehere/C:/ansible_fetch/import_databasename.schema.table_SQLCMD.log
  file: C:\ansible_fetch\import_databasename.schema.table_SQLCMD.log
  item:
    attributes: Archive
    checksum: da39a3ee5e6b4b0d3255bfef95601890afd80709
    creationtime: 1723111691.0563717
    exists: true
    extension: .log
    filename: import_databasename.schema.table_SQLCMD.log
    hlnk_targets: []
    isarchive: true
    isdir: false
    ishidden: false
    isjunction: false
    islnk: false
    isreadonly: false
    isreg: true
    isshared: false
    lastaccesstime: 1723111691.0563717
    lastwritetime: 1723112423.3720267
    lnk_source: null
    lnk_target: null
    nlink: 1
    owner: BUILTIN\Administrators
    path: C:\ansible_fetch\import_databasename.schema.table_SQLCMD.log
    sharename: null
    size: 0
  md5sum: d41d8cd98f00b204e9800998ecf8427e
Using module file /home/cruscio/.local/pipx/venvs/ansible/lib/python3.11/site-packages/ansible_collections/ansible/windows/plugins/modules/win_stat.ps1
Pipelining is enabled.
PSRP: EXEC (via pipeline wrapper)
<machinenamehere> FETCH C:\ansible_fetch\import_[databasename].[schema].[table]_SQLCMD.log TO /tmp/ansible_fetch/machinenamehere/C:/ansible_fetch/import_[databasename].[schema].[table]_SQLCMD.log
fatal: [machinenamehere]: FAILED! => 
  msg: |-
    failed to setup file stream for fetch '/tmp/ansible_fetch/machinenamehere/C:/ansible_fetch/import_[databasename].[schema].[table]_SQLCMD.log': C:\ansible_fetch\import_[databasename].[schema].[table]_SQLCMD.log does not exist
        + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
        + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException
    StackTrace:
    at <ScriptBlock>, <No file>: line 15
    ```
