### ISSUE TITLE
Allow win_package to accept multiple product_id's

### ISSUE THREAD

**Issue by edison-moreland** [ansible-collections/ansible.windows#65]
##### SUMMARY
Some .exe installers bundle multiple packages. I'd like to be able to specify multiple product_id's when using the win_package.

[Originally submitted](https://github.com/ansible/ansible/issues/70031) on Ansible repo, was asked to move here.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
win_package

##### ADDITIONAL INFORMATION
I've been working through automating our windows infrastructure with Ansible and I've come across a few installers, like SophosAV and [.Net SDKs](https://dotnet.microsoft.com/download/visual-studio-sdks), that install several product_id's. Currently I just use one of the product_id's. It'd be nice to add all of them so if just one is missing it re-runs the installer.

```yaml
- name: Install .NET 4.5.2
  win_package:
    path: "NDP452-KB2901951-x86-x64-DevPack.exe"
    product_id:
    - "{290FC320-2F5A-329E-8840-C4193BD7A9EE}"
    - "{19E8AE59-4D4A-3534-B567-6CC08FA4102E}"
    arguments:
      - /q
      - /norestart
```

**Comment by jborean93** [comment]
I'm not sure if this would be a good idea, especially if one id is missing but others are present reinstalling the executable might bring it into a bad state. It's also possible today to do this with a loop, admittedly there is a bit more overhead in this method:

```yaml
- name: Install .NET 4.5.2
  win_package:
    path: "NDP452-KB2901951-x86-x64-DevPack.exe"
    product_id: '{{ item }}'
    arguments:
      - /q
      - /norestart
  loop:
  - "{290FC320-2F5A-329E-8840-C4193BD7A9EE}"
  - "{19E8AE59-4D4A-3534-B567-6CC08FA4102E}"
```

Because of the limited use case and the fact that it is somewhat possible today I think we will have to say no thanks to this feature request.
