### ISSUE TITLE
RFE: Support for managing Windows Capabilities

### ISSUE THREAD

**Issue by myllynen** [ansible-collections/ansible.windows#660]
##### SUMMARY
Recent Windows Server versions allow for adding, querying, and removing Windows capabilities which are separate from features, optional features, and packages. For example, to check the installation status of OpenSSH SSH Server (sshd) on Windows Server 2022 and install it if not installed already one could do:

```yaml
if (Get-WindowsCapability -Name OpenSSH.Server -Online | ? State -ne 'Installed') {
  Add-WindowsCapability -Name OpenSSH.Server -Online
}
```

It would be helpful if there would be an Ansible Windows module available to do this without the need for writing PowerShell.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
win_capability

##### ADDITIONAL INFORMATION
The Add-WindowsCapability, Get-WindowsCapability, and Remove-WindowsCapability PowerShell cmdlets seem to use Dism.exe. While the aforementioned example works as expected on Windows Server 2022 it doesn't seem to do anything on Windows 10. Also, when trying to install other capabilities such as languages the results seem inconsistent, I haven't been able to handle them reliably even if similar language enablement using Settings works as expected. Meaning that if creating this kind of module it should verify the outcome to the extent possible.

```
- name: Install OpenSSH SSH server (sshd)
  ansible.windows.win_capability:
    name: OpenSSH.Server
    state: present
  register: install_status

- name: Remove Azure Arc client setup
  ansible.windows.win_capability:
    name: AzureArcSetup
    state: absent
  register: remove_status

- name: Check available Windows Capabilities
  ansible.windows.win_capability:
    state: available
  register: available_capabilities

- name: Check already installed Windows Capabilities
  ansible.windows.win_capability:
    state: installed
  register: installed_capabilities
```
