### ISSUE TITLE
Powershell script (windows.win_powershell) where parameters are not being passed through to the script

### ISSUE THREAD

**Issue by sjanssen15** [ansible-collections/ansible.windows#664]
##### SUMMARY
When running a Powershell script with the module ansible.windows.win_powershell + Parameters (see second example on the docs website) I get no passthrough of the parameter.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
ansible.windows.win_powershell

##### ANSIBLE VERSION

```paste below
ansible-playbook [core 2.16.3]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/xxxx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.12/site-packages/ansible
  ansible collection location = /home/xxxx/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible-playbook
  python version = 3.12.5 (main, Aug 26 2024, 10:40:21) [GCC 8.5.0 20210514 (Red Hat 8.5.0-22)] (/usr/bin/python3.12)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```paste below
ansible-galaxy collection list ansible.windows

# /usr/lib/python3.12/site-packages/ansible_collections
Collection      Version
--------------- -------
ansible.windows 2.2.0  
```

##### CONFIGURATION

```paste below
ansible-config dump --only-changed
CONFIG_FILE() = /etc/ansible/ansible.cfg
```

##### OS / ENVIRONMENT

OS: Red Hat Enterprise Linux 8.10
Kernel: 4.18.0-553.22.1.el8_10.x86_64

##### STEPS TO REPRODUCE

Running the following Playbook to a Windows Server 2022 standard host via WinRM with Kerberos auth.

```yaml
---
- name: Test Windows Ansible playbook
  hosts: all
  tasks:
    - name: Test script
      ansible.windows.win_powershell:
        script: |
          Write-Host $Path
        parameters:
          Path: C:\temp
      register: script

    - name: debug
      debug:
        msg: "{{ script }}"
```

##### EXPECTED RESULTS

The parameter to be passed on to the script and being usable in the script.

##### ACTUAL RESULTS

Output shows the empty parameter output. This is the same task as the second example in the examples on the Ansible docs: https://docs.ansible.com/ansible/latest/collections/ansible/windows/win_powershell_module.html
```paste below
PLAY [Test Windows Ansible playbook] **************************************************************************************************************************************************************

TASK [Gathering Facts] ****************************************************************************************************************************************************************************
ok: [SERVER]

TASK [Test script] ********************************************************************************************************************************************************************************
changed: [SERVER]

TASK [debug] **************************************************************************************************************************************************************************************
ok: [SERVER] => 
  msg:
    changed: true
    debug: []
    error: []
    failed: false
    host_err: ''
    host_out: ""
    information:
    - message_data:
        BackgroundColor: null
        ForegroundColor: null
        Message: ''
        NoNewLine: false
      source: Write-Host
      tags:
      - PSHOST
      time_generated: '2024-10-10T13:07:56.9684666Z'
    output: []
    result: {}
    verbose: []
    warning: []

PLAY RECAP ****************************************************************************************************************************************************************************************
SERVER        : ok=3    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```

**Comment by jborean93** [comment]
The `parameters` option just sets the parameters when calling the `script`, you still need to specify the `param` block to map those parameters or access them through `$args`. In your example you just want to add `param($Path)` to the top of the script being run and it will be able to access the parameter you specified.

```yaml
    - name: Test script
      ansible.windows.win_powershell:
        script: |
          param($Path)

          Write-Host $Path
        parameters:
          Path: C:\temp
      register: script

```
