### ISSUE TITLE
Win_Package uninstallation will exit without doing anything when path is pointing to a URL

### ISSUE THREAD

**Issue by yangxinyun** [ansible-collections/ansible.windows#667]
##### SUMMARY

When win_package path argument is pointing to a URL and state argument is set to absent, this module will exit without doing uninstallation via downloading the URL specified software package and issue uninstall command as per the arguments
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

win_package
##### ANSIBLE VERSION

```paste below
ansible-core 2.11
```

##### COLLECTION VERSION

```paste below
Ansible.Windows version 2.5.0
```

##### CONFIGURATION

```paste below
NA
```

##### OS / ENVIRONMENT

RedHat Linux

##### STEPS TO REPRODUCE

```yaml
- name: Uninstall python 
  ansible.windows.win_package:
    path: https://www.python.org/ftp/python/3.11.0/python-3.11.0-amd64.exe
    arguments:
      - /uninstall
      - /quiet
     state: absent

```

##### EXPECTED RESULTS

python installed by https://www.python.org/ftp/python/3.11.0/python-3.11.0-amd64.exe is removed accordingly.

##### ACTUAL RESULTS

```paste below
nothing happened, the module exit without any change
```
