### ISSUE TITLE
win_git_config: Add support

### ISSUE THREAD

**Issue by mathstuf** [ansible-collections/ansible.windows#669]
##### SUMMARY
Port `community.general.git_config` to Windows.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
`win_git_config`

##### ADDITIONAL INFORMATION
As with `git_config`, using a command is error-prone and doesn't support `check` very well.

```yaml
- name: Set `core.longpaths`
  become: true
  become_method: runas
  become_flags: logon_flags=with_profile
  ansible.windows.win_git_config:
    name: core.longpaths
    scope: "file"
    file: "c:/Users/{{ gitlab_runner_user }}/.gitconfig"
    value: "true"
  vars:
    ansible_become_user: '{{ gitlab_runner_user }}'
    ansible_become_pass: '{{ windows_svc_user_passwd }}'
```
