### ISSUE TITLE
module.win_group_membership The state present is not idempotent and crash with "name is already member of the group"

### ISSUE THREAD

**Issue by gillg** [ansible-collections/ansible.windows#736]
##### SUMMARY
When using that module and `state: present` it fails if a group member is already present.
When using `state: pure` it works, but it's not the bahaviour I'm searching for.
```
{
  "changed": true,
  "msg": "Exception calling \"Add\" with \"1\" argument(s): \"The specified account name is already a member of the group.\r\n\"",
  "name": "DBAdmin",
  "added": [
    "XXX-E-EUW1-DATA\\Administrator",
    "XXX-E-EUW1-DATA\\user1",
    "XXX-E-EUW1-DATA\\user2",
    "XXX-E-EUW1-DATA\\ITAdmin",
    "XXX-E-EUW1-DATA\\OnCall",
    "XXX-E-EUW1-DATA\\Operations",
    "XXX-E-EUW1-DATA\\ansible",
  ],
  "_ansible_no_log": false
}
```

As an example `XXX-E-EUW1-DATA\\ITAdmin` being a user group, it could be part of the problem... ?

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
win_group_membership 

##### ANSIBLE VERSION

```paste below
2.12.5
```

##### COLLECTION VERSION

```paste below
2.2.0
```

##### OS / ENVIRONMENT
Windows server 2019

##### STEPS TO REPRODUCE

```yaml
- name: Discover all members of Administrators group
  ansible.windows.win_powershell:
    script: |
      [CmdletBinding(SupportsShouldProcess)] # This is vital to run the task even in check mode
      param ()

      $Ansible.result.all_admins = (Get-LocalGroupMember -Group Administrators -ErrorAction SilentlyContinue).Name
      $Ansible.changed = $False
  register: _users_list

- name: Add all builtin Administrators to the DB Admin group
  ansible.windows.win_group_membership:
    name: "DBAdmin"
    members: "{{ _users_list.result.all_admins | ansible.builtin.union([ansible_user]) }}"
```

##### EXPECTED RESULTS
No error; idempotent add or nothing

##### ACTUAL RESULTS
fails with native low level error
