### ISSUE TITLE
[windows.powershell] Server not found in Kerberos database

### ISSUE THREAD

**Issue by davidkim2010** [ansible-collections/ansible.windows#754]
##### SUMMARY

The following codes fail with this error:  Unexpected failure during module execution: SpnegoError (4294967295): Major (851968): Unspecified GSS failure.  Minor code may provide more information, Minor (2529638919): Server not found in Kerberos database, Context: Processing security token"

```
- name: Add abc. to in-memory inventory
  add_host:
    name: '{{ remote_host }}'
    ansible_connection: psrp #winrm #'{{ connection_temp }}'
    ansible_port: 5985 #'{{ port_temp }}'
    ansible_psrp_auth: "{{ winrm_transport_temp }}"
    ansible_winrm_server_cert_validation: ignore
    ansible_user: "{{ admin_userid }}"
    ansible_password: "{{ admin_userid_pwd }}"
    ansible_psrp_connection_timeout: 65
    ansible_psrp_operation_timeout: 60 
    ansible_psrp_read_timeout: 80


- name: Run PowerShell script remotely to configure iscsi disk
  register: pwsh_out
  delegate_to: '{{ remote_host }}'
  ansible.windows.win_powershell:
    error_action: stop
    # executable: powershell.exe
    script: "{{ lookup('ansible.builtin.template', 'config_iscsi_v2.ps1') }}"
    parameters:
      ClientHost: '{{ClientHost}}'
      PrimaryTargetIPAddress: '{{ ret_iscsi_win_primary_target_ip }}'
      TargetIPList: '{{ iscsi_targets }}' #'{{ret_iscsi_win_target_IP_list}}'
      DriveLetter: '{{ StorageJson.MountPoint }}' #'{{ t_drive_letter }}'
      iqn: "{{ iscsi_initiator }}" 
      LunSerialNum: '{{ lun_serial_num }}' #'{{ normalized_lun_serial_num }}' 
      TargetNodeAddress: '{{ iscsi_node_name }}' 
      Operation: '{{ storage_operation }}' #create
```
#### Exception
"Traceback (most recent call last):\n  File \"/usr/local/lib/python3.9/site-packages/spnego/_context.py\", line 68, in wrapper\n    return func(*args, **kwargs)\n  File \"/usr/local/lib/python3.9/site-packages/spnego/_gss.py\", line 431, in step\n    out_token = self._context.step(in_token)\n  File \"/usr/local/lib/python3.9/site-packages/decorator.py\", line 232, in fun\n    return caller(func, *(extras + args), **kw)\n  File \"/usr/local/lib64/python3.9/site-packages/gssapi/_utils.py\", line 165, in check_last_err\n    return func(self, *args, **kwargs)\n  File \"/usr/local/lib/python3.9/site-packages/decorator.py\", line 232, in fun\n    return caller(func, *(extras + args), **kw)\n  File \"/usr/local/lib64/python3.9/site-packages/gssapi/_utils.py\", line 131, in catch_and_return_token\n    return func(self, *args, **kwargs)\n  File \"/usr/local/lib64/python3.9/site-packages/gssapi/sec_contexts.py\", line 584, in step\n    return self._initiator_step(token=token)\n  File \"/usr/local/lib64/python3.9/site-packages/gssapi/sec_contexts.py\", line 606, in _initiator_step\n    res = rsec_contexts.init_sec_context(self._target_name, self._creds,\n  File \"gssapi/raw/sec_contexts.pyx\", line 188, in gssapi.raw.sec_contexts.init_sec_context\ngssapi.raw.misc.GSSError: Major (851968): Unspecified GSS failure.  Minor code may provide more information, Minor (2529638919): Server not found in Kerberos database\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/usr/lib/python3.9/site-packages/ansible/executor/task_executor.py\", line 165, in run\n    res = self._execute()\n  File \"/usr/lib/python3.9/site-packages/ansible/executor/task_executor.py\", line 660, in _execute\n    result = self._handler.run(task_vars=vars_copy)\n  File \"/usr/lib/python3.9/site-packages/ansible/plugins/action/normal.py\", line 39, in run\n    result = merge_hash(result, self._execute_module(task_vars=task_vars, wrap_async=wrap_async))\n  File \"/usr/lib/python3.9/site-packages/ansible/plugins/action/__init__.py\", line 1179, in _execute_module\n    res = self._low_level_execute_command(cmd, sudoable=sudoable, in_data=in_data)\n  File \"/usr/lib/python3.9/site-packages/ansible/plugins/action/__init__.py\", line 1344, in _low_level_execute_command\n    rc, stdout, stderr = self._connection.exec_command(cmd, in_data=in_data, sudoable=sudoable)\n  File \"/usr/lib/python3.9/site-packages/ansible/plugins/connection/psrp.py\", line 428, in exec_command\n    super(Connection, self).exec_command(cmd, in_data=in_data,\n  File \"/usr/lib/python3.9/site-packages/ansible/plugins/connection/__init__.py\", line 35, in wrapped\n    self._connect()\n  File \"/usr/lib/python3.9/site-packages/ansible/plugins/connection/psrp.py\", line 392, in _connect\n    self.runspace.open()\n  File \"/usr/local/lib/python3.9/site-packages/pypsrp/powershell.py\", line 548, in open\n    self.shell.open(options, open_content)\n  File \"/usr/local/lib/python3.9/site-packages/pypsrp/shell.py\", line 205, in open\n    response = self.wsman.create(self.resource_uri, shell, option_set=options if len(options.values) else None)\n  File \"/usr/local/lib/python3.9/site-packages/pypsrp/wsman.py\", line 290, in create\n    res = self.invoke(WSManAction.CREATE, resource_uri, resource, option_set, selector_set, timeout)\n  File \"/usr/local/lib/python3.9/site-packages/pypsrp/wsman.py\", line 470, in invoke\n    response = self.transport.send(xml)\n  File \"/usr/local/lib/python3.9/site-packages/pypsrp/wsman.py\", line 803, in send\n    self._send_request(prep_request)\n  File \"/usr/local/lib/python3.9/site-packages/pypsrp/wsman.py\", line 840, in _send_request\n    response = self.session.send(request, timeout=(self.connection_timeout, self.read_timeout))  # type: ignore[union-attr] # This should not happen\n  File \"/usr/lib/python3.9/site-packages/requests/sessions.py\", line 664, in send\n    r = dispatch_hook('response', hooks, r, **kwargs)\n  File \"/usr/lib/python3.9/site-packages/requests/hooks.py\", line 31, in dispatch_hook\n    _hook_data = hook(hook_data, **kwargs)\n  File \"/usr/local/lib/python3.9/site-packages/pypsrp/negotiate.py\", line 96, in response_hook\n    response = self.handle_401(response, **kwargs)\n  File \"/usr/local/lib/python3.9/site-packages/pypsrp/negotiate.py\", line 141, in handle_401\n    out_token = context.step()\n  File \"/usr/local/lib/python3.9/site-packages/spnego/_context.py\", line 71, in wrapper\n    raise SpnegoError(base_error=native_err, context_msg=context) from native_err\nspnego.exceptions.SpnegoError: SpnegoError (4294967295): Major (851968): Unspecified GSS failure.  Minor code may provide more information, Minor (2529638919): Server not found in Kerberos database, Context: Processing security token\n",

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
ansible [core 2.15.8]
```

##### COLLECTION VERSION

```paste below
 4│      amazon.aws: 9.1.0
 5│      ansible.netcommon: 7.1.0
 6│      ansible.posix: 2.0.0
 7│      ansible.utils: 5.1.2
 8│      ansible.windows: 2.6.0
 9│      awx.awx: 24.6.1
10│      azure.azcollection: 3.1.0
11│      cisco.aci: 2.4.0
12│      community.aws: 9.0.0
13│      community.crypto: 2.15.1
14│      community.dns: 3.1.1
15│      community.general: 10.2.0
16│      community.library_inventory_filtering_v1: 1.0.2
17│      community.network: 5.0.0
18│      community.postgresql: 3.9.1
19│      community.vmware: 4.4.0
20│      community.windows: 2.3.0
21│      cyberark.pas: 1.0.27
22│      infoblox.nios_modules: 1.7.1
23│      netapp.ontap: 22.13.0
24│      oracle.oci: 5.3.0
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Red Hat Enterprise Linux 8.9 (Ootpa)

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```paste below

```
