### ISSUE TITLE
win_acl fails on a path using environment variable that succeeds in win_file

### ISSUE THREAD

**Issue by oboudry-mvp** [ansible-collections/ansible.windows#757]
##### SUMMARY
In an ansible role, I'm using `win_file` followed by `win_acl` on path `'%programfiles(x86)%\APS\Strategic\Bin'` containing an environment variable.

Also both commands use the exact same path, the `win_file` one succeeds, but the `win_acl` fails with error message: `"%programfiles(x86)%\\APS\\Strategic\\Bin file or directory does not exist on the host"`

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
win_acl

##### ANSIBLE VERSION

```paste below
ansible [core 2.18.2]
  config file = None
  configured module search path = ['/home/olivier/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /mnt/c/Users/olivier.boudry/Downloads/windows-awx/.venv/lib/python3.12/site-packages/ansible
  ansible collection location = /home/olivier/.ansible/collections:/usr/share/ansible/collections
  executable location = /mnt/c/Users/olivier.boudry/Downloads/windows-awx/.venv/bin/ansible
  python version = 3.12.3 (main, Jan 17 2025, 18:03:48) [GCC 13.3.0] (/mnt/c/Users/olivier.boudry/Downloads/windows-awx/.venv/bin/python3)
  jinja version = 3.1.5
  libyaml = True
```

##### COLLECTION VERSION

```paste below
# /mnt/c/Users/olivier.boudry/Downloads/windows-awx/.venv/lib/python3.12/site-packages/ansible_collections
ansible.windows                          2.7.0
community.windows                        2.3.0
```

##### CONFIGURATION

```paste below
CONFIG_FILE() = None

GALAXY_SERVERS:
```

##### OS / ENVIRONMENT

Windows 11 Business 24H2

##### STEPS TO REPRODUCE

Create a role containing the following two tasks

```
- name: Strategic Bin dir exists
  win_file:
    path: '%programfiles(x86)%\APS\Strategic\Bin'
    state: directory

- name: Users group has FullControl on Strategic Bin dir
  win_acl:
    path: '%programfiles(x86)%\APS\Strategic\Bin'
    user: Users
    type: allow
    state: present
    rights: FullControl
```

Apply this role to a single Windows computer:

```
ansible-playbook -i "MVP-PF26X6RH.intranet-mvp.ch," -e "target_hosts=MVP-PF26X6RH.intranet-mvp.ch," -u admin_user@intranet-mvp.ch --ask-pass --extra-vars="ansible_connection=winrm ansible_winrm_transport=ntlm ansible_winrm_port=5985" -vvv --tag strategic ch_workstation.yml
```

##### EXPECTED RESULTS
Success for both tasks

##### ACTUAL RESULTS
Second task fails saying path does not exists, also it is the exact same path as the previous task is using

```paste below
TASK [common : Strategic Bin dir exists] ******************************************************************************************************************************************************************************************
task path: /mnt/c/Users/olivier.boudry/Downloads/windows-awx/roles/common/tasks/strategic.yml:103
redirecting (type: modules) ansible.builtin.win_file to ansible.windows.win_file
redirecting (type: modules) ansible.builtin.win_file to ansible.windows.win_file
Using module file /mnt/c/Users/olivier.boudry/Downloads/windows-awx/.venv/lib/python3.12/site-packages/ansible_collections/ansible/windows/plugins/modules/win_file.ps1
Pipelining is enabled.
<MVP-PF26X6RH.intranet-mvp.ch> ESTABLISH WINRM CONNECTION FOR USER: a-olibou@intranet-mvp.ch on PORT 5985 TO MVP-PF26X6RH.intranet-mvp.ch
EXEC (via pipeline wrapper)
ok: [MVP-PF26X6RH.intranet-mvp.ch] => {
    "changed": false
}

TASK [common : Users group has FullControl on Strategic Bin dir] ******************************************************************************************************************************************************************
task path: /mnt/c/Users/olivier.boudry/Downloads/windows-awx/roles/common/tasks/strategic.yml:108
redirecting (type: modules) ansible.builtin.win_acl to ansible.windows.win_acl
redirecting (type: modules) ansible.builtin.win_acl to ansible.windows.win_acl
Using module file /mnt/c/Users/olivier.boudry/Downloads/windows-awx/.venv/lib/python3.12/site-packages/ansible_collections/ansible/windows/plugins/modules/win_acl.ps1
Pipelining is enabled.
<MVP-PF26X6RH.intranet-mvp.ch> ESTABLISH WINRM CONNECTION FOR USER: a-olibou@intranet-mvp.ch on PORT 5985 TO MVP-PF26X6RH.intranet-mvp.ch
EXEC (via pipeline wrapper)
fatal: [MVP-PF26X6RH.intranet-mvp.ch]: FAILED! => {
    "changed": false,
    "msg": "%programfiles(x86)%\\APS\\Strategic\\Bin file or directory does not exist on the host"
}

PLAY RECAP ************************************************************************************************************************************************************************************************************************
MVP-PF26X6RH.intranet-mvp.ch : ok=14   changed=2    unreachable=0    failed=1    skipped=3    rescued=0    ignored=0
```

**Comment by jborean93** [comment]
I know it is not consistent but some modules accept a path like value and others are just a string. You can see that [win_file's path](https://docs.ansible.com/ansible/latest/collections/ansible/windows/win_file_module.html#parameter-path) has a type of `path` whereas [win_acl's path](https://docs.ansible.com/ansible/latest/collections/ansible/windows/win_acl_module.html#parameter-path) has a type of string.

We started moving some across to `path` to support env vars like this but stopped because:

+ You can no longer specify a path that has `%...%` in some form (`C:\Windows\%foo%` is a perfectly valid path)
+ We couldn't remove the ones already supporting `path` because that would be a breaking change

That's why there are different behaviours here. In any case you can pretty much guarantee that this path is going to be `C:\Program Files (x86)` which will work in both situations.

**Comment by oboudry-mvp** [comment]
OK, I was wondering if it was by design or an issue. I solved it by querying the path value in PowerShell for now. If there is no plan to change this because of % being a legit path character, then I'll close this issue.

```yaml
- name: Get the name of the group by SID
  ansible.windows.win_powershell:
    script: |
      Get-LocalGroup -SID S-1-5-32-545 | Select-Object -ExpandProperty Name
  register: group_name

- name: Get Program Files (x86) folder for win_acl which cannot read env variables
  ansible.windows.win_powershell:
    script: |
      ${env:ProgramFiles(x86)} + '\APS\Strategic\Bin'
  register: strategic_bin_path

- name: Users group has FullControl on Strategic Bin dir
  win_acl:
    path: '{{ strategic_bin_path.output[0] }}'
    user: "{{ group_name.output[0] }}"
    type: allow
    state: present
    rights: FullControl
```

Thanks for the quick reply.
