### ISSUE TITLE
win_acl potential bug with audit inheritance

### ISSUE THREAD

**Issue by markatdxb** [ansible-collections/ansible.windows#761]
##### SUMMARY

in my case im using 2 modules:
- win_acl_inheritance to disable inheritance on folder - this one seems to work as exptected
- win_acl - to add new user permissions 

issue is that win_acl seems to break inheritance on Audit settings for some reason

i spotted in code line 247

Try {
                    Set-ACL -LiteralPath $path -AclObject $objACL
                }
                Catch {
                    (Get-Item -LiteralPath $path).SetAccessControl($objACL)
                }

based on reading articles around there seems to be a bug with Set-ACL.  i have done some testing and SetAccessControl works as expected.

would be possible to swap above lines and make SetAccessControl as primary method ? i dont know what implication would that make just humbly suggesting ?

https://stackoverflow.com/questions/31721221/disable-inheritance-and-manually-apply-permissions-when-creating-a-folder-in-pow

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

win_acl
##### ANSIBLE VERSION

```paste below
2.17.7
```

##### COLLECTION VERSION

```paste below
ansible.windows 2.5.0
```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT

Windows 2022

##### STEPS TO REPRODUCE

```yaml
- name: Remove folder inheritance on folder {{ w_folder }}
  ansible.windows.win_acl_inheritance:
    path: "{{ w_folder }}"
    state: absent
    reorganize: false

- name: Set root folder NTFS permissions
  ansible.windows.win_acl:
    path: "{{ w_folder }}"
    user: "{{ item.g_name }}"
    rights: "{{ item.g_acl }}"
    type: allow
    state: present
  loop: "{{ fs_root_ntfs }}"
  vars:
    fs_root_ntfs:
      - g_name: Administrators
        g_acl: FullControl
      - g_name: Authenticated Users
        g_acl: ReadAndExecute,ListDirectory
```

##### EXPECTED RESULTS

access permissions added and audit permissions inheritance is enabled

##### ACTUAL RESULTS

access permissions are added but audit permissions inheritance is disabled

```paste below

```
