### ISSUE TITLE
Tasks return "Access Denied" at windows async encoded script execution.

### ISSUE THREAD

**Issue by ryanthomas-logility** [ansible-collections/ansible.windows#770]
##### SUMMARY

Tasks return "Access Denied" at windows async encoded script execution.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

async
##### ANSIBLE VERSION

```paste below
ansible [core 2.17.9]
  config file = /home/.ansible/ansible/ansible.cfg
  configured module search path = ['/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.12 (main, Feb  4 2025, 14:57:36) [GCC 11.4.0] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True
```

##### COLLECTION VERSION

```paste below
# /usr/lib/python3/dist-packages/ansible_collections
Collection      Version
--------------- -------
ansible.windows 2.5.0  

# /usr/share/ansible/collections/ansible_collections
Collection      Version
--------------- -------
ansible.windows 2.8.0  
```

##### CONFIGURATION

```paste below
BECOME_PLUGIN_PATH(/home/.ansible/ansible/ansible.cfg) = ['/usr/share/ansible/plugins/become']
COLLECTIONS_PATHS(/home/.ansible/ansible/ansible.cfg) = ['/usr/share/ansible/collections']
CONFIG_FILE() = /home/.ansible/ansible/ansible.cfg
DEFAULT_ACTION_PLUGIN_PATH(/home/.ansible/ansible/ansible.cfg) = ['/usr/share/ansible/plugins/action']
DEFAULT_CACHE_PLUGIN_PATH(/home/.ansible/ansible/ansible.cfg) = ['/usr/share/ansible/plugins/cache']
DEFAULT_CALLBACK_PLUGIN_PATH(/home/.ansible/ansible/ansible.cfg) = ['/usr/share/ansible/plugins/callback']
DEFAULT_CLICONF_PLUGIN_PATH(/home/.ansible/ansible/ansible.cfg) = ['/usr/share/ansible/plugins/cliconf']
DEFAULT_CONNECTION_PLUGIN_PATH(/home/.ansible/ansible/ansible.cfg) = ['/usr/share/ansible/plugins/connection']
DEFAULT_FILTER_PLUGIN_PATH(/home/.ansible/ansible/ansible.cfg) = ['/usr/share/ansible/plugins/filter']
DEFAULT_FORKS(/home/.ansible/ansible/ansible.cfg) = 150
DEFAULT_HOST_LIST(/home/.ansible/ansible/ansible.cfg) = ['/home/.ansible/ansible']
DEFAULT_HTTPAPI_PLUGIN_PATH(/home/.ansible/ansible/ansible.cfg) = ['/usr/share/ansible/plugins/httpapi']
DEFAULT_INVENTORY_PLUGIN_PATH(/home/.ansible/ansible/ansible.cfg) = ['/usr/share/ansible/plugins/inventory']
DEFAULT_KEEP_REMOTE_FILES(/home/.ansible/ansible/ansible.cfg) = True
DEFAULT_LOCAL_TMP(/home/.ansible/ansible/ansible.cfg) = /var/tmp/ansible/ansible-local-2023139z3wz_uni
DEFAULT_LOG_PATH(/home/.ansible/ansible/ansible.cfg) = /home/.ansible/ansible/playbooks/ansible.log
DEFAULT_LOOKUP_PLUGIN_PATH(/home/.ansible/ansible/ansible.cfg) = ['/usr/share/ansible/plugins/lookup']
DEFAULT_MODULE_PATH(/home/.ansible/ansible/ansible.cfg) = ['/usr/share/ansible/plugins/modules']
DEFAULT_MODULE_UTILS_PATH(/home/.ansible/ansible/ansible.cfg) = ['/usr/share/ansible/plugins/module_utils']
DEFAULT_NETCONF_PLUGIN_PATH(/home/.ansible/ansible/ansible.cfg) = ['/usr/share/ansible/plugins/netconf']
:...skipping...
BECOME_PLUGIN_PATH(/home/.ansible/ansible/ansible.cfg) = ['/usr/share/ansible/plugins/become']
COLLECTIONS_PATHS(/home/.ansible/ansible/ansible.cfg) = ['/usr/share/ansible/collections']
CONFIG_FILE() = /home/.ansible/ansible/ansible.cfg
DEFAULT_ACTION_PLUGIN_PATH(/home/.ansible/ansible/ansible.cfg) = ['/usr/share/ansible/plugins/action']
DEFAULT_CACHE_PLUGIN_PATH(/home/.ansible/ansible/ansible.cfg) = ['/usr/share/ansible/plugins/cache']
DEFAULT_CALLBACK_PLUGIN_PATH(/home/.ansible/ansible/ansible.cfg) = ['/usr/share/ansible/plugins/callback']
DEFAULT_CLICONF_PLUGIN_PATH(/home/.ansible/ansible/ansible.cfg) = ['/usr/share/ansible/plugins/cliconf']
DEFAULT_CONNECTION_PLUGIN_PATH(/home/.ansible/ansible/ansible.cfg) = ['/usr/share/ansible/plugins/connection']
DEFAULT_FILTER_PLUGIN_PATH(/home/.ansible/ansible/ansible.cfg) = ['/usr/share/ansible/plugins/filter']
DEFAULT_FORKS(/home/.ansible/ansible/ansible.cfg) = 150
DEFAULT_HOST_LIST(/home/.ansible/ansible/ansible.cfg) = ['/home/.ansible/ansible']
DEFAULT_HTTPAPI_PLUGIN_PATH(/home/.ansible/ansible/ansible.cfg) = ['/usr/share/ansible/plugins/httpapi']
DEFAULT_INVENTORY_PLUGIN_PATH(/home/.ansible/ansible/ansible.cfg) = ['/usr/share/ansible/plugins/inventory']
DEFAULT_KEEP_REMOTE_FILES(/home/.ansible/ansible/ansible.cfg) = True
DEFAULT_LOCAL_TMP(/home/.ansible/ansible/ansible.cfg) = /var/tmp/ansible/ansible-local-2023139z3wz_uni
DEFAULT_LOG_PATH(/home/.ansible/ansible/ansible.cfg) = /home/.ansible/ansible/playbooks/ansible.log
DEFAULT_LOOKUP_PLUGIN_PATH(/home/.ansible/ansible/ansible.cfg) = ['/usr/share/ansible/plugins/lookup']
DEFAULT_MODULE_PATH(/home/.ansible/ansible/ansible.cfg) = ['/usr/share/ansible/plugins/modules']
DEFAULT_MODULE_UTILS_PATH(/home/.ansible/ansible/ansible.cfg) = ['/usr/share/ansible/plugins/module_utils']
DEFAULT_NETCONF_PLUGIN_PATH(/home/.ansible/ansible/ansible.cfg) = ['/usr/share/ansible/plugins/netconf']
DEFAULT_NO_LOG(/home/.ansible/ansible/ansible.cfg) = False
DEFAULT_ROLES_PATH(/home/.ansible/ansible/ansible.cfg) = ['/home/.ansible/.ansible/roles', '/usr/share/ansible/roles', '/etc/ansible/roles', '/home/.ansible/ansible/playbooks/roles']
DEFAULT_STRATEGY_PLUGIN_PATH(/home/.ansible/ansible/ansible.cfg) = ['/usr/share/ansible/plugins/strategy']
DEFAULT_TERMINAL_PLUGIN_PATH(/home/.ansible/ansible/ansible.cfg) = ['/usr/share/ansible/plugins/terminal']
DEFAULT_TEST_PLUGIN_PATH(/home/.ansible/ansible/ansible.cfg) = ['/usr/share/ansible/plugins/test']
DEFAULT_VARS_PLUGIN_PATH(/home/.ansible/ansible/ansible.cfg) = ['/usr/share/ansible/plugins/vars']
DOC_FRAGMENT_PLUGIN_PATH(/home/.ansible/ansible/ansible.cfg) = ['/usr/share/ansible/plugins/doc_fragments']
GALAXY_CACHE_DIR(/home/.ansible/ansible/ansible.cfg) = /var/cache/ansible/galaxy_cache
GALAXY_TOKEN_PATH(/home/.ansible/ansible/ansible.cfg) = /etc/ansible/galaxy_token
INVENTORY_ENABLED(/home/.ansible/ansible/ansible.cfg) = ['host_list', 'script', 'auto', 'yaml', 'ini', 'toml', 'azure_rm']
PERSISTENT_CONTROL_PATH_DIR(/home/.ansible/ansible/ansible.cfg) = /var/lib/ansible/pc
```

##### OS / ENVIRONMENT

WindowsVersion WindowsBuildLabEx                       
-------------- -----------------                       
1809           17763.1.amd64fre.rs5_release.180914-1434

Host Name:                 acushnet-pa
OS Name:                   Microsoft Windows Server 2019 Datacenter
OS Version:                10.0.17763 N/A Build 17763
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Member Server
OS Build Type:             Multiprocessor Free
System Manufacturer:       Microsoft Corporation
BIOS Version:              American Megatrends Inc. 090008 , 12/7/2018
                           [01]: Microsoft Hyper-V Network Adapter

Name       InterfaceDescription                 DriverVersion  
----       --------------------                 -------------  
Ethernet 2 Microsoft Hyper-V Network Adapter #2 10.0.17763.6054

##### STEPS TO REPRODUCE

Run a synchronous task against the windows host and the task succeeds. Run a task asynchronously and the task fails. Simply changing async value to "0" allows the task to succeed. 

```yaml
tasks:
    - name: Test synchronous with win_command
      win_shell: |
        Get-ExecutionPolicy -Scope Process
      check_mode: false

    - name: Test execution policy in async mode
      win_shell: |
        whoami
      async: 120
      poll: 30
      check_mode: false
      register: whoami      

    - name: print woami
      debug:
        var: whoami.stdout_lines
```

##### EXPECTED RESULTS

I expect the task to create an asynchronous task and background task on the managed node.

##### ACTUAL RESULTS

The asynchronous task is able to authenticate, copy the temp script to C:\Users\.ansible\AppData\Local\Temp and I can see in event viewer the encoded powershell command execute. The temp files in C:\Users\.ansible\.ansible_async never get created.

* I pasted the verbose output below. 

```paste below
TASK [Test synchronous with win_command] *****************************************************************************************************************************************************************
task path: /home/rthomas/ansible/playbooks/winPing.yaml:31
redirecting (type: modules) ansible.builtin.win_shell to ansible.windows.win_shell
<10.251.98.5> ESTABLISH WINRM CONNECTION FOR USER: ACUSHNET\.ansible on PORT 5985 TO 10.251.98.5
EXEC (via pipeline wrapper)
redirecting (type: modules) ansible.builtin.win_shell to ansible.windows.win_shell
Using module file /usr/share/ansible/collections/ansible_collections/ansible/windows/plugins/modules/win_shell.ps1
<10.251.98.5> PUT "/var/tmp/ansible/ansible-local-20214327mfslebj/tmpa1og9400" TO "C:\Users\.ansible\AppData\Local\Temp\ansible-tmp-1743626639.8020928-2021471-128694565924195\AnsiballZ_win_shell.ps1"
EXEC (via pipeline wrapper)
changed: [acushnet-pa_2d33] => {
    "changed": true,
    "cmd": "Get-ExecutionPolicy -Scope Process",
    "delta": "0:00:00.499990",
    "end": "2025-04-02 20:44:31.999250",
    "rc": 0,
    "start": "2025-04-02 20:44:31.499260",
    "stderr": "",
    "stderr_lines": [],
    "stdout": "Bypass\r\n",
    "stdout_lines": [
        "Bypass"
    ]
}

TASK [Test execution policy in async mode] ***************************************************************************************************************************************************************
task path: /home/rthomas/ansible/playbooks/winPing.yaml:48
redirecting (type: modules) ansible.builtin.win_shell to ansible.windows.win_shell
[WARNING]: ansible_winrm_cleanup_tempfiles unsupported by pywinrm (is an up-to-date version of pywinrm installed?)
[WARNING]: ansible_winrm_tempfile unsupported by pywinrm (is an up-to-date version of pywinrm installed?)
<10.251.98.5> ESTABLISH WINRM CONNECTION FOR USER: ACUSHNET\.ansible on PORT 5985 TO 10.251.98.5
EXEC (via pipeline wrapper)
redirecting (type: modules) ansible.builtin.win_shell to ansible.windows.win_shell
Using module file /usr/share/ansible/collections/ansible_collections/ansible/windows/plugins/modules/win_shell.ps1
<10.251.98.5> PUT "/var/tmp/ansible/ansible-local-20214327mfslebj/tmp8la622wj" TO "C:\Users\.ansible\AppData\Local\Temp\ansible-tmp-1743626672.2079337-2021618-130712028681487\AnsiballZ_win_shell.ps1"
EXEC (via pipeline wrapper)
The full traceback is:
Failed to start async process: 2 (Access denied)
At line:93 char:9
+         throw "Failed to start async process: $rc ($error_msg)"
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Failed to start...(Access denied):String) [], RuntimeException
    + FullyQualifiedErrorId : Failed to start async process: 2 (Access denied)

ScriptStackTrace:
at <ScriptBlock>, <No file>: line 93
at <ScriptBlock><End>, <No file>: line 144
at <ScriptBlock>, <No file>: line 7
fatal: [acushnet-pa_2d33]: FAILED! => {
    "changed": false,
    "msg": "internal error: failed to run exec_wrapper action async_wrapper: Failed to start async process: 2 (Access denied)"
}

PLAY RECAP ***********************************************************************************************************************************************************************************************
acushnet-pa_2d33           : ok=1    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
localhost                  : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```

**Comment by jborean93** [comment]
By default Ansible will pipeline the module code to the Windows host to execute which means it won't try to copy the file to then execute which your output is indicating it happening. The only time this would happen is if you have set `ANSIBLE_KEEP_REMOTE_FILES` which is designed for debugging operations and should not be used in a normal situation. Did you have that enabled for debugging this particular problem?

The error would indicate that the async task failed to start the powershell process and it's not related to PowerShell itself trying to run a script. Are you running as an administrator user on the Windows host?

**Comment by ryanthomas-logility** [comment]
I enabled to debug.

**Comment by ryanthomas-logility** [comment]
@jborean93 
"task failed to start the powershell process". Yes this is my suspicion. 

I am using a domain user, who is in the built in administrators group.

I disabled the file retention and reran the task.

TASK [Test execution policy in async mode] ***************************************************************************************************************************************************************
task path: /home/.ansible/ansible/playbooks/winPing.yaml:48
redirecting (type: modules) ansible.builtin.win_shell to ansible.windows.win_shell
redirecting (type: modules) ansible.builtin.win_shell to ansible.windows.win_shell
Using module file /usr/share/ansible/collections/ansible_collections/ansible/windows/plugins/modules/win_shell.ps1
Pipelining is enabled.
<10.251.98.5> ESTABLISH WINRM CONNECTION FOR USER: domain\.ansible on PORT 5985 TO 10.251.98.5
EXEC (via pipeline wrapper)
The full traceback is:
Failed to start async process: 2 (Access denied)
At line:93 char:9
+         throw "Failed to start async process: $rc ($error_msg)"
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Failed to start...(Access denied):String) [], RuntimeException
    + FullyQualifiedErrorId : Failed to start async process: 2 (Access denied)

ScriptStackTrace:
at <ScriptBlock>, <No file>: line 93
at <ScriptBlock><End>, <No file>: line 144
at <ScriptBlock>, <No file>: line 7
fatal: [servername_2d33]: FAILED! => {
    "changed": false,
    "msg": "internal error: failed to run exec_wrapper action async_wrapper: Failed to start async process: 2 (Access denied)"
}

**Comment by jborean93** [comment]
Could you try and run this playbook and share the info from the debug tasks

```yaml
- hosts: SERVER2025
  gather_facts: false
  tasks:
  - name: enable WMI tracing
    ansible.windows.win_command: 'wevtutil.exe set-log Microsoft-Windows-WMI-Activity/Trace /enabled:true /quiet'

  - block:
    - name: run async test
      ansible.windows.win_ping:
      async: 60
      poll: 2
      ignore_errors: true

    always:
    - name: disable WMI tracing
      ansible.windows.win_command: 'wevtutil.exe set-log Microsoft-Windows-WMI-Activity/Trace /enabled:false'

  - name: get current user info
    ansible.windows.win_whoami:
    register: current_user

  - name: get Network Service info
    ansible.windows.win_whoami:
    become: true
    become_method: runas
    become_user: NetworkService
    ignore_errors: true
    register: network_service

  - name: get WMI trace logs
    ansible.windows.win_powershell:
      script: |
        $correlationId = Get-WinEvent -LogName 'Microsoft-Windows-WMI-Activity/Trace' -Oldest |
            Where-Object Message -like '*Win32_Process*' |
            Select-Object -First 1 -ExpandProperty Message |
            Select-String 'CorrelationId = ({.*});' |
            ForEach-Object { $_.Matches.Groups[1].Value }

        (Get-WinEvent -LogName 'Microsoft-Windows-WMI-Activity/Trace' -Oldest -FilterXPath "*[UserData/*/CorrelationId='$correlationId']").Message
    ignore_errors: true
    register: wmi_logs

  - name: get WMI security info
    ansible.windows.win_powershell:
      script: |
        $sec = Get-CimInstance -ClassName __SystemSecurity -Namespace 'root/cimv2'
        $rights = $sec | Invoke-CimMethod -MethodName GetCallerAccessRights
        if ($rights.ReturnValue) {
            'GetCallerAccessRights failed {0}' -f $rights.ReturnValue
        }
        else {
            'GetCallerAccessRights rights 0x{0:X8}' -f $rights.rights
        }

        $sd = $sec | Invoke-CimMethod -MethodName GetSD
        if ($sd.ReturnValue) {
            'GetSD failed {0}' -f $sd.ReturnValue
        }
        else {
            $rawSD = [System.Security.AccessControl.RawSecurityDescriptor]::new($sd.SD, 0)
            $rawSD.GetSddlForm('All')
        }
    ignore_errors: true
    register: wmi_sd

  - name: display current user info
    ansible.builtin.debug:
      var: current_user

  - name: display NetworkService info
    ansible.builtin.debug:
      var: network_service

  - name: display event log messages
    ansible.builtin.debug:
      var: wmi_logs.output

  - name: display WMI SD info
    ansible.builtin.debug:
      var: wmi_sd.output
```

This will temporarily enable WMI trace event logs and I'm hoping it might shed some light on what is going wrong. It will also:

+ Gather the privileges of the connection user and `Network Service` which is what WMI is running the process creation as
+ The current access rights of the connection user to see if maybe it is restricted somehow
+ Get the Security Descriptor of the `cimv2` namespace that `Win32_Process` lives under to see if maybe there are custom entries denying access
