### ISSUE TITLE
win_template does not resolves jinja variables in community.windows version 3.0.0

### ISSUE THREAD

**Issue by ssaroop** [ansible-collections/ansible.windows#782]
##### SUMMARY

win_template does not resolves jinja variables in version 3.0.0

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

win_template
##### ANSIBLE VERSION

```paste below
ansible-core~=2.13.7
```

##### COLLECTION VERSION

```paste below
community-windows=3.0.0
```

##### CONFIGURATION

```paste below

```

##### STEPS TO REPRODUCE

Create example.txt.j2
```
Hello, {{ username }}!
Welcome to {{ hostname }}.
```

```yaml
- name: Deploy a templated file to Windows
  hosts: windows
  vars:
    username: ssaroop
    hostname: win-server01
  tasks:
    - name: Copy templated file to Windows
      ansible.windows.win_template:
        src: example.txt.j2
        dest: C:\Users\Public\example.txt
```

##### EXPECTED RESULTS

Expect C:\Users\Public\example.txt to contain text
```
Hello, ssaroop!
Welcome to win-server01.
```

##### ACTUAL RESULTS

Actual C:\Users\Public\example.txt to contain text
```
Hello, {{ username }}!
Welcome to {{ hostname }}.
```

```paste below

```
