### ISSUE TITLE
RFE: win_service should return `failure_actions`

### ISSUE THREAD

**Issue by opoplawski** [ansible-collections/ansible.windows#791]
##### SUMMARY
I would like to be able to easily query the failure actions for services.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
win_service

##### ADDITIONAL INFORMATION

```
ansible -m win_service -a 'name=tssdis'  host
```
```yaml
   "can_pause_and_continue": false,
    "changed": false,
    "depended_by": [],
    "dependencies": [
        "RPCSS",
        "MSSQL$MICROSOFT##WID"
    ],
    "description": "Enables a user connection request to be routed to the appropriate Remote Desktop Session Host server in a cluster. If this service is stopped, connection requests will be routed to the first available server.",
    "desktop_interact": false,
    "display_name": "Remote Desktop Connection Broker",
    "exists": true,
    "name": "Tssdis",
    "path": "C:\\Windows\\System32\\tssdis.exe",
    "start_mode": "auto",
    "state": "running",
    "username": "NT Authority\\NetworkService"
     "failure_actions": [
          { "type": "restart" },
          { "type": "restart",
            "delay_ms": 5000 },
          { "type": "restart",
            "delay_ms": 10000 } ]
```
