### ISSUE TITLE
win_package install from network share does not work correctly

### ISSUE THREAD

**Issue by stefangwle** [ansible-collections/ansible.windows#84]
##### SUMMARY
According to win_package module documentation, when  the installation file is hosted on a network share and username and password are specified, the file is not copied locally on the target server.
Actual behavior of the module is opposite. 
Local copy cause an issue when the installation files are more then one. After the copy of the installation exe and executed it cannot find the rest installation files ( dll files etc ).
In my opinion the problem is in the line 406 of win_pacakge.ps1  
if ($program_metadata.location_type -eq [LocationType]::Unc -and $null -ne $credential) {
which should be :
if ($program_metadata.location_type -eq [LocationType]::Unc -and $credential -eq $null) {

I think that the comment on lines 404 and 405 is not correct. 

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
win_package
win_package.ps1

##### ANSIBLE VERSION

`ansible 2.9.7
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/ansible
  executable location = /opt/rh/rh-python36/root/usr/bin/ansible
  python version = 3.6.9 (default, Sep 11 2019, 16:40:19) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]``

##### CONFIGURATION

```paste below
DEFAULT_HOST_LIST(/root/ansible/ansible.cfg) = ['/root/ansible/inventory']
DEFAULT_MANAGED_STR(/root/ansible/ansible.cfg) = Ansible managed: {file} modified on %Y-%m-%d %H:%M:%S
DEFAULT_REMOTE_USER(/root/ansible/ansible.cfg) = stefan
DEPRECATION_WARNINGS(/root/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Red Hat Enterprise Linux Server release 7.8 (Maipo)

##### STEPS TO REPRODUCE

Try to install a package hosted on windows network share, and specify username and password to access the share.

```yaml
  - name: Run installer from mounted network share
    win_package:    
      path: \\server\ServerSoftware\SQL\SQL2017\Developer\setup.exe
      product_id: mssql2017
      user_name: DOMAIN\user
      user_password: password
      log_path: C:\tmp\install.log
      arguments: '/IAcceptSqlServerLicenseTerms /Q /ConfigurationFile="C:\\ConfigurationFile.ini" /SQLSYSADMINACCOUNTS="DOMAIN\user"'
      state: present
```

##### EXPECTED RESULTS

Successful installation

##### ACTUAL RESULTS

fatal: [wintstaa1187]: FAILED! => {
    "changed": false,
    "msg": "unexpected rc from install xb1rikep.aes: see rc, stdo ut and stderr for more details",
    "rc": 3221225781,
    "reboot_required": false,
    "stderr": "",
    "stderr_lines": [],
    "stdout": "",
    "stdout_lines": []

```paste below

```

**Comment by jborean93** [comment]
>  when the installation file is hosted on a network share and username and password are specified, the file is not copied locally on the target server.

I see the opposite, in the [docs](https://docs.ansible.com/ansible/latest/modules/win_package_module.html) under `path` it states

> There are cases where this file will be copied locally to the server so it can access it, see the notes for more info.

Under the notes it also states

> Packages will be temporarily downloaded or copied locally when path is a network location and credential delegation is not set, or path is a URL and the file is not an MSI.

That indicates that the file will be copied from a network path if credential delegation is not set, i.e. when you aren't using the native credential delegation options of CredSSP/Kerberos with delegation/become.

In any case the module has changed dramatically since the collection has been released and all of that code in 2.9 no longer applies. While it will still copy the file locally if explicit credentials are used which is [done here](https://github.com/ansible-collections/ansible.windows/blob/cd21ef8fd0c6250a896d762b4a410e9806538106/plugins/modules/win_package.ps1#L461), this configuration is deprecated in favour of become. Instead of using the `username`/`password` option specifically in the win_package options you should use the native mechanism in Ansible which works for any module.

```yaml
- win_package:
    path: \\server\ServerSoftware\SQL\SQL2017\Developer\setup.exe
    product_id: mssql2017
    user_name: DOMAIN\user
    user_password: password
    log_path: C:\tmp\install.log
    arguments: '/IAcceptSqlServerLicenseTerms /Q /ConfigurationFile="C:\\ConfigurationFile.ini" /SQLSYSADMINACCOUNTS="DOMAIN\user"'
    state: present
  become: yes
  become_method: runas
  vars:
    ansible_become_user: DOMAIN\user
    ansible_become_pass: Password
    ansible_become_flags: logon_type=new_credentials logon_flags=netcredentials_only
```

We have more details on this specific scenario with become [here](https://docs.ansible.com/ansible/latest/user_guide/become.html#become-flags-for-windows). Ultimately what this does is it will run the module with explicit credentials that are used when accessing a network path. This user does not need to be a valid logon for that host so it will work for fileshare that are secured with a domain user.
