### ISSUE TITLE
New win_capability module

### ISSUE THREAD

**Issue by RRohi** [ansible-collections/ansible.windows#96]
##### SUMMARY
Would be nice if there was a module to configure (enable/disable) Windows Capabilities, similar to win_optional_feature module.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

I guess the new module's name would be `win_capability`?

##### ADDITIONAL INFORMATION

The module would replicate the functionality of the cmdlets found via this query:
```powershell
Get-Command -Module Dism -Noun WindowsCapability
```

It would allow people to enable, or disable Windows Capabilities, along with Optional Features and Features (on Servers).

Since Capabilities have version numbers in their names, we should be able to use wildcards, or provide names partially.

Below is an example how I would add RSAT Windows Capabilities with PowerShell and a mockup of an Ansible task where I would disable a couple of Capabilities that are enabled by default.

The asterisk after "{{ item }}" is clearly not correctly placed, I don't know how it should work, but it should indicate that it would be best if the name parameter would accept partial Capability names.

```powershell
Get-WindowsCapability -Online -Name Rsat.* | Add-WindowsCapability -Online
```
```yaml
- name: Disable unnecessary Windows Capabilities
  win_capability:
    name: "{{ item }}"*
    state: absent
  loop:
    - 'XPS.Viewer'
    - 'App.Support.QuickAssist'
    - 'Browser.InternetExplorer'
```
